### PR TITLE
Replace panic calls with proper error handling

### LINKED ISSUE #7955: [chore]: Replace panic() calls with proper error handling
### Summary

Several commands in the Jaeger codebase use `panic()` for error handling. This issue proposes replacing those `panic()` calls with proper error returns and handling to improve robustness and prevent unexpected runtime crashes.

### Files Affected

- `cmd/tracegen/main.go`
- `cmd/es-rollover/app/flags.go` 
- `cmd/es-index-cleaner/app/flags.go` 
- `cmd/internal/flags/flags.go` 

### Problem

Using `panic()` for expected error scenarios:
- Causes abrupt application crashes
- Makes CLI tools less user-friendly
- Prevents graceful error reporting and testing

### Proposed Solution

1. Replace `panic(err)` with proper error returns.
2. Update callers to handle and propagate errors appropriately.
3. Improve error messages to be more descriptive and user-friendly.
4. Add or update tests to cover error paths where applicable.

### Impact

- Improves stability and reliability of Jaeger CLI tools
- Aligns with Go best practices for error handling
- No functional or API-breaking changes

### PR DESCRIPTION
**Pull request by aaryan359**
This PR replaces several `panic()` calls with proper error handling across Jaeger CLI tools, improving robustness and preventing unexpected runtime crashes.

## Which problem is this PR solving?
- Resolves #7955

## Description of the changes
- Replaced `panic(err)` with error returns in `InitFromViper` methods
  - `cmd/es-rollover/app/flags.go`
  - `cmd/es-index-cleaner/app/flags.go`
- Updated `ParseJaegerTags` to return an error for invalid tag pairs
  - `cmd/internal/flags/flags.go`
- Updated all callers to properly handle returned errors
  - `cmd/es-index-cleaner/main.go`
  - `cmd/es-rollover/app/actions.go`
- Updated and extended tests to assert error conditions instead of panics
  - `cmd/es-rollover/app/flags_test.go`
  - `cmd/es-index-cleaner/app/flags_test.go`
  - `cmd/internal/flags/flags_test.go`

These changes align with Go best practices and improve CLI stability without changing functionality.

## How was this change tested?
- `make fmt`
- `make lint`
- `make test`

All tests pass successfully.

## Checklist
- [x] I have read the contributing guidelines
- [x] I have signed all commits
- [x] I have added/updated unit tests where applicable
- [x] I have run lint and test steps successfully

### CODE REVIEW

File: cmd/es-rollover/app/flags_test.go [hunk 1]
```diff
@@ -35,7 +35,8 @@ func TestBindFlags(t *testing.T) {
 	})
 	require.NoError(t, err)
 
-	c.InitFromViper(v)
+	err = c.InitFromViper(v)
+	require.NoError(t, err)
```
Comment (yurishkuro) [inline cmd/es-rollover/app/flags_test.go]:
```suggestion
	require.NoError(t, c.InitFromViper(v))
```

File: cmd/es-index-cleaner/app/flags_test.go [hunk 2]
```diff
@@ -33,7 +33,8 @@ func TestBindFlags(t *testing.T) {
 	})
 	require.NoError(t, err)
 
-	c.InitFromViper(v)
+	err = c.InitFromViper(v)
+	require.NoError(t, err)
```
Comment (yurishkuro) [inline cmd/es-index-cleaner/app/flags_test.go]:
```suggestion
	require.NoError(t, c.InitFromViper(v))
```

File: cmd/tracegen/main.go [hunk 3]
```diff
@@ -37,7 +38,8 @@ func main() {
 	zc.Level = zap.NewAtomicLevelAt(zapcore.Level(-8)) // level used by OTEL's Debug()
 	logger, err := zc.Build()
 	if err != nil {
-		panic(err)
```
Comment (yurishkuro) [inline cmd/tracegen/main.go:40]: panic is fine in main, and is actually better than printf since it prints stacktrace

**Review by yurishkuro — CHANGES_REQUESTED** [review]

**Comment by aaryan359** [comment]
@yurishkuro,
I’ve updated the tests as suggested and restored the `panic` in `tracegen/main.go`.  
Please let me know if there’s anything else to tweak.

**Comment by aaryan359** [comment]
@yurishkuro thanks for the review!  
I noticed a small coverage change due to the new error-handling paths — let me know if you’d like me to add tests for those cases, happy to do so.

**Comment by aaryan359** [comment]
@jkowall, now i fixed the  test coverage and fixed the description also . can this meged now

**Review by yurishkuro — APPROVED** [review]
