### PR TITLE
Enable errorlint linter and fix errors

### LINKED ISSUE #5027: Enable errorlint linter
Last time we checked, there were about 20 places in the code that did not use `fmt.Errorf("...: %w, err)` error wrapping syntax, which is checked by the `errorlint` linter. 

* [ ] fix the code in those places
* [ ] enable the linter

https://github.com/jaegertracing/jaeger/blob/baed450f5f345ef915e76293bf11f76883604f31/.golangci.yml#L53-L56

### PR DESCRIPTION
**Pull request by 1-8**
## Which problem is this PR solving?
Resolves #5027 

## Description of the changes
- Use `%w` when wrapping errors
- use `errors.Is` and `errors.As` instead of explicit cast or comparison
- Fix a bug 249c9592 where direct and wrapped io.EOF were conflicting
- Enable error linting

## How was this change tested?
- 

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [x] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Comment by akagami-harsh** [comment]
@1-8 , `DCO` is failing on your PR. Follow the [CONTRIBUTING_GUIDELINES](https://github.com/jaegertracing/jaeger/blob/main/CONTRIBUTING_GUIDELINES.md#certificate-of-origin---sign-your-work). You can read more about DCO [here](https://github.com/jaegertracing/jaeger/blob/main/CONTRIBUTING_GUIDELINES.md#certificate-of-origin---sign-your-work)

**Comment by 1-8** [comment]
> @1-8 , `DCO` is failing on your PR. Follow the [CONTRIBUTING_GUIDELINES](https://github.com/jaegertracing/jaeger/blob/main/CONTRIBUTING_GUIDELINES.md#certificate-of-origin---sign-your-work). You can read more about DCO [here](https://github.com/jaegertracing/jaeger/blob/main/CONTRIBUTING_GUIDELINES.md#certificate-of-origin---sign-your-work)

Thank you for pointing out the DCO issue. I've completed the signoff.

File: cmd/es-rollover/app/init/action.go [hunk 1]
```diff
@@ -84,7 +85,8 @@ func (c Action) Do() error {
 func createIndexIfNotExist(c client.IndexAPI, index string) error {
 	err := c.CreateIndex(index)
 	if err != nil {
-		if esErr, ok := err.(client.ResponseError); ok {
+		var esErr client.ResponseError
```
Comment (yurishkuro) [inline cmd/es-rollover/app/init/action.go:88]: Does this not be a pointer `*client.ResponseError`? E.g. this doesn't work if you remove the pointer https://go.dev/play/p/-mL6xwpYpIa

File: pkg/es/client/ilm_client.go [hunk 2]
```diff
@@ -34,7 +35,8 @@ func (i ILMClient) Exists(name string) (bool, error) {
 		method:   http.MethodGet,
 	})
 
-	if respError, isResponseErr := err.(ResponseError); isResponseErr {
+	var respError ResponseError
```
Comment (yurishkuro) [inline pkg/es/client/ilm_client.go:38]: pointer?

File: pkg/es/client/index_client.go [hunk 3]
```diff
@@ -108,7 +109,8 @@ func (i *IndicesClient) indexDeleteRequest(concatIndices string) error {
 		method:   http.MethodDelete,
 	})
 	if err != nil {
-		if responseError, isResponseError := err.(ResponseError); isResponseError {
+		var responseError ResponseError
```
Comment (yurishkuro) [inline pkg/es/client/index_client.go:112]: pointer?

File: cmd/anonymizer/app/uiconv/extractor.go [hunk 4]
```diff
@@ -63,7 +64,7 @@ func (e *Extractor) Run() error {
 			spans = append(spans, *span)
 		}
 	}
-	if err != io.EOF {
+	if !errors.Is(err, io.EOF) {
 		return fmt.Errorf("failed when scanning the file: %w", err)
 	}
 	trace := uimodel.Trace{
```
Comment (yurishkuro) [inline cmd/anonymizer/app/uiconv/extractor.go:70]: hm, a test in this pkg ran into NPE (I don't recall it being flaky)
```
--- FAIL: TestExtractor_TraceScanError (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9e87fd]

goroutine 23 [running]:
testing.tRunner.func1.2({0xa387c0, 0xe3df40})
	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1545 +0x3f7
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1548 +0x716
panic({0xa387c0?, 0xe3df40?})
	/opt/hostedtoolcache/go/1.21.5/x64/src/runtime/panic.go:920 +0x270
github.com/jaegertracing/jaeger/cmd/anonymizer/app/uiconv.(*Extractor).Run(0xc0001afb00)
	/home/runner/work/jaeger/jaeger/cmd/anonymizer/app/uiconv/extractor.go:80 +0x73d
github.com/jaegertracing/jaeger/cmd/anonymizer/app/uiconv.TestExtractor_TraceScanError(0x0?)
	/home/runner/work/jaeger/jaeger/cmd/anonymizer/app/uiconv/extractor_test.go:108 +0x57f
testing.tRunner(0xc0001b31e0, 0xad75e8)
	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1595 +0x262
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.21.5/x64/src/testing/testing.go:1648 +0x846
```

Comment (yurishkuro) [reply cmd/anonymizer/app/uiconv/extractor.go:70]: debugging:
```
=== RUN   TestExtractor_TraceScanError
err != io.EOF true
!errors.Is(err, io.EOF) false
```

Comment (yurishkuro) [reply cmd/anonymizer/app/uiconv/extractor.go:69]: fixed in 249c9592 by using a custom error instead of `io.EOF` which was clashing when using `error.Is`

File: cmd/es-rollover/app/init/action.go (hunk 1 above)
Comment (yurishkuro) [reply cmd/es-rollover/app/init/action.go:88]: nvm, this is correct

**Review by yurishkuro — APPROVED** [review]

**Comment by yurishkuro** [comment]
Thank you!
