### PR TITLE
Remove TLS loading and replace with OTEL configtls

### LINKED ISSUE #4316: [Bug]: race condition when reloading TLS certificates
### What happened?

This is a continuation of this discussion: https://github.com/jaegertracing/jaeger/pull/4260#discussion_r1141124965

### Steps to reproduce

We can probably reproduce it by creating a unit test (which will run with `-race`) that does the following:
 * updates the certificates a couple of times
 * meanwhile, makes a couple of client/server calls with TLS using the same tls config

### Expected behavior

We expect that changes to certificates in a server take effect on future client connections. Instead, the test described above should detect a race condition as we try to update the same certPools that are already being used by the server (and therefore will be read on new client connections).

### Relevant log output

_No response_

### Screenshot

_No response_

### Additional context

The rough proposal would be as follows:
* make the certWatcher the owner of certPools internally, accessible via getter (instead of passing them from options.go)
* store those pools as atomic.Value
* when reloading the certs and adding the to the pools, create new pools via copy first, and store them in atomic.Value
* and most importantly, define `tls.Config.GetConfigForClient` function by returning a new config with certPools retrieved from certWatcher (similar to how we already define cfg.Get{Client}Certificate functions). This way the server will be using immutable tls configs and cert pools

NB: this probably would not address the issue of reloading root CA for the server or the client, perhaps we should not be even supporting it. GetConfigForClient would only allow supporting reloading of ClientCA on the server, per @tsaarni 's [comment](https://github.com/jaegertracing/jaeger/pull/4260#discussion_r1141305034).

### Jaeger backend version

_No response_

### SDK

_No response_

### Pipeline

_No response_

### Stogage backend

_No response_

### Operating system

_No response_

### Deployment model

_No response_

### Deployment configs

_No response_

### PR DESCRIPTION
**Pull request by yurishkuro**
## Which problem is this PR solving?
- Resolves #4316
- The last places where racy TLS cert loading code was used

## Description of the changes
- Remove our custom logic for loading certificates
- Fully rely on `configtls` module from otel-collector

## How was this change tested?
- CI

### CODE REVIEW

**Comment by yurishkuro** [comment]
@chahatsagarmain thanks to your changes we can now remove this tls watcher that was causing race conditions.

File: cmd/agent/app/reporter/grpc/builder_test.go [hunk 1]
```diff
@@ -308,12 +315,10 @@ func TestProxyClientTLS(t *testing.T) {
 			defer cancel()
 			var opts []grpc.ServerOption
 			if test.serverTLS.Enabled {
-				tlsCfg, err := test.serverTLS.Config(zap.NewNop())
+				tlsCfg, err := test.serverTLS.ToOtelServerConfig().LoadTLSConfig(ctx)
```
Comment (mahadzaryab1) [inline cmd/agent/app/reporter/grpc/builder_test.go:318]: can we change the test case struct itself to hold `configtls.ServerConfig` so that we don't have to do this conversion here?

File: pkg/config/tlscfg/options_test.go [hunk 2]
```diff
@@ -4,178 +4,14 @@
...
-					cert, err = cfg.GetClientCertificate(&tls.CertificateRequestInfo{})
-					require.NoError(t, err)
-					assert.Equal(t, &c, cert)
-				}
-			}
-			require.NoError(t, test.options.Close())
-		})
-	}
-}
+// var testCertKeyLocation = "./testdata"
```
Comment (mahadzaryab1) [inline pkg/config/tlscfg/options_test.go:14]: can we remove this?

**Review by mahadzaryab1 — COMMENTED** [review]
just a couple of nits

File: cmd/agent/app/reporter/grpc/builder_test.go (hunk 1 above)
Comment (yurishkuro) [reply cmd/agent/app/reporter/grpc/builder_test.go:318]: we could, but it would be just unnecessary changes in the PR. We're still reliant on the tlscfg structs in the main code. Plus, this is legacy agent code we don't even use anymore.

File: cmd/agent/app/reporter/grpc/flags.go [hunk 3]
```diff
@@ -44,7 +44,10 @@ func (b *ConnBuilder) InitFromViper(v *viper.Viper) (*ConnBuilder, error) {
 	if err != nil {
 		return b, fmt.Errorf("failed to process TLS options: %w", err)
 	}
-	b.TLS = tls
+	if tls.Enabled {
+		tlsConf := tls.ToOtelClientConfig()
+		b.TLS = &tlsConf
+	}
```
Comment (mahadzaryab1) [inline cmd/agent/app/reporter/grpc/flags.go:50]: do we want to add a test here for the missing code coverage?

**Review by mahadzaryab1 — APPROVED** [review]
lgtm

File: cmd/agent/app/reporter/grpc/flags.go (hunk 3 above)
Comment (yurishkuro) [reply cmd/agent/app/reporter/grpc/flags.go:50]: done
