### PR TITLE
[v2] Change e2e jaeger-v2 binary log output to temp file

### LINKED ISSUE #5421: Improve logging in e2e tests
## marking log streams

When we run jaeger-v2 binary as part of the e2e tests, we direct its stdout/err to the parent's output. https://github.com/jaegertracing/jaeger/blob/4dc7708451b5d93c1775ad3b58cc04b5e314e584/cmd/jaeger/internal/integration/e2e_integration.go#L58-L59

This results in logs that are somewhat difficult to distinguish:
```
=== RUN   TestESStorage/GetLargeSpans
    integration.go:205: Testing Large Trace over 10K ...
    integration.go:375: Dropped binary type attributes from trace ID: 0000000000000011
2024/05/05 16:47:30 traces export: context deadline exceeded: rpc error: code = DeadlineExceeded desc = context deadline exceeded
    integration.go:145: Waiting for storage backend to update documents, iteration 1 out of 100
```

In this example I assume the line `traces export: context deadline exceeded` is coming from the binary, not from the test. It would be good if there was some kind of prefix in the logs to indicate that, similar to how docker compose prefixes the logs with the service name:
```
hotrod-hotrod-1  | 2024-05-05T19:07:39.470Z	INFO	frontend/server.go:75	Starting	{"service": "frontend", "address": "http://0.0.0.0:8080"}
hotrod-jaeger-1  | {"level":"info","ts":1714936060.192909,"caller":"grpc@v1.57.0/clientconn.go:1303","msg":"[core][Channel #1 SubChannel #2] Subchannel Connectivity change to IDLE, last error: connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:4317: connect: connection refused\"","system":"grpc","grpc_log":true}
```

## more verbose logging from the binary

considering how difficult it is to troubleshoot e2e tests failing we should consider running with a lot more logging.

cc @james-ryans

### PR DESCRIPTION
**Pull request by james-ryans**
## Which problem is this PR solving?
- Resolves #5421

## Description of the changes
- Instead of throwing binary logs to the parent's output, it now writes the logs to a temp file and only outputs the logs if the test fails. This behavior is similar to the current v1 tests that run `docker logs` if failed.
- Here's the outcome if the test fails.
```
=== NAME  TestGRPCStorage
    e2e_integration.go:88: Jaeger-v2 logs:
        2024/05/08 00:41:25 application version: git-commit=, git-version=, build-date=
        2024-05-08T00:41:25.557+0700	info	service@v0.99.0/service.go:99	Setting up own telemetry...
        2024-05-08T00:41:25.557+0700	info	service@v0.99.0/telemetry.go:103	Serving metrics	{"address": ":8888", "level": "Normal"}
        2024-05-08T00:41:25.557+0700	info	exporter@v0.99.0/exporter.go:275	Development component. May change in the future.	{"kind": "exporter", "data_type": "traces", "name": "jaeger_storage_exporter"}
        2024-05-08T00:41:25.557+0700	info	service@v0.99.0/service.go:166	Starting jaeger...	{"Version": "git-commit=, git-version=, build-date=", "NumCPU": 8}
        ...
        2024-05-08T00:41:28.151+0700	warn	app/grpc_handler.go:105	trace not found	{"kind": "extension", "name": "jaeger_query", "id": "0000000000000011", "error": "trace not found"}
        2024-05-08T00:41:29.159+0700	warn	app/grpc_handler.go:105	trace not found	{"kind": "extension", "name": "jaeger_query", "id": "0000000000000001", "error": "trace not found"}
        2024-05-08T00:42:20.300+0700	info	exporterhelper/retry_sender.go:118	Exporting failed. Will retry the request after interval.	{"kind": "exporter", "data_type": "traces", "name": "jaeger_storage_exporter", "error": "plugin error: rpc error: code = Unavailable desc = error reading from server: read tcp [::1]:60235->[::1]:17271: read: connection reset by peer", "interval": "4.858861617s"}
--- ❌ FAIL: TestGRPCStorage (71.93s)
    ...
    --- ✅ PASS: TestGRPCStorage/GetLargeSpans (50.57s)
    --- ❌ FAIL: TestGRPCStorage/FindTraces (17.11s)
        --- ✅ PASS: TestGRPCStorage/FindTraces/Tags_in_one_spot_-_Tags (0.02s)
        ...
        --- ❌ FAIL: TestGRPCStorage/FindTraces/Operation_name_+_max_Duration (5.13s)
        ...
        --- ✅ PASS: TestGRPCStorage/FindTraces/Multiple_Traces (0.02s)
❌ FAIL
coverage: 13.0% of statements in ./...
❌ FAIL	github.com/jaegertracing/jaeger/cmd/jaeger/internal/integration	72.620s
❌ FAIL
```

## How was this change tested?
- Run locally the `STORAGE=grpc SPAN_STORAGE_TYPE=memory make jaeger-v2-storage-integration-test` command with success and fail scenario. 

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [ ] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Review by yurishkuro — COMMENTED** [review]
a few comments:
  1. since we're writing to files, there's no need to mix stdout and stderr anymore, we can write to two files and dump them separately
  2. I'd say you want to kill the process first, and then read & dump the log files
  3. I am curious if we could create a [foldable section](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#grouping-log-lines) in the GH running output. Not sure if it will work when using `t.Logf`, I assume the special annotation needs to be at the start of the line

**Comment by james-ryans** [comment]
This is the output for the group section in my local, since the CI has passed all the tests and I'm not sure if this actually working.
```
=== NAME  TestGRPCStorage/FindTraces
    logger.go:146: 2024-05-08T11:06:40.783+0700	INFO	Memory storage initialized	{"configuration": {"MaxTraces":0}}
    remote_memory_storage.go:44: Starting in-process remote storage server on :17271
    logger.go:146: 2024-05-08T11:06:40.783+0700	INFO	Starting GRPC server	{"addr": "[::]:17271"}
::group::Jaeger-v2 binary logs
=== NAME  TestGRPCStorage
    e2e_integration.go:101: Jaeger-v2 output logs:
    e2e_integration.go:105: Jaeger-v2 error logs:
        2024/05/08 11:05:41 application version: git-commit=, git-version=, build-date=
        2024-05-08T11:05:41.772+0700	info	service@v0.100.0/service.go:102	Setting up own telemetry...
        2024-05-08T11:05:41.772+0700	info	service@v0.100.0/telemetry.go:103	Serving metrics	{"address": ":8888", "level": "Normal"}
        2024-05-08T11:05:41.772+0700	info	exporter@v0.100.0/exporter.go:275	Development component. May change in the future.	{"kind": "exporter", "data_type": "traces", "name": "jaeger_storage_exporter"}
        2024-05-08T11:05:41.773+0700	info	service@v0.100.0/service.go:169	Starting jaeger...	{"Version": "git-commit=, git-version=, build-date=", "NumCPU": 8}
        ...
::endgroup::
--- ✅ PASS: TestGRPCStorage (59.71s)
```

File: cmd/jaeger/internal/integration/e2e_integration.go [hunk 1]
```diff
@@ -77,9 +94,23 @@ func (s *E2EStorageIntegration) e2eInitialize(t *testing.T, storage string) {
 	t.Log("Jaeger-v2 is ready")
 	t.Cleanup(func() {
 		require.NoError(t, cmd.Process.Kill())
+		if t.Failed() {
+			// A Github Actions special annotation to create a foldable section
+			// in the Github runner output.
+			// https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#grouping-log-lines
+			fmt.Println("::group::Jaeger-v2 binary logs")
```
Comment (yurishkuro) [inline cmd/jaeger/internal/integration/e2e_integration.go:101]: I don't think it'll work with print, it's not guaranteed to be properly synced with t.Logf

**Review by yurishkuro — APPROVED** [review]

File: cmd/jaeger/internal/integration/e2e_integration.go (hunk 1 above)
Comment (james-ryans) [reply cmd/jaeger/internal/integration/e2e_integration.go:101]: What if we use fmt.Printf to dump the binary log files? It will output the logs like this
```
::group::Jaeger-v2 binary logs
Jaeger-v2 output logs:
Jaeger-v2 error logs:
2024/05/08 13:35:55 application version: git-commit=, git-version=, build-date=
2024-05-08T13:35:55.403+0700	info	service@v0.100.0/service.go:102	Setting up own telemetry...
...
```

This is how it looks in real case https://github.com/jaegertracing/jaeger/actions/runs/8997482037/job/24715702727?pr=5431#step:9:874.

File: cmd/jaeger/internal/integration/e2e_integration.go [hunk 2]
```diff
@@ -77,9 +94,23 @@ func (s *E2EStorageIntegration) e2eInitialize(t *testing.T, storage string) {
...
+			outLogs, err := os.ReadFile(outFile.Name())
+			require.NoError(t, err)
+			fmt.Printf("Jaeger-v2 output logs:\n%s", outLogs)
+
+			errLogs, err := os.ReadFile(errFile.Name())
+			require.NoError(t, err)
+			fmt.Printf("Jaeger-v2 error logs:\n%s", errLogs)
+			// End of Github Actions foldable section annotation.
+			fmt.Println("::endgroup::")
+		}
```
Comment (yurishkuro) [inline cmd/jaeger/internal/integration/e2e_integration.go:111]: perhaps it makes sense to configure codecov to ignore cmd/jaeger/internal/integration/

**Review by yurishkuro — APPROVED** [review]
