### PR TITLE
Clarify deadlock panic message

### LINKED ISSUE #2603: ingester  crash
**Describe the bug**
image
is it a bug?

**Version (please complete the following information):**
 - OS: [e.g. Linux]  Linux
 - Jaeger version: [e.g. 1.8]  1.20
- Deployment: [e.g. bare metal, Docker, Kubernetes, ...]  K8S 1.16

**What troubleshooting steps did you try?**
Try to follow https://www.jaegertracing.io/docs/latest/troubleshooting/ and describe how far you were able to progress and/or which steps did not work.

I have tried several times

**Additional context**

### PR DESCRIPTION
**Pull request by yurishkuro**
Fixes #2603.

### CODE REVIEW

File: cmd/ingester/app/consumer/deadlock_detector.go [hunk 1]
```diff
@@ -68,7 +68,8 @@ func newDeadlockDetector(metricsFactory metrics.Factory, logger *zap.Logger, int
 		time.Sleep(time.Second) // Allow time to flush metric
 
 		buf := make([]byte, 1<<20)
-		logger.Panic("No messages processed in the last check interval",
+		logger.Panic("No messages processed in the last check interval, possible deadlock, exiting. "+
```
Comment (objectiser) [inline cmd/ingester/app/consumer/deadlock_detector.go:71]: LGTM - only one suggestion might be to remove the stack trace, so it doesn't look like an unexpected exit?

**Review by objectiser — APPROVED** [review]
