### PR TITLE
Exit properly after displayed help

### LINKED ISSUE #2581: OTEL all-in-one `--help` hangs
**Describe the bug**
May be related to #2566.

Running `go run ./cmd/all-in-one --help` prints help documentation, but appears to hang afterwards.

**To Reproduce**
1. `cd cmd/opentelemetry`
2. `go run ./cmd/all-in-one --help`

Output:
```
Jaeger OpenTelemetry all-in-one

Usage:
  jaeger-opentelemetry-all-in-one [flags]
...
      --sampling.strategies-file string                    The path for the sampling strategies file in JSON format. See sampling documentation to see format of the file
^Csignal: interrupt
```

**Expected behavior**
Print help documentation and exit successfully.

**Screenshots**

**Version (please complete the following information):**
 - OS: macOS
 - Jaeger version: master
 - Deployment: Development

**What troubleshooting steps did you try?**

**Additional context**

### PR DESCRIPTION
**Pull request by tzzed**
Signed-off-by: Toufik Zarouali <zerouali.t@gmail.com>

## Which problem is this PR solving?
- This fixes #2581 

## Short description of the changes
- Handle error returned by `cmd.ParseFlags(os.Args)`.

### CODE REVIEW

File: cmd/opentelemetry/cmd/all-in-one/main.go [hunk 1]
```diff
@@ -106,7 +108,7 @@ func main() {
 	)
 
 	// parse flags to propagate Jaeger config file flag value to viper
-	cmd.ParseFlags(os.Args)
+	parseErr := cmd.ParseFlags(os.Args)
 	err = jflags.TryLoadConfigFile(v)
 	if err != nil {
 		handleErr(fmt.Errorf("could not load Jaeger configuration file %w", err))
```
Comment (yurishkuro) [inline cmd/opentelemetry/cmd/all-in-one/main.go:114]:
```suggestion
	if err := jflags.TryLoadConfigFile(v); err != nil {
		handleErr(fmt.Errorf("could not load Jaeger configuration file: %w", err))
```

File: cmd/opentelemetry/cmd/all-in-one/main.go [hunk 2]
```diff
@@ -115,6 +117,11 @@ func main() {
 	go func() {
 		err = svc.Run()
```
Comment (yurishkuro) [inline cmd/opentelemetry/cmd/all-in-one/main.go:118]:
```suggestion
		err := svc.Run()
```

File: cmd/opentelemetry/cmd/all-in-one/main.go [hunk 3]
```diff
@@ -21,6 +21,8 @@ import (
 	"os"
 	"strings"
 
+	"github.com/spf13/pflag"
```
Comment (yurishkuro) [inline cmd/opentelemetry/cmd/all-in-one/main.go:24]: move next to other spf13 import

File: cmd/opentelemetry/cmd/all-in-one/main.go (hunk 1 above)
Comment (tzzed) [reply cmd/opentelemetry/cmd/all-in-one/main.go:114]: I didn't change this code because it doesn't solve directly the problem. 
it should have been in the related review.

File: cmd/opentelemetry/cmd/all-in-one/main.go (hunk 2 above)
Comment (tzzed) [reply cmd/opentelemetry/cmd/all-in-one/main.go:118]: In this case why not 
```go 
handleErr(svc.Run())
```

Comment (yurishkuro) [reply cmd/opentelemetry/cmd/all-in-one/main.go:118]: feel free to wrap them directly in handleErr() - always leave the code in a better state than what you found

**Review by yurishkuro — APPROVED** [review]
Thanks!
