### PR TITLE
[fix] Refactor archive storage initialization and remove error log

### LINKED ISSUE #6634: Confusing archive errors / warnings
@mahadzaryab1 there shouldn't be an error logged in this case, and for some reason both error & warning are logged twice.
```
$ make run-all-in-one
...
{"level":"error","ts":1738249897.282043,"caller":"storage/factory.go:362","msg":"Cannot init archive storage reader","error":"no memory backend registered for span store","stacktrace":"github.com/jaegertracing/jaeger/plugin/storage.(*Factory).InitArchiveStorage\n\t/Users/ysh/dev/jaegertracing/jaeger/plugin/storage/factory.go:362\ngithub.com/jaegertracing/jaeger/cmd/query/app.(*QueryOptions).BuildQueryServiceOptions\n\t/Users/ysh/dev/jaegertracing/jaeger/cmd/query/app/flags.go:153\nmain.main.func1\n\t/Users/ysh/dev/jaegertracing/jaeger/cmd/all-in-one/main.go:174\ngithub.com/spf13/cobra.(*Command).execute\n\t/Users/ysh/golang/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/Users/ysh/golang/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117\ngithub.com/spf13/cobra.(*Command).Execute\n\t/Users/ysh/golang/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041\nmain.main\n\t/Users/ysh/dev/jaegertracing/jaeger/cmd/all-in-one/main.go:214\nruntime.main\n\t/Users/ysh/homebrew/Cellar/go/1.23.4/libexec/src/runtime/proc.go:272"}
{"level":"info","ts":1738249897.282166,"caller":"app/flags.go:158","msg":"Archive storage not initialized"}
{"level":"error","ts":1738249897.28218,"caller":"storage/factory.go:362","msg":"Cannot init archive storage reader","error":"no memory backend registered for span store","stacktrace":"github.com/jaegertracing/jaeger/plugin/storage.(*Factory).InitArchiveStorage\n\t/Users/ysh/dev/jaegertracing/jaeger/plugin/storage/factory.go:362\ngithub.com/jaegertracing/jaeger/cmd/query/app.(*QueryOptions).BuildQueryServiceOptionsV2\n\t/Users/ysh/dev/jaegertracing/jaeger/cmd/query/app/flags.go:169\nmain.main.func1\n\t/Users/ysh/dev/jaegertracing/jaeger/cmd/all-in-one/main.go:175\ngithub.com/spf13/cobra.(*Command).execute\n\t/Users/ysh/golang/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/Users/ysh/golang/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117\ngithub.com/spf13/cobra.(*Command).Execute\n\t/Users/ysh/golang/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041\nmain.main\n\t/Users/ysh/dev/jaegertracing/jaeger/cmd/all-in-one/main.go:214\nruntime.main\n\t/Users/ysh/homebrew/Cellar/go/1.23.4/libexec/src/runtime/proc.go:272"}
{"level":"info","ts":1738249897.282228,"caller":"app/flags.go:174","msg":"Archive storage not initialized"}
```

### PR DESCRIPTION
**Pull request by mahadzaryab1**
## Which problem is this PR solving?
- Fixes #6634 

## Description of the changes
- Remove the error logs for archive storage as it is not an error if archive storage cannot be configured 
- Remove the duplicate logs by only initializing the archive storage once for both query service and query service v2 

## How was this change tested?
```
make run-all-in-one
{"level":"info","ts":1738292734.78397,"caller":"app/flags.go:168","msg":"Archive storage not initialized"}
```

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [x] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `npm run lint` and `npm run test`

### CODE REVIEW

File: plugin/storage/factory.go [hunk 1]
```diff
@@ -354,17 +354,13 @@ func (f *Factory) createArchiveSpanWriter() (spanstore.Writer, error) {
 	return factory.CreateSpanWriter()
 }
 
-func (f *Factory) InitArchiveStorage(
-	logger *zap.Logger,
-) (spanstore.Reader, spanstore.Writer) {
+func (f *Factory) InitArchiveStorage() (spanstore.Reader, spanstore.Writer) {
 	reader, err := f.createArchiveSpanReader()
 	if err != nil {
```
Comment (yurishkuro) [inline plugin/storage/factory.go:359]: what is the nature of the errors returned here? Is it "not supported" or a genuine error like "cannot connect"? If it's always the latter we should just return them and let the top caller log them. If it's not-supported then we need to expose that error as a constant and have the caller check for it with `error.Is` to avoid logging the error / stacktrace and only log "archive not supported, not initialized"

Comment (mahadzaryab1) [reply plugin/storage/factory.go:359]: @yurishkuro It can be both

```
func (f *Factory) createArchiveSpanReader() (spanstore.Reader, error) {
	factory, ok := f.archiveFactories[f.SpanReaderType]
	if !ok {
		return nil, fmt.Errorf("no %s backend registered for span store", f.SpanReaderType)
	}
	return factory.CreateSpanReader()
}

func (f *Factory) createArchiveSpanWriter() (spanstore.Writer, error) {
	factory, ok := f.archiveFactories[f.SpanWriterTypes[0]]
	if !ok {
		return nil, fmt.Errorf("no %s backend registered for span store", f.SpanWriterTypes[0])
	}
	return factory.CreateSpanWriter()
}
```

Comment (yurishkuro) [reply plugin/storage/factory.go:359]: `"no %s backend registered for span store"` is a legit error that should be displayed to the user. I was only thinking of a potential situation where in the past we did an interface cast and if `!ok` the logged "no archive", this should be warning not an error. But in the other PR we had a case where interface cast was actually successful but the implementation was returning a "not implemented" error - that one will by default be logged as an error, but should instead be also logged as a warning.

Comment (mahadzaryab1) [reply plugin/storage/factory.go:359]: @yurishkuro Do we want that to be printed at an error log? We basically try to initialize the archive storage based on the main span reader type. That error will always be printed when someone doesn't have archive configured. We have this check in `Initialize` that will return an error when someone has archive storage configured but there was an error in initialization
```go
	for kind, factory := range f.archiveFactories {
		if archivable, ok := factory.(storage.ArchiveCapable); ok && archivable.IsArchiveCapable() {
			if err := initializeFactory(kind, factory, "archive"); err != nil {
				return err
			}
		} else {
			delete(f.archiveFactories, kind)
		}
	}
```

Comment (yurishkuro) [reply plugin/storage/factory.go:359]: ideally, if they have archive storage configured but we can't instantiate it we log an error. If they didn't ask for it but we tried anyway and failed then it's a warning (Q: why would we try in this case?).

Comment (mahadzaryab1) [reply plugin/storage/factory.go:359]: For your first point - we would fail to startup when initialization fails (see https://github.com/jaegertracing/jaeger/blob/main/cmd/all-in-one/main.go#L106-L108). For your second point, we are not really trying per se - the `f.archiveFactories[f.SpanReaderType]` is checking to see if archive storage is configured. If it is, then we try to create it.

Comment (yurishkuro) [reply plugin/storage/factory.go:359]: right, but this issue was started with v1 all-on-one, so it's not just v2 start up. I think v2 model of fungible storage is much better suited to handle this error issue, I am not worried about it. But in v1 we technically also have `archive.enable` flag which is fairly equivalent to v2 way of configuration (the "roles").

Comment (mahadzaryab1) [reply plugin/storage/factory.go:359]: @yurishkuro Yeah - we do leverage the enable flag for archive storage in `Initialize` so we would fail to start up if archive storage was not configured properly. Do we want different behaviour there?

Comment (yurishkuro) [reply plugin/storage/factory.go:359]: no, failing in such case is correct

Comment (yurishkuro) [reply plugin/storage/factory.go:359]: I think my question still stands - the errors here look like real errors that should be propagated to the caller

Comment (mahadzaryab1) [reply plugin/storage/factory.go:359]: @yurishkuro Sounds good - do we want to propagate the `no %s backend registered for span store` error as well? I think that one isn't a real error because it would occur whenever someone hasn't configured archive storage.

Comment (yurishkuro) [reply plugin/storage/factory.go:359]: if v2 it's a real error that should fail startup. In v1 I don't know how this error could happen, what does it mean? Most settings are cloned from primary storage, does the error occur when some specific setting is empty for archive but `archive.enbaled=true`?

Comment (mahadzaryab1) [reply plugin/storage/factory.go:359]: @yurishkuro This flow altogether is only for v1 - v2 wouldn't go through this. It would just initialize the reader and writer directly. For your second question, that is dependent on the storage implementation and someone might run into an error based on the parameters that they've set for their archive storage. I look through the implementation and only [ES](https://github.com/jaegertracing/jaeger/blob/main/plugin/storage/es/factory.go#L197) and [Kafka](https://github.com/jaegertracing/jaeger/blob/main/plugin/storage/kafka/factory.go#L87) return a non-nil error from `CreateSpanReader`.

Comment (yurishkuro) [reply plugin/storage/factory.go:359]: should we return the errors from here?

Comment (mahadzaryab1) [reply plugin/storage/factory.go:359]: @yurishkuro we could return the errors from here if they come from `CreateSpanReader` and `CreateSpanWriter`

Comment (yurishkuro) [reply plugin/storage/factory.go:359]: yes, why don't we?

File: plugin/storage/factory.go [hunk 2]
```diff
@@ -338,37 +338,34 @@ func (f *Factory) initDownsamplingFromViper(v *viper.Viper) {
...
-	}
-	return factory.CreateSpanReader()
+type ArchiveStorage struct {
+	Reader spanstore.Reader
+	Writer spanstore.Writer
 }
 
-func (f *Factory) createArchiveSpanWriter() (spanstore.Writer, error) {
-	factory, ok := f.archiveFactories[f.SpanWriterTypes[0]]
+func (f *Factory) InitArchiveStorage() (*ArchiveStorage, error) {
```
Comment (yurishkuro) [inline plugin/storage/factory.go:346]: Why not just return 3 values?

**Review by yurishkuro — APPROVED** [review]

File: plugin/storage/factory.go (hunk 2 above)
Comment (mahadzaryab1) [reply plugin/storage/factory.go:346]: @yurishkuro I think its generally a pattern that is avoided in Go. I'm happy to change it if you like that better.

**Review by yurishkuro — APPROVED** [review]
