### PR TITLE
Fix order of the returned results from badger backend. 

### LINKED ISSUE #1913: showing latest traces not working properly using all-in-one with badger
## Requirement - what kind of business use case are you trying to solve?

Seeing the latest traces while limiting the number of results.

## Problem - what in Jaeger blocks you from solving the requirement?

With all-in-one 1.15.1 I don't get the latest X traces anymore, but it seems rather the traces with highest trace ID first.
With 1.14 I correctly get the _latest_ X number of traces, regardless of their trace id.

Running jaeger/all-in-one via docker:
```
jaeger:
    image: jaegertracing/all-in-one:1.15.1
    environment:
      - "COLLECTOR_ZIPKIN_HTTP_PORT=9411"
      - "SPAN_STORAGE_TYPE=badger"
      - "BADGER_EPHEMERAL=false"
      - "BADGER_DIRECTORY_VALUE=/badger/data"
      - "BADGER_DIRECTORY_KEY=/badger/key"
    volumes:
      - jaeger-storage:/badger
    expose:
      - "9411"
      - "16686"
    ports:
      - "16686:16686"
```
Just changing back to 1.14 shows me the latest (e.g. 20) traces again.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

It seems like the search is now giving back the first X number of traces in the given time range based on the highest traceID instead of latest time.
The behavior in 1.14 was correctly returning the latest traces first.

### PR DESCRIPTION
**Pull request by burmanm**
## Which problem is this PR solving?
Add additional tests to verify that results are returned in correct DESC order as well as add the ability to request StartTime filtering for only TraceIDs, instead of requiring complete Traces.

Fixes #1913 

## Short description of the changes

Last index scan will now do a reverse scan (badger defaults to ASC) and retain the order when doing the hash-join against previous index scan results. Otherwise the index scans will keep using the sort-merge-join.

### CODE REVIEW

File: plugin/storage/badger/spanstore/reader.go [hunk 1]
```diff
@@ -494,34 +513,34 @@ func validateQuery(p *spanstore.TraceQueryParameters) error {
...
-		startIndex := make([]byte, len(indexKeyValue)+len(startStampBytes))
+		startIndex := make([]byte, len(indexKeyValue)+8+1)
+		startIndex[len(startIndex)-1] = 0xFF
 		copy(startIndex, indexKeyValue)
-		copy(startIndex[len(indexKeyValue):], startStampBytes)
+		copy(startIndex[len(indexKeyValue):], plan.startTimeMax)
 
-		timeMax := model.TimeAsEpochMicroseconds(startTimeMax)
-		for it.Seek(startIndex); scanFunction(it, indexKeyValue, timeMax); it.Next() {
+		for it.Seek(startIndex); scanFunction(it, indexKeyValue, plan.startTimeMin); it.Next() {
```
Comment (objectiser) [inline plugin/storage/badger/spanstore/reader.go]: Has changed from startTimeMax to Min - is that correct? Is it because of reversing the time order?

File: plugin/storage/badger/spanstore/reader.go [hunk 2]
```diff
@@ -494,34 +513,34 @@ func validateQuery(p *spanstore.TraceQueryParameters) error {
...
 			item := it.Item()
 
 			// ScanFunction is a prefix scanning (since we could have for example service1 & service12)
 			// Now we need to match only the exact key if we want to add it
 			timestampStartIndex := len(it.Item().Key()) - (sizeOfTraceID + 8) // timestamp is stored with 8 bytes
 			if bytes.Equal(indexKeyValue, it.Item().Key()[:timestampStartIndex]) {
-				key := make([]byte, len(item.Key()))
-				copy(key, item.Key())
-				indexResults = append(indexResults, key)
+				traceIDBytes := item.Key()[len(item.Key())-sizeOfTraceID:]
```
Comment (objectiser) [inline plugin/storage/badger/spanstore/reader.go]: Wondering whether it would be better to move knowledge about how to extract `traceIDBytes` from the `key` into the `Item` type - or possibly have a `Key` type that encapsulates all the necessary knowledge about how the key is encoded? Could be done as a separate PR, but might make it easier to maintain.

File: plugin/storage/badger/spanstore/rw_internal_test.go [hunk 3]
```diff
@@ -100,48 +98,34 @@ func TestDecodeErrorReturns(t *testing.T) {
 	assert.Error(t, err)
 }
 
-func TestSortMergeIdsDuplicateDetection(t *testing.T) {
```
Comment (objectiser) [inline plugin/storage/badger/spanstore/rw_internal_test.go]: Could you just clarify why this test is no longer required?

File: plugin/storage/badger/spanstore/rw_internal_test.go [hunk 4]
```diff
@@ -100,48 +98,34 @@ func TestDecodeErrorReturns(t *testing.T) {
...
+				testSpan.SpanID = model.SpanID(rand.Uint64())
+				testSpan.StartTime = origStartTime.Add(time.Duration(rand.Int31n(8000)) * time.Millisecond)
+				err := sw.WriteSpan(&testSpan)
+				assert.NoError(t, err)
+			}
 		}
 
 		traces, err := rw.FindTraceIDs(context.Background(), &spanstore.TraceQueryParameters{
 			ServiceName:  "service",
+			NumTraces:    128,
```
Comment (objectiser) [inline plugin/storage/badger/spanstore/rw_internal_test.go]: Could we have similar tests where `NumTraces` is less than number of traces created - and then ensure that the most recent are returned.

Also might be worth adding an extra test that also adds a couple of tags into the mix, still ensuring that the `NumTraces` is less than the set of traces that would actually match, and ensure they are the most recent.

File: plugin/storage/badger/spanstore/reader.go [hunk 5]
```diff
@@ -155,69 +168,55 @@ func (r *TraceReader) GetTrace(ctx context.Context, traceID model.TraceID) (*mod
...
-			}
-			traces = append(traces, trace)
-		}
 
 		return nil
 	})
 
-	return traces, err
+	sort.Slice(traceKeys, func(k, h int) bool {
+		return bytes.Compare(traceKeys[k][sizeOfTraceID+1:sizeOfTraceID+1+8], traceKeys[h][sizeOfTraceID+1:sizeOfTraceID+1+8]) > 0
```
Comment (jpkrohling) [inline plugin/storage/badger/spanstore/reader.go]: I think this deserves a comment, like:

    // compares traceKeys[k][timestamp] with traceKeys[h][timestamp]

File: plugin/storage/badger/spanstore/reader.go [hunk 6]
```diff
@@ -275,81 +274,138 @@ func serviceQueries(query *spanstore.TraceQueryParameters, indexSeeks [][]byte)
...
+}
+
+// durationQueries checks non unique index of durations and returns a map for further filtering purposes
+func (r *TraceReader) durationQueries(plan *executionPlan, query *spanstore.TraceQueryParameters) map[model.TraceID]struct{} {
 	durMax := uint64(model.DurationAsMicroseconds(query.DurationMax))
 	durMin := uint64(model.DurationAsMicroseconds(query.DurationMin))
 
-	startKey := make([]byte, 0, 9)
-	endKey := make([]byte, 0, 9)
+	startKey := make([]byte, 9)
```
Comment (jpkrohling) [inline plugin/storage/badger/spanstore/reader.go]: 9 == 1 + 8, right? In other places in this source, you are using 1+8, which I find clearer than simply 9.

File: plugin/storage/badger/spanstore/reader.go [hunk 7]
```diff
@@ -494,34 +513,34 @@ func validateQuery(p *spanstore.TraceQueryParameters) error {
...
+func (r *TraceReader) scanIndexKeys(indexKeyValue []byte, plan *executionPlan) ([][]byte, error) {
 	indexResults := make([][]byte, 0)
 
-	startStampBytes := make([]byte, 8)
-	binary.BigEndian.PutUint64(startStampBytes, model.TimeAsEpochMicroseconds(startTimeMin))
-
 	err := r.store.View(func(txn *badger.Txn) error {
 		opts := badger.DefaultIteratorOptions
 		opts.PrefetchValues = false // Don't fetch values since we're only interested in the keys
+		opts.Reverse = true
```
Comment (jpkrohling) [inline plugin/storage/badger/spanstore/reader.go]: More recent first?

File: plugin/storage/badger/spanstore/rw_internal_test.go [hunk 8]
```diff
@@ -215,6 +199,7 @@ func TestMergeJoin(t *testing.T) {
 	assert.Equal(uint32(2), binary.BigEndian.Uint32(merged[1]))
 }
 
+/*
```
Comment (jpkrohling) [inline plugin/storage/badger/spanstore/rw_internal_test.go]: Is this test being re-enabled before the PR is merged?

File: plugin/storage/badger/spanstore/read_write_test.go [hunk 9]
```diff
@@ -224,17 +231,24 @@ func TestIndexSeeks(t *testing.T) {
...
 		assert.NoError(t, err)
-		assert.Equal(t, 9, len(trs))
+		assert.Equal(t, 5, len(trs))
+		testOrder(trs)
 
-		// Assert that we fetched correctly in DESC time order
-		for l := 1; l < len(trs); l++ {
-			assert.True(t, trs[l].Spans[spans-1].StartTime.Before(trs[l-1].Spans[spans-1].StartTime))
-		}
+		// Check for DESC return order without
```
[the remark this answers is not in the document]
Comment (burmanm) [reply plugin/storage/badger/spanstore/read_write_test.go]: Yeah, it's meant to say "without duration index".

File: plugin/storage/badger/spanstore/read_write_test.go [hunk 10]
```diff
@@ -244,7 +258,9 @@ func TestIndexSeeks(t *testing.T) {
 
 		trs, err = sr.FindTraces(context.Background(), params)
 		assert.NoError(t, err)
-		assert.Equal(t, 6, len(trs))
+		assert.Equal(t, 5, len(trs))
```
[the remark this answers is not in the document]
Comment (burmanm) [reply plugin/storage/badger/spanstore/read_write_test.go]: 5 is the correct number, there was an empty TraceID element in the previous version because the check for prevTraceID in the loop did not account the first iteration correctly.

File: plugin/storage/badger/spanstore/reader.go (hunk 6 above)
Comment (burmanm) [reply plugin/storage/badger/spanstore/reader.go]: Yes, it's the length of timestamp + indexKey (8+1).

File: plugin/storage/badger/spanstore/reader.go (hunk 7 above)
Comment (burmanm) [reply plugin/storage/badger/spanstore/reader.go]: Yep.

File: plugin/storage/badger/spanstore/reader.go (hunk 1 above)
Comment (burmanm) [reply plugin/storage/badger/spanstore/reader.go]: Exactly. We finish the scan when the min timestamp is hit.

File: plugin/storage/badger/spanstore/reader.go (hunk 2 above)
Comment (burmanm) [reply plugin/storage/badger/spanstore/reader.go]: The key is encoded in different way depending on the type of key. For example, primary keys that store the trace have different structure than the indexKeys.

Also, Item/Key are types used internally by badger, so that might be a bit confusing if those names were used. But yes, this could be built as "indexKey" and "traceKey" structs.

File: plugin/storage/badger/spanstore/rw_internal_test.go (hunk 4 above)
Comment (burmanm) [reply plugin/storage/badger/spanstore/rw_internal_test.go]: Such test resides in the "TestIndexSeek". This "NumTraces" parameter is actually incorrect here, the intention is just to test that since 128*32 spans were created, only 128 is returned.

File: plugin/storage/badger/spanstore/rw_internal_test.go (hunk 8 above)
Comment (burmanm) [reply plugin/storage/badger/spanstore/rw_internal_test.go]: Ah no. I'll remove the commented test. The order is different depending if we're fetching the last index or previous ones.

File: plugin/storage/badger/spanstore/read_write_test.go [hunk 11]
```diff
@@ -224,17 +231,24 @@ func TestIndexSeeks(t *testing.T) {
 		trs, err = sr.FindTraces(context.Background(), params)
 		assert.NoError(t, err)
 		assert.Equal(t, 2, len(trs))
+		testOrder(trs)
```
[the remark this answers is not in the document]
Comment (burmanm) [reply plugin/storage/badger/spanstore/read_write_test.go]: I'll add such check.

File: plugin/storage/badger/spanstore/reader.go [hunk 12]
```diff
@@ -207,12 +207,17 @@ func (r *TraceReader) scanTimeRange(plan *executionPlan) ([]model.TraceID, error
...
 
-	traceIDs := make([]model.TraceID, len(traceKeys))
+	sizeCount := len(traceKeys)
+	if plan.limit > 0 {
+		sizeCount = plan.limit
+	}
+	traceIDs := make([]model.TraceID, sizeCount)
 
-	for i := 0; i < len(traceKeys); i++ {
+	for i := 0; i < len(traceKeys) && i < sizeCount; i++ {
```
Comment (objectiser) [inline plugin/storage/badger/spanstore/reader.go]: Only needs to be `i < sizeCount`

Comment (burmanm) [reply plugin/storage/badger/spanstore/reader.go]: Actually that alone would cause error (indexoutofbounds), due to the previous lines where sizeCount could be bigger than len(traceKeys).

File: plugin/storage/badger/spanstore/read_write_test.go [hunk 13]
```diff
@@ -224,17 +234,37 @@ func TestIndexSeeks(t *testing.T) {
...
 
-		// Check for DESC return order
-		params.NumTraces = 9
+		// Check for DESC return order with duration index
+		params = &spanstore.TraceQueryParameters{
+			StartTimeMin: startT,
+			StartTimeMax: startT.Add(time.Duration(time.Hour * 1)),
+			DurationMin:  time.Duration(30 * time.Millisecond), // Filters one
+			DurationMax:  time.Duration(50 * time.Millisecond), // Filters three
```
Comment (jpkrohling) [inline plugin/storage/badger/spanstore/read_write_test.go]: DurationMax is supported then :)

File: plugin/storage/badger/spanstore/read_write_test.go [hunk 14]
```diff
@@ -128,11 +129,6 @@ func TestValidation(t *testing.T) {
 		params.Tags = map[string]string{"A": "B"}
 		_, err = sr.FindTraces(context.Background(), params)
 		assert.EqualError(t, err, "service name must be set")
-
-		// Only StartTimeMin and Max (not supported yet)
-		// _, err := sr.FindTraces(context.Background(), params)
-		// assert.EqualError(t, err, "This query parameter is not supported yet")
```
[the remark this answers is not in the document]
Comment (burmanm) [reply plugin/storage/badger/spanstore/read_write_test.go]: Yep.

**Comment by burmanm** [comment]
@jpkrohling As for the code that should be removed.. it was removed already? I think you looked at the wrong side of the compare ;)

**Comment by jpkrohling** [comment]
> As for the code that should be removed.. it was removed already? I think you looked at the wrong side of the compare ;)

What's going on with me... :-)
