### PR TITLE
[Fix] Restore ES metrics

### LINKED ISSUE #6891: [Bug]: ES store metrics got lost
### What happened?

Described in this thread https://github.com/jaegertracing/jaeger/pull/6883/files#r2007690346

### Expected behavior

Since we refactored the storage a lot this needs a fresh look. The metrics were introduced in #257. Can we still have similar metrics produced?

### PR DESCRIPTION
**Pull request by AnmolxSingh**
## Which problem is this PR solving?
-  Resolves #6891 

## Description of the changes
- Reintroduced metrics which were lost during #6883 

## How was this change tested?
- Ran writer tests

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [x] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `npm run lint` and `npm run test`

### CODE REVIEW

**Comment by AnmolxSingh** [comment]
@yurishkuro I just wanted to know about my direction at moment.

File: internal/storage/v1/elasticsearch/spanstore/writer.go [hunk 1]
```diff
@@ -41,7 +47,7 @@ type CoreSpanWriter interface {
 	// CreateTemplates creates index templates.
 	CreateTemplates(spanTemplate, serviceTemplate string, indexPrefix cfg.IndexPrefix) error
 	// WriteSpan writes a span and its corresponding service:operation in ElasticSearch
-	WriteSpan(spanStartTime time.Time, span *dbmodel.Span)
+	WriteSpan(spanStartTime time.Time, span *dbmodel.Span) error
```
Comment (Manik2708) [inline internal/storage/v1/elasticsearch/spanstore/writer.go:50]: I have worked on implementing this interface, so thought of reviewing it, why error is needed when nil is to be returned?

Comment (AnmolxSingh) [reply internal/storage/v1/elasticsearch/spanstore/writer.go:50]: I added it to keep it consistent with higher level API as it returns the error.

https://github.com/jaegertracing/jaeger/blob/04d2983038d649ebfee1da93585fea5571bdfbba/internal/storage/v1/elasticsearch/spanstore/writerv1.go#L32

Would not mind dropping it for now if preferred but I introduced it upon @yurishkuro advice.

https://github.com/jaegertracing/jaeger/issues/6891#issuecomment-2784601398

Comment (AnmolxSingh) [reply internal/storage/v1/elasticsearch/spanstore/writer.go:50]: @Manik2708 Thank you!! for reviewing the pr.
Appreciate your work and time.

Comment (Manik2708) [reply internal/storage/v1/elasticsearch/spanstore/writer.go:50]: > I added it to keep it consistent with higher level API as it returns the error.
> 
> https://github.com/jaegertracing/jaeger/blob/04d2983038d649ebfee1da93585fea5571bdfbba/internal/storage/v1/elasticsearch/spanstore/writerv1.go#L32
> 
> Would not mind dropping it for now if preferred but I introduced it upon @yurishkuro advice.
> 
> [#6891 (comment)](https://github.com/jaegertracing/jaeger/issues/6891#issuecomment-2784601398)

Ok, I also tried this but the major problem was when I was trying to reach the code coverage to 100, I discovered that the case when `WriteSpan` will be returning an error is not possible so thought of omitting it! Just now I saw the comments in the issue thread. Thanks!

Comment (Manik2708) [reply internal/storage/v1/elasticsearch/spanstore/writer.go:50]: Also please handle this error in v1 also where it is actually invoked!

File: internal/storage/v1/elasticsearch/spanstore/mocks/CoreSpanWriter.go [hunk 2]
```diff
@@ -58,8 +58,9 @@ func (_m *CoreSpanWriter) CreateTemplates(spanTemplate string, serviceTemplate s
 }
 
 // WriteSpan provides a mock function with given fields: spanStartTime, span
-func (_m *CoreSpanWriter) WriteSpan(spanStartTime time.Time, span *dbmodel.Span) {
+func (_m *CoreSpanWriter) WriteSpan(spanStartTime time.Time, span *dbmodel.Span) error{
 	_m.Called(spanStartTime, span)
+	return nil
```
Comment (Manik2708) [inline internal/storage/v1/elasticsearch/spanstore/mocks/CoreSpanWriter.go:63]: I think you have manually edited this file. If yes then it is not correct. Run `make generate-mocks` (I think that will fix the linter also)

Comment (AnmolxSingh) [reply internal/storage/v1/elasticsearch/spanstore/mocks/CoreSpanWriter.go:63]: Got it.
I just manually edited it just as to temporarily block out the error. Did not know that mocks are not to be generated (changed) manually.
Thanks! once again.

**Comment by AnmolxSingh** [comment]
@yurishkuro I ran the failing unit tests locally and all of them passed so it seems there might be a flaky failure.

File: internal/storage/v1/elasticsearch/spanstore/writer.go [hunk 3]
```diff
@@ -119,13 +128,17 @@ func getSpanAndServiceIndexFn(p SpanWriterParams, writeAlias string) spanAndServ
 }
 
 // WriteSpan writes a span and its corresponding service:operation in ElasticSearch
-func (s *SpanWriter) WriteSpan(spanStartTime time.Time, span *dbmodel.Span) {
+func (s *SpanWriter) WriteSpan(spanStartTime time.Time, span *dbmodel.Span) error {
+	s.writerMetrics.indexCreate.Attempts.Inc(1)
```
Comment (yurishkuro) [inline internal/storage/v1/elasticsearch/spanstore/writer.go:132]: why is WriteSpan == indexCreate?

File: internal/storage/v1/elasticsearch/spanstore/writerv1.go [hunk 4]
```diff
@@ -31,7 +32,10 @@ func (s *SpanWriterV1) CreateTemplates(spanTemplate, serviceTemplate string, ind
 // WriteSpan writes a span and its corresponding service:operation in ElasticSearch
 func (s *SpanWriterV1) WriteSpan(_ context.Context, span *model.Span) error {
 	jsonSpan := s.spanConverter.FromDomainEmbedProcess(span)
-	s.spanWriter.WriteSpan(span.StartTime, jsonSpan)
+	err := s.spanWriter.WriteSpan(span.StartTime, jsonSpan)
```
Comment (yurishkuro) [inline internal/storage/v1/elasticsearch/spanstore/writerv1.go:35]:
```suggestion
	return s.spanWriter.WriteSpan(span.StartTime, jsonSpan)
```

File: internal/storage/v1/elasticsearch/spanstore/writer.go [hunk 5]
```diff
@@ -119,13 +128,17 @@ func getSpanAndServiceIndexFn(p SpanWriterParams, writeAlias string) spanAndServ
...
+
 	spanIndexName, serviceIndexName := s.spanServiceIndex(spanStartTime)
 	if serviceIndexName != "" {
 		s.writeService(serviceIndexName, span)
 	}
 	s.writeSpan(spanIndexName, span)
 	s.logger.Debug("Wrote span to ES index", zap.String("index", spanIndexName))
+
+	return nil
```
Comment (yurishkuro) [inline internal/storage/v1/elasticsearch/spanstore/writer.go:141]:
```suggestion
	s.logger.Debug("Writing span to ES index", zap.String("index", spanIndexName))
	return s.writeSpan(spanIndexName, span)
```

File: internal/storage/elasticsearch/config/config.go [hunk 6]
```diff
@@ -239,18 +239,37 @@ func NewClient(c *Configuration, logger *zap.Logger, metricsFactory metrics.Fact
 			}
```
Comment (yurishkuro) [inline internal/storage/elasticsearch/config/config.go:239]: `if !ok { return }` makes no sense. Suggestion
```
if ok {
  m.Delete(id)
} else {
  start = time.Now()
}
```

Comment (AnmolxSingh) [reply internal/storage/elasticsearch/config/config.go:241]: Fixed

File: internal/storage/v1/elasticsearch/spanstore/writerv1.go (hunk 4 above)
Comment (AnmolxSingh) [reply internal/storage/v1/elasticsearch/spanstore/writerv1.go:35]: fixed

File: internal/storage/v1/elasticsearch/spanstore/writer.go (hunk 5 above)
Comment (AnmolxSingh) [reply internal/storage/v1/elasticsearch/spanstore/writer.go:141]: Actually I believe this cannot be done as writeSpan uses .Add() method which is async and does not return anything.

File: internal/storage/v1/elasticsearch/spanstore/writer.go (hunk 3 above)
Comment (yurishkuro) [reply internal/storage/v1/elasticsearch/spanstore/writer.go:132]: index-create and span-write seem like distinct operations to me.

File: internal/storage/elasticsearch/config/config.go [hunk 7]
```diff
@@ -235,9 +235,13 @@ func NewClient(c *Configuration, logger *zap.Logger, metricsFactory metrics.Fact
 		After(func(id int64, requests []elastic.BulkableRequest, response *elastic.BulkResponse, err error) {
 			start, ok := m.Load(id)
 			if !ok {
```
Comment (yurishkuro) [inline internal/storage/elasticsearch/config/config.go:237]: this bug indicates you don't have a unit test for it
```suggestion
			if ok {
```

Comment (AnmolxSingh) [reply internal/storage/elasticsearch/config/config.go:237]: you are right. Actually I was waiting for the metrics design to be reviewed and approved before writing the unit test as change in logic might affect them.

File: internal/storage/elasticsearch/config/config.go [hunk 8]
```diff
@@ -246,11 +250,27 @@ func NewClient(c *Configuration, logger *zap.Logger, metricsFactory metrics.Fact
...
+			sm.Inserts.Inc(int64(successCount))
+			sm.Errors.Inc(int64(failureCount))
+
+			if err != nil || failureCount > 0 {
+				sm.LatencyErr.Record(duration)
+			} else {
+				sm.LatencyOk.Record(duration)
+			}
+
+			sm.Emit(err, duration)
```
Comment (yurishkuro) [inline internal/storage/elasticsearch/config/config.go:272]: why is this new code repeating what seems to be already done below int the old code?

Comment (AnmolxSingh) [reply internal/storage/elasticsearch/config/config.go]: added this before remembering that Emit() already does the job.
fixed!

File: internal/storage/v1/elasticsearch/spanstore/writer.go (hunk 5 above)
Comment (yurishkuro) [reply internal/storage/v1/elasticsearch/spanstore/writer.go:141]: my suggestion still applies. Make s.writeSpan return an error too.

File: internal/storage/elasticsearch/config/config.go [hunk 9]
```diff
@@ -246,11 +249,19 @@ func NewClient(c *Configuration, logger *zap.Logger, metricsFactory metrics.Fact
 						if val.Error != nil {
 							logger.Error("Elasticsearch part of bulk request failed", zap.String("map-key", key),
 								zap.Reflect("response", val))
+						} else {
+							successCount++
```
Comment (yurishkuro) [inline internal/storage/elasticsearch/config/config.go:253]: can we not test this path?

File: internal/storage/v1/elasticsearch/spanstore/writer.go (hunk 5 above)
Comment (AnmolxSingh) [reply internal/storage/v1/elasticsearch/spanstore/writer.go:141]: then my proposal for this would be returning a nil from the `writeSpan()` func.
Would this approach work for us here?

File: internal/storage/elasticsearch/config/config.go (hunk 9 above)
Comment (AnmolxSingh) [reply internal/storage/elasticsearch/config/config.go:253]: I was writing tests for this and i think we would we needing  metrics.Factory for this so should i create a MockFactory or use a NullFactory

Comment (AnmolxSingh) [reply internal/storage/elasticsearch/config/config.go:253]: Do i need to execute the actual successcode++ line in order to test it?

File: internal/storage/v2/elasticsearch/tracestore/writer.go [hunk 10]
```diff
@@ -29,7 +29,9 @@ func (t *TraceWriter) WriteTraces(_ context.Context, td ptrace.Traces) error {
 	dbSpans := ToDBModel(td)
 	for i := 0; i < len(dbSpans); i++ {
 		span := &dbSpans[i]
-		t.spanWriter.WriteSpan(model.EpochMicrosecondsAsTime(span.StartTime), span)
+		if err := t.spanWriter.WriteSpan(model.EpochMicrosecondsAsTime(span.StartTime), span); err != nil {
+			return err
```
Comment (AnmolxSingh) [inline internal/storage/v2/elasticsearch/tracestore/writer.go:33]: I just wanted to know do we just return error or log it

File: internal/storage/v2/elasticsearch/tracestore/writer_test.go [hunk 11]
```diff
@@ -48,7 +51,12 @@ func TestTraceWriter_CreateTemplates(t *testing.T) {
 }
 
 func Test_NewTraceWriter(t *testing.T) {
-	params := spanstore.SpanWriterParams{}
+
+	params := spanstore.SpanWriterParams{
+		Client:         func() elasticsearch.Client { return nil },
```
Comment (AnmolxSingh) [inline internal/storage/v2/elasticsearch/tracestore/writer_test.go:56]: I have currently returned nil for this. I am open to modify this as per the needs of the code.

File: internal/storage/elasticsearch/config/config.go (hunk 9 above)
Comment (AnmolxSingh) [reply internal/storage/elasticsearch/config/config.go:253]: Do I need to create a new server for this or can i just replicate this logic in test.

**Comment by AnmolxSingh** [comment]
@yurishkuro Please review this pr i am actively working on it.
also please tell if the metrics code logic seems correct then i might move with writing tests

File: internal/storage/v2/elasticsearch/tracestore/writer.go (hunk 10 above)
Comment (yurishkuro) [reply internal/storage/v2/elasticsearch/tracestore/writer.go:33]: return it

File: internal/storage/v1/elasticsearch/spanstore/writer.go [hunk 12]
```diff
@@ -25,13 +26,18 @@ const (
 	indexCacheTTLDefault   = 48 * time.Hour
 )
 
+type spanWriterMetrics struct {
```
Comment (yurishkuro) [inline internal/storage/v1/elasticsearch/spanstore/writer.go:29]: what is the purpose of this struct? Why not just capture `*spanstoremetrics.WriteMetrics` directly?

File: internal/storage/elasticsearch/config/config.go [hunk 13]
```diff
@@ -234,10 +234,13 @@ func NewClient(c *Configuration, logger *zap.Logger, metricsFactory metrics.Fact
...
-			if !ok {
-				return
+			if ok {
+				m.Delete(id)
+			} else {
+				start = time.Now()
 			}
-			m.Delete(id)
+
+			var successCount, failureCount int
```
Comment (yurishkuro) [inline internal/storage/elasticsearch/config/config.go:243]: what is the difference between `failureCount` and `failed` in L267

File: internal/storage/v1/elasticsearch/spanstore/writer.go (hunk 12 above)
Comment (AnmolxSingh) [reply internal/storage/v1/elasticsearch/spanstore/writer.go:29]: actually it was in previous code I kept it same.
But it makes sense to directly take it in `SpanWriterParams`.

File: internal/storage/elasticsearch/config/config.go (hunk 13 above)
Comment (AnmolxSingh) [reply internal/storage/elasticsearch/config/config.go:243]: Ahh! I actually missed incrementing `failureCount`.
`failureCount` is used for emitting the error metrics and `failed` is used for logging failed requests.

Comment (yurishkuro) [reply internal/storage/elasticsearch/config/config.go:243]: it doesn't answer my question.

Comment (AnmolxSingh) [reply internal/storage/elasticsearch/config/config.go:243]: Just to clarify - are you asking whether they overlap in counting the same failed writes?

Comment (yurishkuro) [reply internal/storage/elasticsearch/config/config.go:243]: yes, and why we need to have similar logic twice

File: internal/storage/elasticsearch/config/config.go [hunk 14]
```diff
@@ -234,23 +234,31 @@ func NewClient(c *Configuration, logger *zap.Logger, metricsFactory metrics.Fact
...
-			m.Delete(id)
 
 			// log individual errors, note that err might be false and these errors still present
-			if response != nil && response.Errors {
-				for _, it := range response.Items {
-					for key, val := range it {
-						if val.Error != nil {
-							logger.Error("Elasticsearch part of bulk request failed", zap.String("map-key", key),
-								zap.Reflect("response", val))
+			if response != nil {
```
Comment (yurishkuro) [inline internal/storage/elasticsearch/config/config.go:244]: this code appears nearly identical to what it was before, why does it need to change?

File: internal/storage/v2/elasticsearch/tracestore/writer_test.go [hunk 15]
```diff
@@ -48,7 +51,11 @@ func TestTraceWriter_CreateTemplates(t *testing.T) {
 }
 
 func Test_NewTraceWriter(t *testing.T) {
-	params := spanstore.SpanWriterParams{}
+	params := spanstore.SpanWriterParams{
+		Client:         func() elasticsearch.Client { return nil },
```
Comment (yurishkuro) [inline internal/storage/v2/elasticsearch/tracestore/writer_test.go:55]:
```suggestion
```

File: internal/storage/v2/elasticsearch/tracestore/writer_test.go (hunk 11 above)
Comment (yurishkuro) [reply internal/storage/v2/elasticsearch/tracestore/writer_test.go:55]: it makes no different if it's initialized or not

File: internal/storage/v1/elasticsearch/spanstore/writer.go [hunk 16]
```diff
@@ -119,13 +122,15 @@ func getSpanAndServiceIndexFn(p SpanWriterParams, writeAlias string) spanAndServ
 }
 
 // WriteSpan writes a span and its corresponding service:operation in ElasticSearch
-func (s *SpanWriter) WriteSpan(spanStartTime time.Time, span *dbmodel.Span) {
+func (s *SpanWriter) WriteSpan(spanStartTime time.Time, span *dbmodel.Span) error {
```
Comment (yurishkuro) [inline internal/storage/v1/elasticsearch/spanstore/writer.go:125]: Why is the change to return error required for this PR? I could see it would make sense if you were using it somewhere, but I don't see any code that does it for the metrics purposes.

File: internal/storage/v1/elasticsearch/spanstore/writer.go [hunk 17]
```diff
@@ -89,8 +91,9 @@ func NewSpanWriter(p SpanWriterParams) *SpanWriter {
 
 	serviceOperationStorage := NewServiceOperationStorage(p.Client, p.Logger, serviceCacheTTL)
 	return &SpanWriter{
-		client:            p.Client,
-		logger:            p.Logger,
+		client:           p.Client,
+		logger:           p.Logger,
+		writerMetrics:    spanstoremetrics.NewWriter(p.MetricsFactory, "span_write"),
```
Comment (yurishkuro) [inline internal/storage/v1/elasticsearch/spanstore/writer.go:96]: what is "span_write" string for? Does it match how metrics were historically emitted? What do the resulting metric look like?

**Review by yurishkuro — COMMENTED** [review]
I don't see any unit tests validating that the expected metrics are being emitted

File: internal/storage/v1/elasticsearch/spanstore/writer.go (hunk 16 above)
Comment (AnmolxSingh) [reply internal/storage/v1/elasticsearch/spanstore/writer.go:137]: Thanks for raising this.

Initially, the change to make WriteSpan() return error was introduced following your earlier suggestion https://github.com/jaegertracing/jaeger/issues/6891#issuecomment-2784687558,
when we were discussing error tracking during span writes for metrics.

However, now that metrics emission has been moved fully into the batch .After() callback

I can revert the error return from WriteSpan() to keep the API cleaner and minimal.

Comment (yurishkuro) [reply internal/storage/v1/elasticsearch/spanstore/writer.go:137]: Yes I remember the discussion, but if you are not making use of returned errors (and in practice they are always nil) there's no reason to introduce this change.

**Comment by AnmolxSingh** [comment]
> I don't see any unit tests validating that the expected metrics are being emitted

While writing the unit tests for emitted metrices I was thinking of simulating the `.After()` callback.
Is this approach correct?

File: internal/storage/v1/elasticsearch/spanstore/writer.go (hunk 17 above)
Comment (AnmolxSingh) [reply internal/storage/v1/elasticsearch/spanstore/writer.go]: I mistakenly used `span-write` but historically metrics used names like `Spans` `ServiceOperation` `IndexCreate`.
I think it would be best if we use `Spans`

**Comment by yurishkuro** [comment]
> I was thinking of simulating the

you can move the code of the callback into a top level function which you can call directly from the test

File: internal/storage/v1/elasticsearch/spanstore/writer.go (hunk 17 above)
Comment (yurishkuro) [reply internal/storage/v1/elasticsearch/spanstore/writer.go]: `"spans"`

File: internal/storage/v1/elasticsearch/spanstore/writer.go [hunk 18]
```diff
@@ -167,8 +171,9 @@ func (s *SpanWriter) writeService(indexName string, jsonSpan *dbmodel.Span) {
 	s.serviceWriter(indexName, jsonSpan)
 }
 
-func (s *SpanWriter) writeSpan(indexName string, jsonSpan *dbmodel.Span) {
+func (s *SpanWriter) writeSpan(indexName string, jsonSpan *dbmodel.Span) error {
```
Comment (AnmolxSingh) [inline internal/storage/v1/elasticsearch/spanstore/writer.go:174]: Should `error` return be also removed from here?

File: internal/storage/elasticsearch/config/config_test.go [hunk 19]
```diff
@@ -55,6 +58,54 @@ var mockEsServerResponseWithVersion8 = []byte(`
 }
 `)
 
+// mock collector implementation for testing
+type testCollector struct {
```
Comment (yurishkuro) [inline internal/storage/elasticsearch/config/config_test.go:62]: we don't need extra test utils, already have them in internal/metricstest

File: internal/storage/v1/elasticsearch/spanstore/writer.go (hunk 18 above)
Comment (yurishkuro) [reply internal/storage/v1/elasticsearch/spanstore/writer.go:174]: Isn't it part of the overall Write API?

File: internal/storage/elasticsearch/config/config.go [hunk 20]
```diff
@@ -315,6 +283,46 @@ func NewClient(c *Configuration, logger *zap.Logger, metricsFactory metrics.Fact
...
+						zap.String("map-key", key), zap.Reflect("response", val))
+				}
+			}
+		}
+	}
+
+	sm.Emit(err, time.Since(start.(time.Time)))
+	if err != nil {
+		var failed int
+		if response == nil {
```
Comment (AnmolxSingh) [inline internal/storage/elasticsearch/config/config.go:309]: can this if else ladder be changed to 
``` 
if response != nil {
        failed = len (response.Failed())
}
```

Comment (yurishkuro) [reply internal/storage/elasticsearch/config/config.go:309]: I think `if err != nil {` should only be around `logger.Error(...)`. The other calculations should happen regardless, to increment the metrics.

Comment (AnmolxSingh) [reply internal/storage/elasticsearch/config/config.go:309]: would something of this type work here
```
var failed int
if response != nil {
	failed = len(response.Failed())
}

total := len(requests)
sm.Inserts.Inc(int64(total - failed))
sm.Errors.Inc(int64(failed))

if err != nil {
	logger.Error("Elasticsearch could not process bulk request",
		zap.Int("request_count", total),
		zap.Int("failed_count", failed),
		zap.Error(err),
		zap.Any("response", response))
}
```

Comment (yurishkuro) [reply internal/storage/elasticsearch/config/config.go:309]: yes looks reasonable

File: internal/storage/elasticsearch/config/config.go [hunk 21]
```diff
@@ -315,6 +283,45 @@ func NewClient(c *Configuration, logger *zap.Logger, metricsFactory metrics.Fact
 	return eswrapper.WrapESClient(rawClient, bulkProc, c.Version, rawClientV8), nil
 }
 
+func handleBulkAfterCallback(id int64, requests []elastic.BulkableRequest, response *elastic.BulkResponse, err error, startTimes *sync.Map, sm *spanstoremetrics.WriteMetrics, logger *zap.Logger) {
```
Comment (yurishkuro) [inline internal/storage/elasticsearch/config/config.go:286]:
```suggestion
func handleBulkAfterCallback(
	id int64,
	requests []elastic.BulkableRequest,
	response *elastic.BulkResponse,
	err error,
	startTimes *sync.Map,
	sm *spanstoremetrics.WriteMetrics,
	logger *zap.Logger,
) {
```

Comment (yurishkuro) [reply internal/storage/elasticsearch/config/config.go:286]: too many parameters. Make it a method and only pass what's needed. The actual hook only has 4 params.

File: internal/storage/v1/elasticsearch/spanstore/writer.go [hunk 22]
```diff
@@ -132,6 +135,7 @@ func getSpanAndServiceIndexFn(p SpanWriterParams, writeAlias string) spanAndServ
 
 // WriteSpan writes a span and its corresponding service:operation in ElasticSearch
 func (s *SpanWriter) WriteSpan(spanStartTime time.Time, span *dbmodel.Span) {
+	s.writerMetrics.Attempts.Inc(1)
```
Comment (yurishkuro) [inline internal/storage/v1/elasticsearch/spanstore/writer.go:138]: this should be added to core writer, not v1 writer. We need the same metrics in v2.

Comment (AnmolxSingh) [reply internal/storage/v1/elasticsearch/spanstore/writer.go:138]: If I am not wrong do you mean to add it to this one
https://github.com/jaegertracing/jaeger/blob/70e6a3038f0ca2580852713b30e492de8317bb9e/internal/storage/v1/elasticsearch/spanstore/writerv1.go#L30

File: internal/storage/elasticsearch/config/config.go (hunk 21 above)
Comment (AnmolxSingh) [reply internal/storage/elasticsearch/config/config.go:286]: can this be done passing 5 arguments
```
func handleBulkAfterCallback(
	id int64,
	requests []elastic.BulkableRequest,
	response *elastic.BulkResponse,
	err error,
	logger *zap.Logger,
) {
```

Comment (yurishkuro) [reply internal/storage/elasticsearch/config/config.go:286]:
```
type bulkCallback struct {
	startTimes *sync.Map
	sm *spanstoremetrics.WriteMetrics
	logger *zap.Logger
}

func (bcb *bulkCallback) invoke(.. same args as After()) {
  // logic
}

// inside NewClient()
  bulkCB := &bulkCallback{ ... initialize }
  ...
  After(bulkCB.invoke)
```

File: internal/storage/v1/elasticsearch/spanstore/writer.go (hunk 22 above)
Comment (AnmolxSingh) [reply internal/storage/v1/elasticsearch/spanstore/writer.go:138]: Is this not the core writer?

File: internal/storage/elasticsearch/config/config.go [hunk 23]
```diff
@@ -228,47 +234,19 @@ func NewClient(c *Configuration, logger *zap.Logger, metricsFactory metrics.Fact
 	}
 
 	sm := spanstoremetrics.NewWriter(metricsFactory, "bulk_index")
-	m := sync.Map{}
+	startTimes := sync.Map{}
+
+	bcb := &bulkCallback{
+		startTimes: &startTimes,
```
Comment (yurishkuro) [inline internal/storage/elasticsearch/config/config.go:240]: don't make it a pointer and you won't need to initialize it.

File: internal/storage/elasticsearch/config/config.go [hunk 24]
```diff
@@ -228,47 +234,19 @@ func NewClient(c *Configuration, logger *zap.Logger, metricsFactory metrics.Fact
...
+		sm:         sm,
```
Comment (yurishkuro) [inline internal/storage/elasticsearch/config/config.go:241]:
```suggestion
		sm:         spanstoremetrics.NewWriter(metricsFactory, "bulk_index"),
```

File: internal/storage/elasticsearch/config/config.go [hunk 25]
```diff
@@ -69,6 +69,12 @@ type Indices struct {
 	Sampling     IndexOptions `mapstructure:"sampling"`
 }
 
+type bulkCallback struct {
+	startTimes *sync.Map
```
Comment (yurishkuro) [inline internal/storage/elasticsearch/config/config.go:73]:
```suggestion
	startTimes sync.Map
```

File: internal/storage/elasticsearch/config/config.go [hunk 26]
```diff
@@ -315,6 +289,46 @@ func NewClient(c *Configuration, logger *zap.Logger, metricsFactory metrics.Fact
...
+
+	bcb.sm.Emit(err, time.Since(start.(time.Time)))
+
+	var failed int
+	if response != nil {
+		failed = len(response.Failed())
+	}
+
+	total := len(requests)
+	bcb.sm.Inserts.Inc(int64(total - failed))
```
Comment (yurishkuro) [inline internal/storage/elasticsearch/config/config.go:320]:
```suggestion
	bcb.sm.Attempts.Inc(int64(total))
	bcb.sm.Inserts.Inc(int64(total - failed))
```
please add a test

File: internal/storage/elasticsearch/config/config.go [hunk 27]
```diff
@@ -315,6 +289,46 @@ func NewClient(c *Configuration, logger *zap.Logger, metricsFactory metrics.Fact
...
+			for key, val := range it {
+				if val.Error != nil {
+					bcb.logger.Error("Elasticsearch part of bulk request failed",
+						zap.String("map-key", key), zap.Reflect("response", val))
+				}
+			}
+		}
+	}
+
+	bcb.sm.Emit(err, time.Since(start.(time.Time)))
```
Comment (yurishkuro) [inline internal/storage/elasticsearch/config/config.go:312]: Emit function is designed for recording a single operation. it increments attempts / inserts / errors. I don't think it works in this case.

Comment (AnmolxSingh) [reply internal/storage/elasticsearch/config/config.go:312]: I was going to ask this actually it was the reason errors were calculated twice.

Comment (AnmolxSingh) [reply internal/storage/elasticsearch/config/config.go:312]: Giving wrong calculation.

File: internal/storage/elasticsearch/config/config.go [hunk 28]
```diff
@@ -315,6 +289,46 @@ func NewClient(c *Configuration, logger *zap.Logger, metricsFactory metrics.Fact
 	return eswrapper.WrapESClient(rawClient, bulkProc, c.Version, rawClientV8), nil
 }
 
+func (bcb *bulkCallback) invoke(id int64, requests []elastic.BulkableRequest, response *elastic.BulkResponse, err error) {
+	start, ok := bcb.startTimes.Load(id)
```
[the remark this answers is not in the document]
Comment (yurishkuro) [reply internal/storage/elasticsearch/config/config.go:293]: you can use it to record latency numbers directly, similar to how Emit function does it

**Review by yurishkuro — APPROVED** [review]
