### PR TITLE
Fix elasticsearch create index race condition error

### LINKED ISSUE #589: [es] Span write fails if index already exists due to race condition
ES version is 5.1.1
{
    "level": "error", 
    "ts": 1513045072.7463179, 
    "caller": "app/span_processor.go:103", 
    "msg": "Failed to save span", 
    "error": "Failed to create index: elastic: Error 400 (Bad Request): index [jaeger-service-2017-12-12/CV-EQal-Q1KQ3vEyxG1W7g] already exists [type=index_already_exists_exception]", 
    "errorVerbose": "elastic: Error 400 (Bad Request): index [jaeger-service-2017-12-12/CV-EQal-Q1KQ3vEyxG1W7g] already exists [type=index_already_exists_exception]
Failed to create index
github.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).logError
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:191
github.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).createIndex
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:148
github.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).WriteSpan
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:120
github.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).saveSpan
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:102
github.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).(github.com/jaegertracing/jaeger/cmd/collector/app.saveSpan)-fm
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:89
github.com/jaegertracing/jaeger/cmd/collector/app.ChainedProcessSpan.func1
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/model_consumer.go:32
github.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).processItemFromQueue
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:126
github.com/jaegertracing/jaeger/cmd/collector/app.NewSpanProcessor.func1
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:57
github.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumers.func1
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/queue/bounded_queue.go:65
runtime.goexit
	/home/travis/.gimme/versions/go1.9.linux.amd64/src/runtime/asm_amd64.s:2337", 
    "stacktrace": "github.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).saveSpan
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:103
github.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).(github.com/jaegertracing/jaeger/cmd/collector/app.saveSpan)-fm
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:89
github.com/jaegertracing/jaeger/cmd/collector/app.ChainedProcessSpan.func1
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/model_consumer.go:32
github.com/jaegertracing/jaeger/cmd/collector/app.(*spanProcessor).processItemFromQueue
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:126
github.com/jaegertracing/jaeger/cmd/collector/app.NewSpanProcessor.func1
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/collector/app/span_processor.go:57
github.com/jaegertracing/jaeger/pkg/queue.(*BoundedQueue).StartConsumers.func1
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/queue/bounded_queue.go:65"
}

### PR DESCRIPTION
**Pull request by pavolloffay**
Fixes #589

### CODE REVIEW

File: plugin/storage/es/spanstore/writer.go [hunk 1]
```diff
@@ -140,12 +141,15 @@ func (s *SpanWriter) createIndex(indexName string, mapping string, jsonSpan *jMo
...
-			// the exists check above and try to create the same index all at once, this might fail and
-			// drop a couple spans (~1 per collector). Creating indices ahead of time alleviates this issue.
+			// the exists check above and try to create the same index all at once, this might fail
+			// we check the error type and return
 			_, err := s.client.CreateIndex(indexName).Body(s.fixMapping(mapping)).Do(s.ctx)
 			s.writerMetrics.indexCreate.Emit(err, time.Since(start))
 			if err != nil {
-				return s.logError(jsonSpan, err, "Failed to create index", s.logger)
+				eErr, ok := err.(*elastic.Error)
+				if !ok || eErr.Details.Type != "index_already_exists_exception" {
```
Comment (yurishkuro) [inline plugin/storage/es/spanstore/writer.go]: can Details be null?

Comment (pavolloffay) [reply plugin/storage/es/spanstore/writer.go]: null check added

File: plugin/storage/es/spanstore/writer.go [hunk 2]
```diff
@@ -140,12 +141,15 @@ func (s *SpanWriter) createIndex(indexName string, mapping string, jsonSpan *jMo
 		exists, _ := s.client.IndexExists(indexName).Do(s.ctx) // don't need to check the error because the exists variable will be false anyway if there is an error
 		if !exists {
 			// if there are multiple collectors writing to the same elasticsearch host, if the collectors pass
```
Comment (black-adder) [inline plugin/storage/es/spanstore/writer.go]: this whole sentence is kinda wonky now.
"if there are multiple collectors attempting to create the same index at once, we make sure the error is not index_already_exists_exception or else we return the error"

or something to that effect
