### PR TITLE
fix(badger): Add missing SamplingStoreFactory.CreateLock method

### LINKED ISSUE #4963: [Bug]: badger as sampling store not work
### What happened?

Error starting "storage factory of type badger does not support sampling store"

badger storage not implement SamplingStoreFactory interface -> no method CreateLock

### Steps to reproduce

docker run --rm --env SAMPLING_STORAGE_TYPE=badger --env SAMPLING_CONFIG_TYPE=adaptive jaegertracing/all-in-one:1.51.0

### Expected behavior

work with badger as sampling store

### Relevant log output

_No response_

### Screenshot

_No response_

### Additional context

_No response_

### Jaeger backend version

v1.51.0

### SDK

_No response_

### Pipeline

_No response_

### Stogage backend

badger

### Operating system

Linux

### Deployment model

Docker

### Deployment configs

_No response_

### PR DESCRIPTION
**Pull request by slayer321**
## Which problem is this PR solving?
- Resolves #4963

## Description of the changes
-   Implement missing `CreateLock` method on `SamplingStoreFactory` interface for badger

## How was this change tested?
-  run the Integration and make test command

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [x] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Comment by yurishkuro** [comment]
@slayer321 this issue should've been caught at compile time, and via integration test, but it looks like this PR is not changing any of those. The storage factory must implement this interface https://github.com/jaegertracing/jaeger/blob/47f39a8f4f4279c7532aef75a85af4d31d253933/storage/factory.go#L54

I think the issue with integration tests is that the StorageIntegration struct is defined with direct access to SpanWriter etc. that are pre-initialized by the concrete implementation. Instead it would be better if implementations would only initialize the respective factories and let the test retrieve writer, etc. (we could do it in another PR).

File: plugin/storage/badger/factory.go [hunk 1]
```diff
@@ -177,6 +178,11 @@ func (f *Factory) CreateSamplingStore(maxBuckets int) (samplingstore.Store, erro
 	return badgerSampling.NewSamplingStore(f.store), nil
 }
 
+// CreateLock implements storage.SamplingStoreFactory
+func (f *Factory) CreateLock() (distributedlock.Lock, error) {
```
Comment (yurishkuro) [inline plugin/storage/badger/factory.go:182]: please add a test

**Comment by yurishkuro** [comment]
Cf: https://github.com/jaegertracing/jaeger/pull/4967

File: plugin/storage/badger/factory.go [hunk 2]
```diff
@@ -186,6 +187,11 @@ func (f *Factory) CreateSamplingStore(maxBuckets int) (samplingstore.Store, erro
...
```
Comment (yurishkuro) [inline plugin/storage/badger/factory.go:191]: please fix L58

**Review by yurishkuro — APPROVED** [review]
