### PR TITLE
Fix gRPC over cmux and add unit tests

### LINKED ISSUE #1754: Cannot connect to query-service via gRPC
Reported by @32leaves on Gitter.

## Requirement - what kind of business use case are you trying to solve?

Programmatically retrieve traces via gRPC endpoint on all-in-one.

## Problem - what in Jaeger blocks you from solving the requirement?

https://gist.github.com/32leaves/8d422784ad7cb105ff4b1a36e8726222

gRPC client cannot complete the handshake with the server.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Looks like a bug. We should have a working example and a unit test.

## Any open questions to address

At Uber we have an internal client library that works, but we're running gRPC server on a separate port from HTTP server, so the issue might be with the cmux.

### PR DESCRIPTION
**Pull request by yurishkuro**
Resolves #1754

Includes the main commit by @32leaves from #1756

### CODE REVIEW

File: cmd/query/app/server_test.go [hunk 1]
```diff
@@ -43,13 +47,40 @@ func TestServer(t *testing.T) {
...
+	dependencyReader := &depsmocks.Reader{}
+
+	querySvc := querysvc.NewQueryService(spanReader, dependencyReader, querysvc.QueryServiceOptions{})
+
 	tracer := opentracing.NoopTracer{}
 
-	server := NewServer(flagsSvc, querySvc, &QueryOptions{Port: ports.QueryAdminHTTP,
-		BearerTokenPropagation: true}, tracer)
+	server := NewServer(flagsSvc, querySvc,
+		&QueryOptions{Port: ports.QueryAdminHTTP, BearerTokenPropagation: true},
```
Comment (annanay25) [inline cmd/query/app/server_test.go]: Changing the listening port here to -

```
		&QueryOptions{Port: ports.QueryHTTP, BearerTokenPropagation: true},
```

.. and using `cmuxServer.MatchWithWriters(...)` as suggested by @32leaves seems to work for me. 

We definitely needed an integration test with cmux though, thanks for pointing out!
