### PR TITLE
Fix "index out of range" when receiving a dual client/server Zipkin span

### LINKED ISSUE #3404: Request with "parent+children" spans to the zipkin collector service fails with error: index out of range
If we send parent and children spans in request, jaeger will be failed with error: "runtime error: index out of range"

**Steps to reproduce:**
1.  Run jaeger.
2.  Send POST request to the "<jaeger_address>: <zipkin_collector_port>/api/v1/spans" with next json in the body:
```json
[
    {
        "traceId": "4ed11df465275600",
        "id": "4ed11df465275600",
        "name": "get /",
        "timestamp": 1633073248674949,
        "duration": 14861,
        "localEndpoint": {
            "serviceName": "first_service",
            "ipv4": "10.0.2.15"
        },
        "annotations": [
            {
                "timestamp": 1633073248674949,
                "value": "sr"
            },
            {
                "timestamp": 163307324868981,
                "value": "ss"
            }
        ]
    },
    {
        "traceId": "4ed11df465275600",
        "parentId": "4ed11df465275600",
        "id": "c943743e25dc2cdf",
        "name": "get /api",
        "timestamp": 1633073248678309,
        "duration": 3360,
        "localEndpoint": {
            "serviceName": "first_service",
            "ipv4": "10.0.2.15"
        },
        "annotations": [
            {
                "timestamp": 1633073248678309,
                "value": "cs"
            },
            {
                "timestamp": 1633073248681669,
                "value": "sr"
            },
            {
                "timestamp": 1633073248685029,
                "value": "cr"
            },
            {
                "timestamp": 1633073248688388,
                "value": "ss"
            }
        ]
    }
]
```
**Expected result:** 202 Accepted
**Actual result:** 500 Internal Server Error

 - Jaeger version: 1.28.0, master
 - Deployment: Docker, Kubernetes

**Additional context**
During the debug, we found that the problem occurs in the [SubmitZipkinBatch](https://github.com/jaegertracing/jaeger/blob/master/cmd/collector/app/handler/thrift_span_handler.go#L109-L132) function.

After "Sanitize" there are "mSpans" array with 3 items and "bools" with labels of processed spans :

image

image

Where span with  "parentId" field was converted in two items.

And then function creates "responses" array with length=2(from original "spans"), but iterates through "bools" with length =3. Eventually there is rises error "index out of range [2] with length 2".

### PR DESCRIPTION
**Pull request by yurishkuro**
## Which problem is this PR solving?
- Resolves #3404 

## Short description of the changes
- Handle case where one input zipkin span is transformed into two Jaeger spans, but still return response with the same length as input
- Add a test for dial client/server span provided in #3404 
- Side effect: refactor `cmd/collector/app/zipkin` to avoid circular dependencies

### CODE REVIEW

**Comment by yurishkuro** [comment]
@albertteoh or @pavolloffay can I get a review plz?

File: cmd/collector/app/handler/thrift_span_handler.go [hunk 1]
```diff
@@ -121,13 +125,23 @@ func (h *zipkinSpanHandler) SubmitZipkinBatch(spans []*zipkincore.Span, options
 		return nil, err
 	}
 	responses := make([]*zipkincore.Response, len(spans))
-	for i, ok := range bools {
+	// at this point we may have len(spans) < len(bools) if conversion results in more spans
```
Comment (albertteoh) [inline cmd/collector/app/handler/thrift_span_handler.go:128]: Perhaps the comment should refer to `total converted` instead of `bool` (same below)?

File: cmd/collector/app/zipkin/http_handler_test.go [hunk 2]
```diff
@@ -116,66 +116,86 @@ func TestThriftFormat(t *testing.T) {
...
 		{
-			payload:    createSpan("bar", "", "1", "1", 156, 15145, false, annoJSON, binAnnoJSON),
+			name:       "empty span id",
+			payload:    zm.CreateSpan("bar", "", "1", "1", 156, 15145, false, annoJSON, binAnnoJSON),
 			expected:   "Unable to process request body: strconv.ParseUint: parsing &#34;&#34;: invalid syntax\n",
 			statusCode: http.StatusBadRequest,
 		},
 		{
-			payload:    createSpan("bar", "ZTA", "1", "1", 156, 15145, false, "", ""),
+			name:       "ivalid span id",
```
Comment (albertteoh) [inline cmd/collector/app/zipkin/http_handler_test.go:175]:
```suggestion
			name:       "invalid span id",
```

File: cmd/collector/app/zipkin/http_handler_test.go [hunk 3]
```diff
@@ -116,66 +116,86 @@ func TestThriftFormat(t *testing.T) {
...
+			payload:    zm.CreateSpan("bar", "ZTA", "1", "1", 156, 15145, false, "", ""),
 			expected:   "Unable to process request body: strconv.ParseUint: parsing &#34;ZTA&#34;: invalid syntax\n",
 			statusCode: http.StatusBadRequest,
 		},
 		{
-			payload:    createSpan("bar", "1", "", "1", 156, 15145, false, "", createAnno("cs", 1, endpErrJSON)),
+			name:       "ivalid ipv4 address",
```
Comment (albertteoh) [inline cmd/collector/app/zipkin/http_handler_test.go:181]:
```suggestion
			name:       "invalid ipv4 address",
```

File: cmd/collector/app/zipkin/http_handler_test.go [hunk 4]
```diff
@@ -398,3 +418,9 @@ func postBytes(urlStr string, bytesBody []byte, header *http.Header) (int, strin
 	}
 	return res.StatusCode, string(body), nil
 }
+
+func randBytesOfLen(n int) []byte {
+	b := make([]byte, n)
+	rand.Read(b)
```
Comment (albertteoh) [inline cmd/collector/app/zipkin/http_handler_test.go:424]: I think we should add a `require.NoError` here.

File: cmd/collector/app/zipkin/zipkindeser/zipkindesermocks/mocks.go [hunk 5]
```diff
@@ -0,0 +1,46 @@
...
+	return fmt.Sprintf(annoFmt, val, ts, endpoint)
+}
+
+// CreateBinAnno builds binary annotation JSON.
+func CreateBinAnno(key string, val string, endpoint string) string {
+	return fmt.Sprintf(binaAnnoFmt, key, val, endpoint)
+}
+
+// CreateSpan builds span JSON.
+func CreateSpan(name string, id string, parentID string, traceID string, ts int64, duration int64, debug bool,
```
Comment (albertteoh) [inline cmd/collector/app/zipkin/zipkindeser/zipkindesermocks/mocks.go:42]: nit: for brevity, you could consider omitting types for consecutive type names. e.g. if you'd like to maintain the same ordering, this could be: `name, id, parentID, traceID string, ts, duration int64, debug bool, anno, binAnno string`

File: cmd/collector/app/zipkin/zipkindeser/zipkindesermocks/mocks_test.go [hunk 6]
```diff
@@ -0,0 +1,25 @@
...
+// See the License for the specific language governing permissions and
+// limitations under the License.
+
+package zipkindesermocks
+
+import "testing"
+
+// Fake test to provide test coverage.
+func TestMocks(m *testing.T) {
+	CreateEndpoint("serviceName", "ipv4", "ipv6", 1)
```
Comment (albertteoh) [inline cmd/collector/app/zipkin/zipkindeser/zipkindesermocks/mocks_test.go:21]: Should these tests be asserting on the expected mocked output string?

**Review by albertteoh — COMMENTED** [review]
Overall looks good to me, just some nits.

File: cmd/collector/app/handler/thrift_span_handler.go (hunk 1 above)
Comment (yurishkuro) [reply cmd/collector/app/handler/thrift_span_handler.go:128]: Can you elaborate / suggest?

File: cmd/collector/app/zipkin/zipkindeser/zipkindesermocks/mocks_test.go (hunk 6 above)
Comment (yurishkuro) [reply cmd/collector/app/zipkin/zipkindeser/zipkindesermocks/mocks_test.go:21]: ok will add

File: cmd/collector/app/zipkin/zipkindeser/zipkindesermocks/mocks.go (hunk 5 above)
Comment (yurishkuro) [reply cmd/collector/app/zipkin/zipkindeser/zipkindesermocks/mocks.go:42]: +1

File: cmd/collector/app/zipkin/http_handler_test.go (hunk 4 above)
Comment (yurishkuro) [reply cmd/collector/app/zipkin/http_handler_test.go:424]: +1

File: cmd/collector/app/zipkin/http_handler_test.go (hunk 3 above)
Comment (yurishkuro) [reply cmd/collector/app/zipkin/http_handler_test.go:181]: +1

File: cmd/collector/app/zipkin/http_handler_test.go (hunk 2 above)
Comment (yurishkuro) [reply cmd/collector/app/zipkin/http_handler_test.go:175]: +1

File: cmd/collector/app/handler/thrift_span_handler.go (hunk 1 above)
Comment (albertteoh) [reply cmd/collector/app/handler/thrift_span_handler.go:128]: Sorry, please ignore this one, I later understood the context behind `bools`. It's fine as is.

**Review by albertteoh — APPROVED** [review]
LGTM

**Comment by yurishkuro** [comment]
thanks!
