### PR TITLE
Attempt to fix flaky TestGetRoundTripper* tests

### LINKED ISSUE #4732: Flaky test TestGetRoundTripperTLSConfig
https://github.com/jaegertracing/jaeger/blob/2ac6aac9ef9d897a4f189962ef01ed39781ca527/plugin/metrics/prometheus/metricsstore/reader_test.go#L543

```
=== RUN   TestGetRoundTripperTLSConfig/tls_tlsEnabled
    reader_test.go:542: 
        	Error Trace:	/home/runner/work/jaeger/jaeger/plugin/metrics/prometheus/metricsstore/reader_test.go:542
        	            				/opt/hostedtoolcache/go/1.21.0/x64/src/net/http/server.go:2136
        	            				/opt/hostedtoolcache/go/1.21.0/x64/src/net/http/server.go:2938
        	            				/opt/hostedtoolcache/go/1.21.0/x64/src/net/http/server.go:2009
        	            				/opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650
        	Error:      	Not equal: 
        	            	expected: "***"
        	            	actual  : ""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-***
        	            	+
        	Test:       	TestGetRoundTripperTLSConfig/tls_tlsEnabled
=== RUN   TestGetRoundTripperTLSConfig/tls_disabled
    reader_test.go:542: 
        	Error Trace:	/home/runner/work/jaeger/jaeger/plugin/metrics/prometheus/metricsstore/reader_test.go:542
        	            				/opt/hostedtoolcache/go/1.21.0/x64/src/net/http/server.go:2136
        	            				/opt/hostedtoolcache/go/1.21.0/x64/src/net/http/server.go:2938
        	            				/opt/hostedtoolcache/go/1.21.0/x64/src/net/http/server.go:2009
        	            				/opt/hostedtoolcache/go/1.21.0/x64/src/runtime/asm_amd64.s:1650
        	Error:      	Not equal: 
        	            	expected: "***"
        	            	actual  : ""
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1 +1 @@
        	            	-***
        	            	+
        	Test:       	TestGetRoundTripperTLSConfig/tls_disabled
--- FAIL: TestGetRoundTripperTLSConfig (0.11s)
    --- FAIL: TestGetRoundTripperTLSConfig/tls_tlsEnabled (0.11s)
    --- FAIL: TestGetRoundTripperTLSConfig/tls_disabled (0.00s)
```

### PR DESCRIPTION
**Pull request by albertteoh**
## Which problem is this PR solving?
- Resolves #4732

## Description of the changes
- Introduces an atomic boolean outside of the HTTP test handler and only set to `true` if the expected request is received.
- This should prevent cases where unrelated processes are hitting the same test URL.

## How was this change tested?
- Ran `make test` to pass.
- Ran `go test -tags=memory_storage_integration -count 10 ./...` and confirmed `metricsstore` tests are passing.
- Note that a number of unrelated tests were failing with the `-count 10` flag set, **not as a result of the changes from this PR**, namely:
```
--- FAIL: TestFactory (0.00s)
    --- FAIL: TestFactory/#00 (0.00s)
panic: Reuse of exported var name: test_1694287567920905000_counter_x
 [recovered]
	panic: Reuse of exported var name: test_1694287567920905000_counter_x
```
and
```
--- FAIL: TestPublishOpts (0.00s)
    builder_test.go:308:
        	Error Trace:	/Users/albertteoh/go/src/github.com/albertteoh/jaeger/cmd/agent/app/builder_test.go:308
        	Error:      	Received unexpected error:
        	            	cannot create processors: cannot create Thrift Processor: cannot create UDP Server: cannot create UDPServerTransport: listen udp :5775: bind: address already in use
        	Test:       	TestPublishOpts
```

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [x] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

File: plugin/metrics/prometheus/metricsstore/reader_test.go [hunk 1]
```diff
@@ -537,10 +538,14 @@ func TestGetRoundTripperTLSConfig(t *testing.T) {
 			}, logger)
 			require.NoError(t, err)
 
+			var authReceived atomic.Bool
```
Comment (yurishkuro) [inline plugin/metrics/prometheus/metricsstore/reader_test.go:541]:
```suggestion
			var authReceived atomic.Pointer[string]
```

File: plugin/metrics/prometheus/metricsstore/reader_test.go [hunk 2]
```diff
@@ -537,10 +538,14 @@ func TestGetRoundTripperTLSConfig(t *testing.T) {
...
 			server := httptest.NewServer(
 				http.HandlerFunc(
 					func(w http.ResponseWriter, r *http.Request) {
-						assert.Equal(t, "Bearer foo", r.Header.Get("Authorization"))
+						t.Logf("Request to fake Prometheus server %+v", r)
+						if r.Header.Get("Authorization") == "Bearer foo" {
+							authReceived.Store(true)
+						}
```
Comment (yurishkuro) [inline plugin/metrics/prometheus/metricsstore/reader_test.go:548]:
```suggestion
						h := r.Header.Get("Authorization")
						authReceived.Store(&h)
```

File: plugin/metrics/prometheus/metricsstore/reader_test.go [hunk 3]
```diff
@@ -556,7 +561,9 @@ func TestGetRoundTripperTLSConfig(t *testing.T) {
 
 			resp, err := rt.RoundTrip(req)
 			require.NoError(t, err)
+
 			assert.Equal(t, http.StatusOK, resp.StatusCode)
+			assert.True(t, authReceived.Load())
```
Comment (yurishkuro) [inline plugin/metrics/prometheus/metricsstore/reader_test.go:566]:
```suggestion
			assert.Equal(t, "Bearer foo", *authReceived.Load())
```

**Review by yurishkuro — COMMENTED** [review]
Using boolean in the assert is not the best output when the assert fails. Using the actual string produces much more intuitive output in case of test failure.

File: plugin/metrics/prometheus/metricsstore/reader_test.go [hunk 4]
```diff
@@ -685,14 +708,12 @@ func startMockPrometheusServer(t *testing.T, wantPromQlQuery string, wantWarning
...
 
-func sendResponse(t *testing.T, w http.ResponseWriter, responseFile string) error {
+func sendResponse(t *testing.T, w http.ResponseWriter, responseFile string) {
 	bytes, err := os.ReadFile(responseFile)
-	if err != nil {
-		return err
-	}
+	require.NoError(t, err)
 
 	_, err = fmt.Fprintln(w, string(bytes))
```
Comment (yurishkuro) [inline plugin/metrics/prometheus/metricsstore/reader_test.go:715]:
```suggestion
	_, err = w.Write(bytes)
```

**Comment by albertteoh** [comment]
> Using boolean in the assert is not the best output when the assert fails. Using the actual string produces much more intuitive output in case of test failure.

Good suggestion, addressed in: [31bdc02](https://github.com/jaegertracing/jaeger/pull/4738/commits/31bdc020f521e55317f6f061de3e53f3af454450)

**Review by yurishkuro — DISMISSED** [review]

**Review by yurishkuro — APPROVED** [review]
