### PR TITLE
Fix HotRod job pool termination (#1453)

### LINKED ISSUE #1453: HotRod: pool: Stop all the workers by closing the stop channel
## Requirement - what kind of business use case are you trying to solve?
Instead of sending a signal on the stop chan, closing the stop chan is the correct way to stop all the workers; Reading from a closed chan is always successful.

## Proposal - what do you suggest to solve the problem or improve the existing situation?
Close the `stop` channel instead of sending values to it.

### PR DESCRIPTION
**Pull request by mfrw**
## Which problem is this PR solving?
- Instead of sending a signal on the stop chan, closing the stop chan is the correct way to stop all the workers; Reading from a closed chan is always successful. (Resolves #1453)

## Short description of the changes
- Close the stop channel instead of sending values to it.

### CODE REVIEW

File: examples/hotrod/pkg/pool/pool.go [hunk 1]
```diff
@@ -49,5 +49,7 @@ func (p *Pool) Execute(job func()) {
 
 // Stop halts all the workers
 func (p *Pool) Stop() {
-	p.stop <- struct{}{}
+	if p.stop != nil {
```
Comment (yurishkuro) [inline examples/hotrod/pkg/pool/pool.go]: why is the nil check necessary?

Comment (mfrw) [reply examples/hotrod/pkg/pool/pool.go]: @yurishkuro sorry for the late reply,
IMHO, this is a bug. Assuming you have more than 1 worker, calling stop only stops 1 of the workers and not all, while as closing the chan stops all the workers. Please let me know if you still want me to rename the PR.

Comment (yurishkuro) [reply examples/hotrod/pkg/pool/pool.go]: good point
