### PR TITLE
[ingester/fix] Apply sanitizers to avoid panic on span.process=nil

### LINKED ISSUE #3578: Jaeger ingester panics on convertProcess function
**Describe the bug**
The Jaeger ingester is panicking when taking data from kafka and attempting to write it into elasticsearch.

I believe the following code is the reason for the panic. 

https://github.com/jaegertracing/jaeger/blob/4f55a70524b29ef87178b4deffbd5a99be5d017a/plugin/storage/es/spanstore/dbmodel/from_domain.go#L123

There seems to be no safeguards for a null process or null tags?

This is the following stack trace 

```
{"level":"info","ts":1646779105.5014815,"caller":"consumer/processor_factory.go:65","msg":"Creating new processors","partition":31}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xd94dc6]

goroutine 84516 [running]:
github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/dbmodel.FromDomain.convertProcess(...)
	github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/dbmodel/from_domain.go:123
github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/dbmodel.FromDomain.convertSpanEmbedProcess({0x0, 0xc0003c48a0, {0x1499618, 0xf23872}}, 0xc00c544690)
	github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/dbmodel/from_domain.go:64 +0x126
github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/dbmodel.FromDomain.FromDomainEmbedProcess(...)
	github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/dbmodel/from_domain.go:43
github.com/jaegertracing/jaeger/plugin/storage/es/spanstore.(*SpanWriter).WriteSpan(0xc0005f8cc0, {0x0, 0x0}, 0xc00c544690)
	github.com/jaegertracing/jaeger/plugin/storage/es/spanstore/writer.go:152 +0x7a
github.com/jaegertracing/jaeger/cmd/ingester/app/processor.KafkaSpanProcessor.Process({{0x14ad480, 0x1dee2a8}, {0x14ad340, 0xc0005f8cc0}, {0x0, 0x0}}, {0x14af760, 0xc0111950e0})
	github.com/jaegertracing/jaeger/cmd/ingester/app/processor/span_processor.go:67 +0xd3
github.com/jaegertracing/jaeger/cmd/ingester/app/processor/decorator.(*retryDecorator).Process(0xc00008f180, {0x14af760, 0xc0111950e0})
	github.com/jaegertracing/jaeger/cmd/ingester/app/processor/decorator/retry.go:110 +0x37
github.com/jaegertracing/jaeger/cmd/ingester/app/consumer.(*comittingProcessor).Process(0xc0085cfaa0, {0x14af760, 0xc0111950e0})
	github.com/jaegertracing/jaeger/cmd/ingester/app/consumer/committing_processor.go:44 +0x5e
github.com/jaegertracing/jaeger/cmd/ingester/app/processor.(*metricsDecorator).Process(0xc00f38fa00, {0x14af760, 0xc0111950e0})
	github.com/jaegertracing/jaeger/cmd/ingester/app/processor/metrics_decorator.go:44 +0x5b
github.com/jaegertracing/jaeger/cmd/ingester/app/processor.(*ParallelProcessor).Start.func1()
	github.com/jaegertracing/jaeger/cmd/ingester/app/processor/parallel_processor.go:57 +0x42
created by github.com/jaegertracing/jaeger/cmd/ingester/app/processor.(*ParallelProcessor).Start
	github.com/jaegertracing/jaeger/cmd/ingester/app/processor/parallel_processor.go:53 +0x10c
```

**To Reproduce**

We aren't sure how to reproduce this as the only component panicking is the ingester.

We also haven't seen what set of traces are causing this. 

The best way to attempt to reproduce this could be to send a trace to the collector without process tags. We just haven't tried that yet.

**Expected behavior**
We expect the Jaeger ingester to gracefully handle any "bad" data and give us the configuration to either panic or discard the data.

**Screenshots**
N/A

**Version (please complete the following information):**
 - OS: Amazon Linux 2 (5.4.176-91.338.amzn2.x86_64)
 - Jaeger version: 1.31.0 ( We were on 1.20.0 and didn't see this issue)
 - Elastic version: 7.16.2
 - Kafka version: quay.io/strimzi/kafka:0.25.0-kafka-2.8.0
 - K8s version: 1.19 ( We are also seeing this on 1.21)
 - Deployment: Kubernetes via Operator

**What troubleshooting steps did you try?**

We tried downgrading the ingesters back to 1.20.0 and saw the same issue. 

We recreated the Jaeger deployment and still saw the issue. 

The only temporary fix was clearing the kafka queue, which implies bad data is making it to the queue.

**Additional context**
We are going to add collector tags to everything which should force process tags if I am reading the doc correctly.

https://www.jaegertracing.io/docs/1.32/cli/#jaeger-collector-kafka

--collector.tags |  
-- | --
One or more tags to be added to the Process tags of all spans passing through this collector. Ex: key1=value1,key2=${envVar:defaultValue}

### PR DESCRIPTION
**Pull request by locmai**
## Which problem is this PR solving?
- Fix #3578

## Short description of the changes
- Using the process.GetTags() and process.GetServiceName() instead of directly reference to those fields to avoid panic due to nil pointer dereference.

### CODE REVIEW

File: plugin/storage/es/spanstore/dbmodel/from_domain_test.go [hunk 1]
```diff
@@ -108,6 +108,32 @@ func TestTagMap(t *testing.T) {
...
+	converter := NewFromDomain(false, nil, ":")
+	dbSpanWithNilTags := converter.FromDomainEmbedProcess(&spanWithNilProcessTags)
+	dbSpanWithNilProcess := converter.FromDomainEmbedProcess(&spanWithNilProcess)
+
+	assert.Equal(t, 3, len(dbSpanWithNilTags.Tags))
+	assert.Equal(t, 3, len(dbSpanWithNilProcess.Tags))
+	assert.Equal(t, 0, len(dbSpanWithNilTags.Process.Tags))
+	assert.Equal(t, 0, len(dbSpanWithNilProcess.Process.Tags))
+
+	tagsMap := map[string]interface{}(nil)
```
Comment (locmai) [inline plugin/storage/es/spanstore/dbmodel/from_domain_test.go:130]: not sure if this was expected but this is what I got from the `convertKeyValuesString` func if the Tags was nil.

File: plugin/storage/es/spanstore/dbmodel/from_domain.go [hunk 2]
```diff
@@ -120,9 +120,9 @@ func (fd FromDomain) convertLogs(logs []model.Log) []Log {
 }
 
 func (fd FromDomain) convertProcess(process *model.Process) Process {
-	tags, tagsMap := fd.convertKeyValuesString(process.Tags)
+	tags, tagsMap := fd.convertKeyValuesString(process.GetTags())
 	return Process{
-		ServiceName: process.ServiceName,
+		ServiceName: process.GetServiceName(),
```
Comment (yurishkuro) [inline plugin/storage/es/spanstore/dbmodel/from_domain.go:125]: So this is exactly the type of change that I did not want to make. It avoids a panic, but does it silently, creating invalid data in the process (service name is not allowed to be empty, it could break many other places, including the UI).

I've added a sanitizer in #3631. We can try invoking it early in the Kafka consumer path.

Comment (locmai) [reply plugin/storage/es/spanstore/dbmodel/from_domain.go:125]: Thanks for taking a look at this and making things clearer. Let me take a look at the sanitizer and try what you suggested.

It make sense that the service name must not be empty, so I might revert the change to process.GetServiceName() here. For the process.GetTags, I think it still nicely handles the `nil` cases those led to the panics.

Comment (yurishkuro) [reply plugin/storage/es/spanstore/dbmodel/from_domain.go:125]: > I think it still nicely handles the nil cases those led to the panics.

Yes, but again, it does that accidentally, it so happens that in this context the behavior is appropriate. But fundamentally you're trying to work around malformed data that should've never gotten to this point in the pipeline. *I don't mind this specific change*, but at least with the current code we knew that there is a data issue (even though panicing on it is not ideal reaction).

File: plugin/storage/es/spanstore/dbmodel/from_domain_test.go (hunk 1 above)
Comment (yurishkuro) [inline plugin/storage/es/spanstore/dbmodel/from_domain_test.go:130]:
```suggestion
	nilMap := map[string]interface{}(nil)
```

File: plugin/storage/es/spanstore/dbmodel/from_domain_test.go [hunk 3]
```diff
@@ -108,6 +108,32 @@ func TestTagMap(t *testing.T) {
...
+	}
+
+	spanWithNilProcessTags := model.Span{Tags: tags, Process: &model.Process{Tags: nil}}
+	spanWithNilProcess := model.Span{Tags: tags, Process: nil}
+
+	converter := NewFromDomain(false, nil, ":")
+	dbSpanWithNilTags := converter.FromDomainEmbedProcess(&spanWithNilProcessTags)
+	dbSpanWithNilProcess := converter.FromDomainEmbedProcess(&spanWithNilProcess)
+
+	assert.Equal(t, 3, len(dbSpanWithNilTags.Tags))
```
Comment (yurishkuro) [inline plugin/storage/es/spanstore/dbmodel/from_domain_test.go:125]:
```suggestion
	assert.Len(t, 3, dbSpanWithNilTags.Tags)
```

File: plugin/storage/es/spanstore/dbmodel/from_domain.go (hunk 2 above)
Comment (trangmaiq) [reply plugin/storage/es/spanstore/dbmodel/from_domain.go:125]: Hi @yurishkuro , thank you so much for your review. As you mentioned, I understand it's important to detect data issue in our system, so should we return error here and let caller know that we do not accept the nil process for example? 

I think panic should be considered if we do want application immediately crash. Otherwise, we can consider error.

Thank you for your explanation and effort.

Comment (yurishkuro) [reply plugin/storage/es/spanstore/dbmodel/from_domain.go:125]: If we apply the sanitizer earlier in the pipeline then this code does need to change as it will never have to deal with nil process.

File: plugin/storage/es/spanstore/dbmodel/from_domain_test.go [hunk 4]
```diff
@@ -108,6 +108,26 @@ func TestTagMap(t *testing.T) {
...
 }
 
+func TestNilProcess(t *testing.T) {
+	tags := []model.KeyValue{
+		model.String("foo", "foo"),
+		model.Bool("a", true),
+		model.Int64("b.b", 1),
+	}
+
+	spanWithNilTags := model.Span{Tags: tags, Process: &model.Process{Tags: nil}}
```
Comment (yurishkuro) [inline plugin/storage/es/spanstore/dbmodel/from_domain_test.go:118]: This test would pass without any code changes in the PR. It's the nil Process that's causing panic in production, not the nil tags (nil tags are still iterable).

**Review by yurishkuro — APPROVED** [review]
