### PR TITLE
Decouple from OTel Collector semconv package

### LINKED ISSUE #7315: Replace semconv from collector with otel/semconv
### Requirement

We want to upgrade to the latest OTEL https://github.com/jaegertracing/jaeger/pull/7287

### Problem

The build is failing not being able to find go.opentelemetry.io/collector/semconv

### Proposal

According to https://github.com/open-telemetry/opentelemetry-collector/pull/13012 that package has been decommissioned and we should be using go.opentelemetry.io/otel/semconv

```
$ rg go.opentelemetry.io/collector/semconv
go.mod
286:	go.opentelemetry.io/collector/semconv v0.128.1-0.20250610090210-188191247685

go.sum
856:go.opentelemetry.io/collector/semconv v0.128.1-0.20250610090210-188191247685 h1:XCN7qkZRNzRYfn6chsMZkbFZxoFcW6fZIsZs2aCzcbc=
857:go.opentelemetry.io/collector/semconv v0.128.1-0.20250610090210-188191247685/go.mod h1:OPXer4l43X23cnjLXIZnRj/qQOjSuq4TgBLI76P9hns=

internal/storage/v2/elasticsearch/tracestore/to_dbmodel.go
14:	conventions "go.opentelemetry.io/collector/semconv/v1.16.0"

internal/storage/v2/elasticsearch/tracestore/from_dbmodel.go
19:	conventions "go.opentelemetry.io/collector/semconv/v1.16.0"

internal/storage/v2/elasticsearch/tracestore/to_dbmodel_test.go
20:	conventions "go.opentelemetry.io/collector/semconv/v1.9.0"

internal/storage/v2/elasticsearch/tracestore/from_dbmodel_test.go
21:	conventions "go.opentelemetry.io/collector/semconv/v1.16.0"

internal/storage/v2/memory/memory_test.go
21:	conventions "go.opentelemetry.io/collector/semconv/v1.16.0"

internal/storage/v2/memory/memory.go
14:	conventions "go.opentelemetry.io/collector/semconv/v1.16.0"
```

In some parts of the code we already tried to use indirection via our own package. 
```
internal/telemetry/otelsemconv/semconv.go
7:	semconv "go.opentelemetry.io/otel/semconv/v1.34.0"
```
There should be no direct references to OTEL/collector semconv in the rest of the codebase

### PR DESCRIPTION
**Pull request by danish9039**
## Which problem is this PR solving?
- Resolves #7315

## Description of the changes

  This commit removes the dependency on ` go.opentelemetry.io/collector/semconv` and internalizes the required semantic convention constants.

  Key changes:
   - Package `internal/telemetry/otelsemconv`  host the semantic convention constants used throughout the project.
   
   - All usages of the external semconv package have been replaced with the internal package.
  
 

  This change reduces external dependencies, providing more stability and control over the semantic conventions used within Jaeger.

## How was this change tested?
- 

## Checklist
- [ ] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [ ] I have signed all commits
- [ ] I have added unit tests for the new functionality
- [ ] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `npm run lint` and `npm run test`

### CODE REVIEW

File: internal/storage/v2/elasticsearch/tracestore/from_dbmodel_test.go [hunk 1]
```diff
@@ -18,10 +18,10 @@ import (
 	"github.com/stretchr/testify/require"
 	"go.opentelemetry.io/collector/pdata/pcommon"
 	"go.opentelemetry.io/collector/pdata/ptrace"
-	conventions "go.opentelemetry.io/collector/semconv/v1.16.0"
 
 	"github.com/jaegertracing/jaeger-idl/model/v1"
 	"github.com/jaegertracing/jaeger/internal/storage/elasticsearch/dbmodel"
+	"github.com/jaegertracing/jaeger/internal/telemetry/otelsemconv"
```
Comment (yurishkuro) [inline internal/storage/v2/elasticsearch/tracestore/from_dbmodel_test.go]:
```suggestion
	conventions "github.com/jaegertracing/jaeger/internal/telemetry/otelsemconv"
```
Minimize changes

File: internal/telemetry/otelsemconv/semconv.go [hunk 2]
```diff
@@ -13,21 +13,43 @@ import (
...
 	TelemetrySDKVersionKey    = semconv.TelemetrySDKVersionKey
 	TelemetryDistroNameKey    = semconv.TelemetryDistroNameKey
 	TelemetryDistroVersionKey = semconv.TelemetryDistroVersionKey
 
-	ServiceNameKey            = semconv.ServiceNameKey
-	DBQueryTextKey            = semconv.DBQueryTextKey
-	DBSystemKey               = semconv.DBSystemNameKey
-	PeerServiceKey            = semconv.PeerServiceKey
+	// Service
+	ServiceNameKey = semconv.ServiceNameKey
```
Comment (yurishkuro) [inline internal/telemetry/otelsemconv/semconv.go]: Any reason not to convert these to strings here so that we don't have to do it all over the code??

File: internal/storage/v2/elasticsearch/tracestore/to_dbmodel.go [hunk 3]
```diff
@@ -79,14 +79,29 @@ func resourceToDbProcess(resource pcommon.Resource) dbmodel.Process {
...
+			scopeName = attr.AsString()
+		}
 		tags = append(tags, attributeToDbTag(key, attr))
 	}
+
+	switch {
+	case serviceName != "":
+		process.ServiceName = serviceName
+	case scopeName != "":
+		process.ServiceName = scopeName
```
Comment (yurishkuro) [inline internal/storage/v2/elasticsearch/tracestore/to_dbmodel.go]: scope name is never a service name. Please do not change business logic in this PR.

File: internal/telemetry/otelsemconv/semconv.go (hunk 2 above)
Comment (danish9039) [reply internal/telemetry/otelsemconv/semconv.go]: @yurishkuro Because codebase has a mixed usage pattern where semantic convention keys are needed in two different contexts
1. Internal operations (attribute lookups, map keys, string comparisons) that require string constants
examples:
- to_dbmodel.go: Uses conventions.ServiceNameKey as string for comparisons
https://github.com/jaegertracing/jaeger/blob/a9c1473f1db7e9323cbb39879d418bb10f5ff3af/internal/storage/v2/elasticsearch/tracestore/to_dbmodel.go#L84
- memory.go: Uses conventions.ServiceNameKey as string for attribute lookups 
https://github.com/jaegertracing/jaeger/blob/a9c1473f1db7e9323cbb39879d418bb10f5ff3af/internal/storage/v2/memory/memory.go#L223 

 2. OpenTelemetry SDK calls that require `attribute.Key` types with methods like `.String()`
  examples:
- main.go: Needs `conventions.ServiceNameKey.String(svc) `for resource attributes
  https://github.com/jaegertracing/jaeger/blob/a9c1473f1db7e9323cbb39879d418bb10f5ff3af/cmd/tracegen/main.go#L89
- query_logger.go : `conventions.DBSystemKey.String("elasticsearch")
https://github.com/jaegertracing/jaeger/blob/a9c1473f1db7e9323cbb39879d418bb10f5ff3af/internal/storage/metricstore/elasticsearch/query_logger.go#L37

Comment (danish9039) [reply internal/telemetry/otelsemconv/semconv.go]: @yurishkuro  Should i Modify  semconv.go to provide both string constants and attribute.Key types??


something like 
```
const (
    ServiceNameKeyStr = "service.name"
)

var (
    ServiceNameKey = semconv.ServiceNameKey
)
  

```

Comment (yurishkuro) [reply internal/telemetry/otelsemconv/semconv.go]: how many places where the actual attribute is required? If it's just a couple, I would convert all Key constants to strings but for the places where the actual attribute is being created define functions, e.g.
```
func ServiceNameAttribute(value strign) {
  return otel.ServiceNameKey.String(svc) 
}
```

Comment (danish9039) [reply internal/telemetry/otelsemconv/semconv.go]: @yurishkuro got it ! , atrribute keys are used in total of six files, namely :  

https://github.com/jaegertracing/jaeger/blob/598e0a216518cca9f486824e2d24e84fa6bd7e9d/examples/hotrod/services/customer/database.go#L69

https://github.com/jaegertracing/jaeger/blob/598e0a216518cca9f486824e2d24e84fa6bd7e9d/internal/jtracer/jtracer.go#L106



https://github.com/jaegertracing/jaeger/blob/598e0a216518cca9f486824e2d24e84fa6bd7e9d/internal/storage/metricstore/elasticsearch/query_logger.go#L37


https://github.com/jaegertracing/jaeger/blob/598e0a216518cca9f486824e2d24e84fa6bd7e9d/cmd/tracegen/main.go#L89



https://github.com/jaegertracing/jaeger/blob/598e0a216518cca9f486824e2d24e84fa6bd7e9d/examples/hotrod/pkg/tracing/rpcmetrics/observer_test.go#L38




https://github.com/jaegertracing/jaeger/blob/598e0a216518cca9f486824e2d24e84fa6bd7e9d/examples/hotrod/pkg/tracing/init.go#L55

File: internal/storage/v2/elasticsearch/tracestore/to_dbmodel.go [hunk 4]
```diff
@@ -79,14 +79,23 @@ func resourceToDbProcess(resource pcommon.Resource) dbmodel.Process {
...
+		default:
+			tags = append(tags, attributeToDbTag(key, attr))
 		}
-		tags = append(tags, attributeToDbTag(key, attr))
 	}
+
+	if serviceName == "" {
+		serviceName = noServiceName
+	}
+	process.ServiceName = serviceName
```
[the remark this answers is not in the document]
Comment (danish9039) [reply internal/storage/v2/elasticsearch/tracestore/to_dbmodel.go]: already discussed https://github.com/jaegertracing/jaeger/pull/7318#discussion_r2210753320

File: internal/storage/v2/elasticsearch/tracestore/to_dbmodel.go [hunk 5]
```diff
@@ -79,14 +79,23 @@ func resourceToDbProcess(resource pcommon.Resource) dbmodel.Process {
...
 	for key, attr := range attrs.All() {
-		if key == conventions.AttributeServiceName {
-			process.ServiceName = attr.AsString()
-			continue
+		switch key {
+		case conventions.ServiceNameKey:
+			serviceName = attr.AsString()
+		case conventions.AttributeOtelScopeName:
+			tags = append(tags, attributeToDbTag(key, attr))
+		default:
```
Comment (yurishkuro) [inline internal/storage/v2/elasticsearch/tracestore/to_dbmodel.go]: these changes are not needed, please restore the original code. You only need to change one line in it.

File: internal/telemetry/otelsemconv/semconv.go [hunk 6]
```diff
@@ -13,21 +14,65 @@ import (
...
-	DBQueryTextKey            = semconv.DBQueryTextKey
-	DBSystemKey               = semconv.DBSystemNameKey
-	PeerServiceKey            = semconv.PeerServiceKey
-	HTTPResponseStatusCodeKey = semconv.HTTPResponseStatusCodeKey
-
-	HostIDKey   = semconv.HostIDKey
-	HostIPKey   = semconv.HostIPKey
-	HostNameKey = semconv.HostNameKey
+	// Telemetry SDK
+	TelemetrySDKLanguageKey   = "telemetry.sdk.language"
```
Comment (yurishkuro) [inline internal/telemetry/otelsemconv/semconv.go]: why are you redefining the strings? We should still read them from semconv
```
TelemetrySDKLanguageKey   = string(semconv.TelemetrySDKLanguageKey)
```

File: internal/storage/v2/memory/memory_test.go [hunk 7]
```diff
@@ -497,7 +497,7 @@ func TestGetOperationsWithKind(t *testing.T) {
 			require.NoError(t, err)
 			td := ptrace.NewTraces()
 			resourceSpan := td.ResourceSpans().AppendEmpty()
-			resourceSpan.Resource().Attributes().PutStr(conventions.AttributeServiceName, "service-z")
+			resourceSpan.Resource().Attributes().PutStr(conventions.ServiceNameKey, "service-z")
```
Comment (yurishkuro) [inline internal/storage/v2/memory/memory_test.go:500]: isn't there a Put version that takes the full attribute, something like
```
resourceSpan.Resource().Attributes().Put(conventions.ServiceNameAttribute("service-z"))
```

File: internal/storage/v2/elasticsearch/tracestore/to_dbmodel.go [hunk 8]
```diff
@@ -339,34 +342,35 @@ func getTagsFromInstrumentationLibrary(il pcommon.InstrumentationScope) ([]dbmod
...
 
 func refTypeFromLink(link ptrace.SpanLink) dbmodel.ReferenceType {
-	refTypeAttr, ok := link.Attributes().Get(conventions.AttributeOpentracingRefType)
-	if !ok {
-		return dbmodel.FollowsFrom
+	if refType, ok := link.Attributes().Get(conventions.AttributeOpentracingRefType); ok {
+		return strToDbSpanRefType(refType.Str())
 	}
-	return strToDbSpanRefType(refTypeAttr.Str())
+	return dbmodel.ChildOf
```
Comment (yurishkuro) [inline internal/storage/v2/elasticsearch/tracestore/to_dbmodel.go]: this is not equivalent change

File: internal/storage/v2/memory/memory_test.go (hunk 7 above)
Comment (danish9039) [reply internal/storage/v2/memory/memory_test.go:500]: @yurishkuro I have checked at the OpenTelemetry Go collector's pcommon.Map API (https://pkg.go.dev/go.opentelemetry.io/collector/pdata/pcommon#Map), there's no Put method that lets you pass in a complete attribute object like `conventions.ServiceNameAttribute("service-z")`.
