### PR TITLE
Respect environment variables when creating internal tracer

### LINKED ISSUE #6122: [Bug]: Jaeger Query Should Accept Configurable Jaeger Collector Address when enabled query.enable-tracing
### What happened?

Currently, when tracing is enabled (enable-tracing), jaeger-query defaults to localhost:4317 as the OTLP endpoint, which assumes that the Jaeger Collector is available on the same local address. This setup causes issues where Jaeger-query and the Jaeger Collector typically run in separate pods or hosts.

When jaeger-query cannot reach the Jaeger Collector at localhost:4317, tracing data fails to be exported, and the following connection errors are logged:
`{"level":"info","ts":1729846746.785025,"caller":"grpc@v1.66.0/clientconn.go:1319","msg":"[core] Creating new client transport to \"{Addr: \\\"127.0.0.1:4317\\\", ServerName: \\\"localhost:4317\\\", }\": connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:4317: connect: connection refused\""}`

### Steps to reproduce

1. Deploy Jaeger-query in a k8s environment with Jaeger collector in separate pods.
2. Enable tracing on Jaeger-query. (--query.enable-tracing = true)

### Expected behavior

jaeger-query should accept a configurable Jaeger Collector address when enable-tracing is enabled. Users should be able to specify this address through something like this: `--query.collector-address`

### Jaeger backend version

v1.60.0

### PR DESCRIPTION
**Pull request by akstron**
## Which problem is this PR solving?
Resolves #6122 

## Description of the changes
- The changes include using the `otlptracegrpc.WithInsecure()` based on `OTEL_EXPORTER_OTLP_ENDPOINT` and `OTEL_EXPORTER_OTLP_INSECURE` env variables.

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [ ] I have added unit tests for the new functionality
- [ ] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Comment by akstron** [comment]
I ran the failing `Build all-in-one / all-in-one (v1) (pull_request) ` without my changes, but it still fails for `getAPITrace` and `getServicesAPIV3`

File: pkg/jtracer/jtracer.go [hunk 1]
```diff
@@ -109,9 +111,17 @@ func otelResource(ctx context.Context, svc string) (*resource.Resource, error) {
 	)
 }
 
+func defaultGRPCOptions() []otlptracegrpc.Option {
+	var options []otlptracegrpc.Option
+	if strings.ToLower(os.Getenv("OTEL_EXPORTER_OTLP_INSECURE")) == "true" {
```
Comment (yurishkuro) [inline pkg/jtracer/jtracer.go:116]: https://github.com/jaegertracing/jaeger/blob/883d68193f36e717f1f0ec80b26b6f7a0718c5b4/examples/hotrod/pkg/tracing/init.go#L74

Comment (akstron) [reply pkg/jtracer/jtracer.go]: Added the negation of the above logic to add `Insecure` option.

**Review by yurishkuro — APPROVED** [review]
