### PR TITLE
Return 400 instead of 500 on incorrect OTLP payload

### LINKED ISSUE #6598: Return 400 instead of 500 from upload OTLP endpoint
Related to this UI issue https://github.com/jaegertracing/jaeger-ui/issues/2589

The UI asks the server to transform (http://localhost:16686/api/transform) data in OTLP into Jaeger UI model. If the payload is malformed the server responds with a 500 status code, which is incorrect since this is a user error and the status code should be one of 400s.

```json
{"data":null,"total":0,"limit":0,"offset":0,"errors":[{"code":500,"msg":"cannot unmarshal OTLP : readUint32: unexpected character: \ufffd, error found in #10 byte of ...|esCount\":-1}],\"links|..., bigger context ...|AR to the classpath\"}}],\"droppedAttributesCount\":-1}],\"links\":[],\"status\":{\"code\":2},\"flags\":257},{\"|..."}]}
```

### PR DESCRIPTION
**Pull request by ADI-ROXX**
## Which problem is this PR solving?
- Resolves #6598 

## Description of the changes
- Changed StatusInternalServerError to StatusBadRequest because otlp2traces doing the unmarshaling will go into error if there is error in the payload
- Added a new unit test for the change

## How was this change tested?
- make lint test => pass 

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [x] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `npm run lint` and `npm run test`

### CODE REVIEW

**Comment by ADI-ROXX** [comment]
@yurishkuro I think that the issue of the 500 error is coming because of the otlp2traces function called here:
image

I think that if the otlp payload cannot be converted into a JSON, there's definitely an issue with the payload and not the server. That's why I have replaced the status code

**Review by yurishkuro — COMMENTED** [review]
please add a unit test to validate that

**Comment by yurishkuro** [comment]
please make PR title more descriptive

**Comment by ADI-ROXX** [comment]
@yurishkuro I have added a test case in which I am providing a bad otlp payload and then I am checking is the phrase "400 error" is in the text or not.

File: cmd/query/app/http_handler_test.go [hunk 1]
```diff
@@ -769,6 +769,15 @@ func TestTransformOTLPBadPayload(t *testing.T) {
 	}, querysvc.QueryServiceOptions{})
 }
 
+func TestBadOTLPReturns400(t *testing.T) {
+	withTestServer(t, func(ts *testServer) {
+		response := new(any)
+		request := "Bad Payload"
+		err := postJSON(ts.server.URL+"/api/transform", request, response)
+		require.ErrorContains(t, err, "400 error")
```
Comment (yurishkuro) [inline cmd/query/app/http_handler_test.go:777]: why do we need to check for string error message instead of the actual status code?

Comment (ADI-ROXX) [reply cmd/query/app/http_handler_test.go:777]: We have to do it this way because:
image
postJSON returns a struct `"error"` which is:-
image

So it is a string like the following:
`"400 error from server: {\"data\":null,\"total\":0,\"limit\":0,\"offset\":0,\"errors\":[{\"code\":400,\"msg\":\"cannot unmarshal OTLP : ReadObjectCB: expect { or n, but found \\\", error found in #1 byte of ...|\\\"Bad Payloa|..., bigger context ...|\\\"Bad Payload\\\"\\n|...\"}]}\n"`

So, I have tried to keep the format same as there was earlier:
image

**Comment by ADI-ROXX** [comment]
@yurishkuro I have added a regex method to fetch the code and check if it is equal to 400 or not.

**Comment by ADI-ROXX** [comment]
@yurishkuro In the latest commit, I have directly checked the status code without the need of regex or anything else. Can you review it once?

File: cmd/query/app/http_handler_test.go [hunk 2]
```diff
@@ -769,6 +769,29 @@ func TestTransformOTLPBadPayload(t *testing.T) {
...
 
+func TestBadOTLPReturns400(t *testing.T) {
+	withTestServer(t, func(ts *testServer) {
+		url := ts.server.URL + "/api/transform"
+		request := "Bad Payload"
+		buf := &bytes.Buffer{}
+		encoder := json.NewEncoder(buf)
+		if err := encoder.Encode(request); err != nil {
+			require.Error(t, err)
+		}
```
Comment (yurishkuro) [inline cmd/query/app/http_handler_test.go:780]:
```suggestion
		require.NoError(t, encoder.Encode(request))
```

Comment (ADI-ROXX) [reply cmd/query/app/http_handler_test.go]: Resolved in the latest commit.

**Review by yurishkuro — APPROVED** [review]

**Review by yurishkuro — APPROVED** [review]

File: cmd/query/app/http_handler_test.go (hunk 2 above)
Comment (yurishkuro) [reply cmd/query/app/http_handler_test.go]: I expected you'd be able to pattern match on the suggestion and apply it consistently, not just to this line.
