### PR TITLE
[fix][query] Filter out tracing for access to static UI assets

### LINKED ISSUE #6265: Access to UI static assets should not be traced
Jaeger v2 (and probably v1 too) is now recording spans with names like these: `jaeger: /static/index-DgTHkKtK.js`. This is because we now use `confighttp.ToServer` helper that installs the tracing handlers unconditionally. There are options we can pass to the tracing instrumentation with filters such that certain endpoints may be ignored.

cc @mahadzaryab1

### PR DESCRIPTION
**Pull request by mahadzaryab1**
## Which problem is this PR solving?
- Fixes #6265

## Description of the changes
- Adds a filter from `xconfighttp` to ignore accesses to static UI assets at `/static/*`

## Testing
I ran the monitor example and accessed the Jaeger UI to test that the traces were getting recorded on main but not in this PR. 

### On main
```
curl -s "http://localhost:16686/api/traces?service=jaeger" | jq -r '.data[].spans[] | select(.operationName | startswith("/static")) | .operationName'
/static/jaeger-logo-CNZsoUdk.svg
/static/index-bzTJ6oK_.css
/static/index-BDRwFQ_z.js
```
### This PR 
```
curl -s "http://localhost:16686/api/traces?service=jaeger" | jq -r '.data[].spans[] | select(.operationName | startswith("/static")) | .operationName'
```

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [x] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `npm run lint` and `npm run test`

### CODE REVIEW

File: cmd/query/app/server.go [hunk 1]
```diff
@@ -219,6 +222,12 @@ func createHTTPServer(
 			MeterProvider:  telset.MeterProvider,
 		},
 		handler,
+		xconfighttp.WithOtelHTTPOptions(
+			otelhttp.WithFilter(func(r *http.Request) bool {
+				ignorePaths := regexp.MustCompile(`^/static/.*`)
```
Comment (yurishkuro) [inline cmd/query/app/server.go:227]: 1. `^/static/.*` does not require regex, can be matched with `strings.HasPrefix`
2. it doesn't look like it will work if the UI is running with a custom base path, we need to account for that too

Comment (mahadzaryab1) [reply cmd/query/app/server.go:227]: @yurishkuro for 2 - do we want to do a `contains` to see if the `/static` path is anywhere in the URL?

Comment (yurishkuro) [reply cmd/query/app/server.go:227]: that would be a bit fuzzy. I would rather use HasPrefix with `basePath + "/static/"`

Comment (mahadzaryab1) [reply cmd/query/app/server.go:227]: done

Comment (yurishkuro) [reply cmd/query/app/server.go:227]:
```diff
git diff cmd/jaeger/config.yaml

   jaeger_query:
+    base_path: /foobar
     storage:
       traces: some_store
       traces_archive: another_store
```
```
$ go run ./cmd/jaeger --config ./cmd/jaeger/config.yaml
```
Reload UI a few times, observe span `/foobar/static/favicon-BxcVf0am.ico`

So, not solved.

Comment (mahadzaryab1) [reply cmd/query/app/server.go]: @yurishkuro apologies - i forgot to push my commits

File: cmd/query/app/server.go [hunk 2]
```diff
@@ -219,6 +222,12 @@ func createHTTPServer(
 			MeterProvider:  telset.MeterProvider,
 		},
 		handler,
+		xconfighttp.WithOtelHTTPOptions(
+			otelhttp.WithFilter(func(r *http.Request) bool {
+				ignorePath := path.Join("/", queryOpts.BasePath, "static")
```
Comment (yurishkuro) [inline cmd/query/app/server.go:227]: Can `queryOpts.BasePath` be `/` here? If so it will create invalid `//static` prefix.

Comment (mahadzaryab1) [reply cmd/query/app/server.go:227]: @yurishkuro yeah it can - `path.Join` removes duplicate slashes. The leading slash needs to be there in the case where `queryOpts.BasePath` is empty because a slash doesn't get added in that case.

**Review by yurishkuro — APPROVED** [review]
