### PR TITLE
Kafka: Add new Consumer and Producer flags

### LINKED ISSUE #1190: [ingester] Crash if Kafka is specified as storage
Reported by @ledor473 - https://github.com/jaegertracing/jaeger/pull/1094#issuecomment-439221399

I've just realized that if you run the Ingester with `SPAN_STORAGE_TYPE=elasticsearch,kafka`, the Ingester crash with the following:
```
WARNING: multiple span storage types have been specified. Only the first type (elasticsearch) will be used for reading and archiving.

flag redefined: kafka.brokers
panic: flag redefined: kafka.brokers

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc000080d80, 0xefd9a0, 0xc00018d080, 0xe04f6e, 0xd, 0xe2cb58, 0x4b)
	/home/travis/.gimme/versions/go1.11.1.linux.amd64/src/flag/flag.go:805 +0x529
flag.(*FlagSet).StringVar(0xc000080d80, 0xc00018d080, 0xe04f6e, 0xd, 0xe05426, 0xe, 0xe2cb58, 0x4b)
	/home/travis/.gimme/versions/go1.11.1.linux.amd64/src/flag/flag.go:708 +0x8a
flag.(*FlagSet).String(0xc000080d80, 0xe04f6e, 0xd, 0xe05426, 0xe, 0xe2cb58, 0x4b, 0xe00e66)
	/home/travis/.gimme/versions/go1.11.1.linux.amd64/src/flag/flag.go:721 +0x8b
github.com/jaegertracing/jaeger/cmd/ingester/app.AddFlags(0xc000080d80)
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/app/flags.go:84 +0x6e
github.com/jaegertracing/jaeger/pkg/config.AddFlags(0xc00015a0f0, 0xc000186240, 0xc000159f28, 0x5, 0x5, 0xc00003a042, 0xd)
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/pkg/config/config.go:36 +0x56
main.main()
	/home/travis/gopath/src/github.com/jaegertracing/jaeger/cmd/ingester/main.go:138 +0x59f
```

I'm not sure how, but I feel we should add a validation on the storage type to prevent the use to `KAFKA` in the Ingester. Unless we want to support Kafka -> Kafka with the Ingester, but that feels wrong

### PR DESCRIPTION
**Pull request by ledor473**
## Which problem is this PR solving?
- Closes #1190 

## Short description of the changes
Replace #1231 and implement this: https://github.com/jaegertracing/jaeger/pull/1231#issuecomment-457276236

- Add `kafka.producer` flags in plugins/storage/kafka
- Add `kafka.consumer` flags in Ingester
- Deprecate `kafka` flags

### CODE REVIEW

File: cmd/ingester/app/flags.go [hunk 1]
```diff
@@ -106,14 +108,61 @@ func AddFlags(flagSet *flag.FlagSet) {
 		DefaultDeadlockInterval,
 		"Interval to check for deadlocks. If no messages gets processed in given time, ingester app will exit. Value of 0 disables deadlock check.")
 
+	// TODO: Remove deprecated flags after 1.11
+	flagSet.String(
+		DeprecatedKafkaConfigPrefix+SuffixBrokers,
+		DefaultBroker,
+		"Deprecated; The comma-separated list of kafka brokers. i.e. '127.0.0.1:9092,0.0.0:1234'")
```
Comment (yurishkuro) [inline cmd/ingester/app/flags.go]: rather than explaining the meaning, I suggest we refer to the new flag that's replacing this one, i.e. "deprecated; replaced by xxx"

File: cmd/ingester/app/flags.go [hunk 2]
```diff
@@ -106,14 +108,61 @@ func AddFlags(flagSet *flag.FlagSet) {
...
+			DeprecatedKafkaConfigPrefix+SuffixEncoding,
+			KafkaConsumerConfigPrefix+SuffixEncoding,
+		)
+		o.Encoding = encoding
+	}
+
+	o.Brokers = strings.Split(v.GetString(KafkaConsumerConfigPrefix+SuffixBrokers), ",")
+	o.Topic = v.GetString(KafkaConsumerConfigPrefix + SuffixTopic)
+	o.GroupID = v.GetString(KafkaConsumerConfigPrefix + SuffixGroupID)
+	o.Encoding = v.GetString(KafkaConsumerConfigPrefix + SuffixEncoding)
```
Comment (yurishkuro) [inline cmd/ingester/app/flags.go]: if the new flags are not specified, wouldn't all these values become empty?

Comment (ledor473) [reply cmd/ingester/app/flags.go]: I've rework the PR and added a test for that.
I wasn't sure which flags we should prefer if both are specified, currently the old flags will win over the new flags if both are specified (as per the test)

**Comment by ledor473** [comment]
I wonder if retrying the CI jobs would fix it

File: cmd/ingester/app/flags.go [hunk 3]
```diff
@@ -106,14 +108,61 @@ func AddFlags(flagSet *flag.FlagSet) {
...
+		fmt.Sprintf("Deprecated; replaced by %s", KafkaConsumerConfigPrefix+SuffixEncoding))
 }
 
 // InitFromViper initializes Builder with properties from viper
 func (o *Options) InitFromViper(v *viper.Viper) {
-	o.Brokers = strings.Split(v.GetString(KafkaConfigPrefix+SuffixBrokers), ",")
-	o.Topic = v.GetString(KafkaConfigPrefix + SuffixTopic)
-	o.GroupID = v.GetString(KafkaConfigPrefix + SuffixGroupID)
-	o.Encoding = v.GetString(KafkaConfigPrefix + SuffixEncoding)
+	o.Brokers = strings.Split(v.GetString(KafkaConsumerConfigPrefix+SuffixBrokers), ",")
```
Comment (yurishkuro) [inline cmd/ingester/app/flags.go]: we recently fixed a bug where the list of hosts for Cassandra or ES would not parse correctly if they contained spaces. Perhaps worth reusing the same util method.

Comment (ledor473) [reply cmd/ingester/app/flags.go]: I’ll bundle that suggestion into the PR tha delete the deprecated flags (to be merged post 1.11)
