### PR TITLE
Fix badger merge-join algorithm to correctly filter indexes

### LINKED ISSUE #1719: Badger index merge is working incorrectly
## Problem - what in Jaeger blocks you from solving the requirement?

While doing some additional tests, I managed to create a case where the end result that used multiple index queries was not correct.

Merge-join processing has bugs.

* Missing one advance in the equality compare
* Input for the next round should be the output of previous invocation (in same sorted order)

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Working on it, adding also some more tests also to verify more complex index merge scenarios.

### PR DESCRIPTION
**Pull request by burmanm**
## Which problem is this PR solving?

Resolves #1719, the index seeks were not correctly merged and filtered. 

## Short description of the changes

Make the merge-join correctly update two indices when encountering equal items. Also, the input must be the output of previous merge. Also, changed ASC to DESC reversing to happen after the top query filtering - thus reducing unnecessary work.

### CODE REVIEW

File: plugin/storage/badger/spanstore/reader.go [hunk 1]
```diff
@@ -346,53 +345,60 @@ func (r *TraceReader) durationQueries(query *spanstore.TraceQueryParameters, ids
...
 		}
-
 	} else {
-		// mergeIntersected should be reversed intersected
-		for i, j := 0, len(intersected)-1; j >= 0; i, j = i+1, j-1 {
-			mergeIntersected = append(mergeIntersected, intersected[j])
-		}
-		intersected = mergeIntersected
+		merged = ids[0]
+
```
Comment (pavolloffay) [inline plugin/storage/badger/spanstore/reader.go]: nit: remove line?

File: plugin/storage/badger/spanstore/reader.go [hunk 2]
```diff
@@ -346,53 +345,60 @@ func (r *TraceReader) durationQueries(query *spanstore.TraceQueryParameters, ids
 	return ids
 }
 
+func mergeJoinIds(left, right [][]byte) [][]byte {
+	merged := make([][]byte, 0, len(left)) // len(left) or len(right) is the maximum, whichever is smallest
```
Comment (pavolloffay) [inline plugin/storage/badger/spanstore/reader.go]: Why not allocate the smallest and use the size also in the following loop?

File: plugin/storage/badger/spanstore/reader.go [hunk 3]
```diff
@@ -346,53 +345,60 @@ func (r *TraceReader) durationQueries(query *spanstore.TraceQueryParameters, ids
 	return ids
 }
 
+func mergeJoinIds(left, right [][]byte) [][]byte {
```
Comment (pavolloffay) [inline plugin/storage/badger/spanstore/reader.go]: rename to `mergeEqualIds` ?

Comment (pavolloffay) [reply plugin/storage/badger/spanstore/reader.go]: Are the ids sorted? Maybe that should be documented somewhere.

Comment (burmanm) [reply plugin/storage/badger/spanstore/reader.go]: It's mentioned at the beginning of the package. Everything is sorted (it's a sorted K/V).

Comment (burmanm) [reply plugin/storage/badger/spanstore/reader.go]: As for the name, it's because the algorithm is called "sort-merge join" and is used in relational databases. Here the sorting phase happens in the DB and the merge phase in this code. It's pretty descriptive in my opinion since if someone wants to improve this method such as doing it parallel or using sharding from multiple badgers there are known algorithms for those variations too (which would underneath use this in any case).

Comment (pavolloffay) [reply plugin/storage/badger/spanstore/reader.go]: Thanks for the explanation. Now it rings a bell..

File: plugin/storage/badger/spanstore/read_write_test.go [hunk 4]
```diff
@@ -200,6 +205,7 @@ func TestIndexSeeks(t *testing.T) {
 		params.OperationName = "operation-1"
 		tags := make(map[string]string)
 		tags["k11"] = "val0"
+		tags["error"] = "true"
```
[the remark this answers is not in the document]
Comment (burmanm) [reply plugin/storage/badger/spanstore/read_write_test.go]: Devil is in the details. That single line exploits the bug (the test fails with older version) since it adds another index query against the tags.

[the remark this answers is not in the document]
Comment (burmanm) [reply plugin/storage/badger/spanstore/read_write_test.go]: As for the id list, it is basically the list of matches for the search query. A form of a posting list (of traceIDs) if thinking in terms of the ES.

In terms of relational database, it's equivalent to something like: ``SELECT id FROM dbo.spans WHERE service = 'invoices'`` 

That is, a single id list is equivalent to that one. Just imagine each id list is one similar query, touching a single index and single value. It doesn't matter if the index is the same or not (so one query could be against service, one against tags index etc).
