### PR TITLE
Pass username/password to Cassandra docker-compose health check

### LINKED ISSUE #6215: [Bug]: cassandra container never becomes healthy
### What happened?

Post addition of password-based authentication, the Cassandra container spawned by the docker-compose never becomes healthy. This is because the username and password is not provided to the health check cmd.

Image

Upon checking health check stat using: `docker inspect --format "{{json .State.Health }}" "v4-cassandra-1" | jq`

Image

### Steps to reproduce

1. `docker compose -f "docker-compose/cassandra/v4/docker-compose.yaml" up -d`

### Expected behavior

1. Getting a `healthy` status at some point and no authentication error logs.

### Relevant log output

```shell
 "Status": "unhealthy",
  "FailingStreak": 9,
  "Log": [
    {
      "Start": "2024-11-16T13:37:50.300599482Z",
      "End": "2024-11-16T13:37:50.659393355Z",
      "ExitCode": 1,
      "Output": "Connection error: ('Unable to connect to any servers', {'127.0.0.1:9042': AuthenticationFailed('Remote end requires authentication')})\n"
    },
    {
      "Start": "2024-11-16T13:38:20.658710087Z",
      "End": "2024-11-16T13:38:21.009395221Z",
      "ExitCode": 1,
      "Output": "Connection error: ('Unable to connect to any servers', {'127.0.0.1:9042': AuthenticationFailed('Remote end requires authentication')})\n"
    },
```

### Jaeger backend version

Both v1 and v2

### Stogage backend

Cassandra v4

### PR DESCRIPTION
**Pull request by akstron**
## Which problem is this PR solving?
- Resolves #6215 

## Description of the changes
- Added the username and password values for health check cmd
- Added `healthcheck_cassandra` point to make sure the container is healthy as per the cmd.

## How was this change tested?
- bash scripts/cassandra-integration-test.sh 4 v004 v1 
- bash scripts/cassandra-integration-test.sh 4 v004 v2

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [ ] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Comment by akstron** [comment]
> I don't mind this change, but I would like to understand what specifically it's fixing since our CI was fine without it. And if it fixes a real problem then why didn't our CI catch it before.

Replied in the issue linked. Thanks

File: scripts/cassandra-integration-test.sh [hunk 1]
```diff
@@ -26,6 +26,19 @@ setup_cassandra() {
   docker compose -f "$compose_file" up -d
 }
 
+healthcheck_cassandra() {
+  local cas_version=$1
+  local container_name="cassandra-${cas_version}"
+  local status="unhealthy"
+  while [[ ${status} != "healthy" ]]; do
```
Comment (yurishkuro) [inline scripts/cassandra-integration-test.sh:33]: This is not how we usually perform liveness checks. This will loop forever, but we want to timeout at some point. Please check other scripts for deadline based checks.

Comment (akstron) [reply scripts/cassandra-integration-test.sh]: Done. Thanks

**Review by yurishkuro — APPROVED** [review]

**Comment by yurishkuro** [comment]
Thanks
