### PR TITLE
Avoid process crash when elasticsearch response is nil

### LINKED ISSUE #1440: es client afterFn should check the case of resp == nil
## Proposal - what do you suggest to solve the problem or improve the existing situation?
add nil pointer check before using es response pointer, such as : https://github.com/jaegertracing/jaeger/blob/21e9ab49048740c20cb0d01893b0134ff12ce80c/pkg/es/config/config.go#L117

### PR DESCRIPTION
**Pull request by YEXINGZHE54**
Add nil pointer check in elasticsearch bulkprocessor's
after callback, defined inside pkg/es/config/config.go.
In some rare cases, elasticsearch request will return
error with nil response, and then nil response will
be passed into after callback, and using of nil pointer
will cause process crash.
Signed-off-by: YEXINGZHE54 <429567185@qq.com>

## Which problem is this PR solving?
- Resolves #1440 

## Short description of the changes
- Add nil pointer check inside es after callback

### CODE REVIEW

File: pkg/es/config/config.go [hunk 1]
```diff
@@ -127,13 +127,21 @@ func (c *Configuration) NewClient(logger *zap.Logger, metricsFactory metrics.Fac
 
 			sm.Emit(err, time.Since(start.(time.Time)))
 			if err != nil {
-				failed := len(response.Failed())
+				var failed int
+				var respval interface{}
+				if response == nil {
+					failed = 0
+					respval = "nil"
```
Comment (pavolloffay) [inline pkg/es/config/config.go]: isn't this logged by default as nil when it's nil?

Comment (YEXINGZHE54) [reply pkg/es/config/config.go]: yes , it will be logged as null by default; I will remove unneeded action
