### PR TITLE
[Fix] Prevent panic when sanitizing read-only traces with multiple exporters

### LINKED ISSUE #7221: [Bug] Jaeger v2 panics when exporting a span without "service.name" to multiple exporters
### What happened?

Jaeger v2 panics when exporting a span without "service.name" to multiple exporters

Please note the following code:
https://github.com/open-telemetry/opentelemetry-collector/blob/4ddf2cc7c8be95889feed96284c83d52230c63b8/internal/fanoutconsumer/traces.go#L66-L74

`td.MarkReadOnly()` is invoked when there are multiple exporters in the pipeline. After that, the trace data can no longer be modified.

that’s why sanitizeEmptyServiceName causes a panic.

### Steps to reproduce

1. start jaeger v2 with two trace exporter(debug, jaeger_storage_exporter)
2. send a span without `service.name` resource attributes
3. you will get panic

another way to reproduce:

Run the `TestExporter` with the code ` traces.MarkReadOnly()` added above this line:
https://github.com/jaegertracing/jaeger/blob/5957be0dd7871bdb186501eca6f4c38349ef9e0a/cmd/jaeger/internal/exporters/storageexporter/exporter_test.go#L144

### Expected behavior

jaeger v2 not panic when using more than one exporter

### Relevant log output

```shell
panic log:

panic: invalid access to shared data

goroutine 110 [running]:
go.opentelemetry.io/collector/pdata/internal.(*State).AssertMutable(...)
  go.opentelemetry.io/collector/pdata@v1.33.0/internal/state.go:20
go.opentelemetry.io/collector/pdata/pcommon.Map.PutStr({0xc000f2c438?, 0xc000d8e6c8?}, {0x3f410c0?, 0xc?}, {0x3f6e303?, 0xc00018e1d0?})
  go.opentelemetry.io/collector/pdata@v1.33.0/pcommon/map.go:126 +0x26d
github.com/jaegertracing/jaeger/internal/jptrace/sanitizer.sanitizeEmptyServiceName({0xc000bcc5b8?, 0xc000d8e6c8?})
  github.com/jaegertracing/jaeger/internal/jptrace/sanitizer/emptyservicename.go:35 +0x245
github.com/jaegertracing/jaeger/internal/jptrace/sanitizer.init.NewChainedSanitizer.func1({0xc000bcc5b8?, 0xc000d8e6c8?})
  github.com/jaegertracing/jaeger/internal/jptrace/sanitizer/sanitizer.go:34 +0x3c
github.com/jaegertracing/jaeger/cmd/jaeger/internal/exporters/storageexporter.(*storageExporter).pushTraces(0xc000a92060, {0x48e5148, 0xc000c5af30}, {0xc000bcc5b8?, 0xc000d8e6c8?})
  github.com/jaegertracing/jaeger/cmd/jaeger/internal/exporters/storageexporter/exporter.go:53 +0x36
go.opentelemetry.io/collector/consumer.ConsumeTracesFunc.ConsumeTraces(0xc000a34cf0?, {0x48e5148?, 0xc000c5af30?}, {0xc000bcc5b8?, 0xc000d8e6c8?})
  go.opentelemetry.io/collector/consumer@v1.33.0/traces.go:27 +0x37
go.opentelemetry.io/collector/exporter/exporterhelper.NewTraces.requestConsumeFromTraces.func2({0x48e5148?, 0xc000c5af30?}, {0x48b6818?, 0xc0001acff0?})
  go.opentelemetry.io/collector/exporter@v0.127.0/exporterhelper/traces.go:121 +0x4a
go.opentelemetry.io/collector/exporter/exporterhelper/internal/sender.(*sender[...]).Send(...)
  go.opentelemetry.io/collector/exporter@v0.127.0/exporterhelper/internal/sender/sender.go:31
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*obsReportSender[...]).Send(0x48d2dc0, {0x48e5148, 0xc000a92210?}, {0x48b6818?, 0xc0001acff0})
  go.opentelemetry.io/collector/exporter@v0.127.0/exporterhelper/internal/obs_report_sender.go:92 +0x9b
go.opentelemetry.io/collector/exporter/exporterhelper/internal.(*BaseExporter).Send(0xc000899600, {0x48e5148, 0xc000a92210}, {0x48b6818, 0xc0001acff0})
  go.opentelemetry.io/collector/exporter@v0.127.0/exporterhelper/internal/base_exporter.go:114 +0x8f
go.opentelemetry.io/collector/exporter/exporterhelper.NewTracesRequest.newConsumeTraces.func1({0x48e5148, 0xc000a92210}, {0xc000bcc5b8?, 0xc000d8e6c8?})
  go.opentelemetry.io/collector/exporter@v0.127.0/exporterhelper/traces.go:176 +0x2b0
go.opentelemetry.io/collector/consumer.ConsumeTracesFunc.ConsumeTraces(...)
  go.opentelemetry.io/collector/consumer@v1.33.0/traces.go:27
go.opentelemetry.io/collector/internal/fanoutconsumer.(*tracesConsumer).ConsumeTraces(0x3bda4c0?, {0x48e5148, 0xc000a92210}, {0xc000bcc5b8?, 0xc000d8e6c8?})
  go.opentelemetry.io/collector/internal/fanoutconsumer@v0.127.0/traces.go:71 +0x9c
go.opentelemetry.io/collector/processor/batchprocessor.(*batchTraces).export(0xc000b50f40?, {0x48e5148?, 0xc000a92210?}, {0xc000bcc5b8?, 0xc000d8e6c8?})
  go.opentelemetry.io/collector/processor/batchprocessor@v0.127.0/batch_processor.go:455 +0x2f
go.opentelemetry.io/collector/processor/batchprocessor.(*shard[...]).sendItems(0xc000047f34, 0x0?)
  go.opentelemetry.io/collector/processor/batchprocessor@v0.127.0/batch_processor.go:262 +0x8b
go.opentelemetry.io/collector/processor/batchprocessor.(*shard[...]).startLoop(0x49156c0)
  go.opentelemetry.io/collector/processor/batchprocessor@v0.127.0/batch_processor.go:222 +0x1c5
created by go.opentelemetry.io/collector/processor/batchprocessor.(*shard[...]).start in goroutine 1
  go.opentelemetry.io/collector/processor/batchprocessor@v0.127.0/batch_processor.go:186 +0x8a
```

### Screenshot

_No response_

### Additional context

_No response_

### Jaeger backend version

v2.7.0

### SDK

_No response_

### Pipeline

Please note that this configuration is used by a rebuilt Jaeger v2 with the `transformprocessor`. You can easily set it up on your local machine.
```
service:
  extensions: [jaeger_storage, remote_sampling, healthcheckv2, expvar, zpages]
  pipelines:
    traces:
      receivers: [otlp, jaeger, zipkin]
      processors: [transform,batch]
      exporters: [debug, jaeger_storage_exporter]
  telemetry:
    resource:
      service.name: jaeger
    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: "0.0.0.0"
                port: 8888
    logs:
      level: info
    # TODO Initialize telemetry tracer once OTEL released new feature.
    # https://github.com/open-telemetry/opentelemetry-collector/issues/10663

extensions:
  jaeger_query:
    storage:
      traces: some_storage

  jaeger_storage:
    backends:
      some_storage:
        memory:
          max_traces: 100000

  remote_sampling:
    # We can either use file or adaptive sampling strategy in remote_sampling
    file:
      path:
      default_sampling_probability: 1
      reload_interval: 1s
    # adaptive:
    #   sampling_store: some_store
    #   initial_sampling_probability: 0.1
    http:
      endpoint: "0.0.0.0:5778"
    grpc:
      endpoint: "0.0.0.0:5779"

  healthcheckv2:
    use_v2: true
    http:
      endpoint: "0.0.0.0:13133"
    grpc:

  expvar:
    endpoint: "0.0.0.0:27777"

  zpages:
    # for some reason the official extension listens on ephemeral port 55679
    # so we override it with a normal port
    endpoint: "0.0.0.0:27778"

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"

  jaeger:
    protocols:
      grpc:
        endpoint: "0.0.0.0:14250"
      thrift_http:
        endpoint: "0.0.0.0:14268"
      thrift_binary:
        endpoint: "0.0.0.0:6832"
      thrift_compact:
        endpoint: "0.0.0.0:6831"

  zipkin:
    endpoint: "0.0.0.0:9411"

processors:
  batch:
  transform:
    error_mode: ignore
    trace_statements:
      - delete_key(resource.attributes, "service.name")

exporters:
  debug:
    # verbosity: detailed
    verbosity: detailed
    sampling_initial: 1
    sampling_thereafter: 1000
  jaeger_storage_exporter:
    trace_storage: some_storage
```

### Stogage backend

_No response_

### Operating system

_No response_

### Deployment model

_No response_

### Deployment configs

```shell

```

### PR DESCRIPTION
**Pull request by victornguen**
## Which problem is this PR solving?
- Resolves #7221 

## Description of the changes
Implement copy-on-write approach for all sanitizers:

- Check if modifications are needed before attempting changes
- Return original traces if no sanitization required
- Test mutability and create a copy if data is read-only
- Apply modifications to the working copy instead of original data

## How was this change tested?
- Tests each sanitizer with read-only traces that need modification
- Tests each sanitizer with read-only traces that don't need modification
- Added test in storage exporter that reproduces the original panic scenario

## Checklist
- [X] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [X] I have signed all commits
- [X] I have added unit tests for the new functionality
- [X] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `npm run lint` and `npm run test`

### CODE REVIEW

File: internal/jptrace/sanitizer/negative_duration_santizer.go [hunk 1]
```diff
@@ -26,10 +26,58 @@ func NewNegativeDurationSanitizer() Func {
...
+		}
+	}
+
+	if !needsModification {
+		return traces
+	}
+
+	var workingTraces ptrace.Traces
+
+	canModify := true
```
Comment (yurishkuro) [inline internal/jptrace/sanitizer/negative_duration_santizer.go]: there is IsReadOnly function, why do we need to test via panic?

Comment (victornguen) [reply internal/jptrace/sanitizer/negative_duration_santizer.go]: my bad, I've refactored it

File: internal/jptrace/sanitizer/negative_duration_santizer.go [hunk 2]
```diff
@@ -26,10 +26,42 @@ func NewNegativeDurationSanitizer() Func {
...
 		resourceSpan := resourceSpans.At(i)
 		scopeSpans := resourceSpan.ScopeSpans()
+		for j := 0; j < scopeSpans.Len() && !needsModification; j++ {
+			scopeSpan := scopeSpans.At(j)
+			spans := scopeSpan.Spans()
+			for k := 0; k < spans.Len() && !needsModification; k++ {
+				span := spans.At(k)
+				if spanNeedsDurationSanitization(span) {
+					needsModification = true
+					break
```
Comment (yurishkuro) [inline internal/jptrace/sanitizer/negative_duration_santizer.go]: this only breaks out of the inner loop, you need to use a label at the outer loop and `break outerloop`. Or move the check to a function and `return true`

File: internal/jptrace/sanitizer/emptyservicename.go [hunk 3]
```diff
@@ -23,12 +23,44 @@ func NewEmptyServiceNameSanitizer() Func {
...
+	if traces.IsReadOnly() {
+		workingTraces = ptrace.NewTraces()
+		traces.CopyTo(workingTraces)
+	} else {
+		workingTraces = traces
+	}
+
+	workingResourceSpans := workingTraces.ResourceSpans()
+	for i := 0; i < workingResourceSpans.Len(); i++ {
+		resourceSpan := workingResourceSpans.At(i)
```
Comment (yurishkuro) [inline internal/jptrace/sanitizer/emptyservicename.go]: I think you can simplify using iterators
```suggestion
	for resourceSpan := range workingTraces.ResourceSpans().All()  {
```

File: internal/jptrace/sanitizer/utf8.go [hunk 4]
```diff
@@ -55,7 +68,50 @@ func sanitizeUTF8(traces ptrace.Traces) ptrace.Traces {
...
+				}
+			}
+		}
+	}
+	return false
+}
+
+func attributesNeedUTF8Sanitization(attributes pcommon.Map) bool {
+	needsSanitization := false
+	attributes.Range(func(k string, v pcommon.Value) bool {
```
Comment (yurishkuro) [inline internal/jptrace/sanitizer/utf8.go]: could you use iterator here?
```
for k, v := attributes.All()
```

**Review by yurishkuro — APPROVED** [review]

**Comment by yurishkuro** [comment]
Both DCO checks are failing. My recommendation is to squash all commits into one and make sure it is signed correctly. See CONTRIBUTING for help.

**Comment by victornguen** [comment]
Thanks, I squashed the commits. DCO passed.
