### PR TITLE
fix: Right-align bytes in convertTraceIDFromDB for 64-bit trace IDs

### LINKED ISSUE #8266: [Bug]: Corrupted 64-bit Trace IDs when reading from Elasticsearch in v2 storage
### What happened?

There is a critical bug in the v2 Elasticsearch storage backend reader where 64-bit Trace IDs are incorrectly padded when converted to OpenTelemetry `pcommon.TraceID` types. This results in the complete corruption of the Trace ID. 

In `internal/storage/v2/elasticsearch/tracestore/ids.go`, the `convertTraceIDFromDB` function translates a DB trace ID (a hex-encoded string) into a 16-byte OpenTelemetry `pcommon.TraceID`. 

```go
func convertTraceIDFromDB(dbTraceId dbmodel.TraceID) (pcommon.TraceID, error) {
	var traceId [16]byte
	traceBytes, err := hex.DecodeString(string(dbTraceId))
	if err != nil {
		return pcommon.TraceID{}, err
	}
	copy(traceId[:], traceBytes) // BUG: Left-aligns the bytes
	return traceId, nil
}


### Steps to reproduce


### **Steps to reproduce**
```markdown
1. Configure Jaeger with the `v2` Elasticsearch storage backend.
2. Query a trace that originally had a 64-bit Trace ID (16 hex characters).
3. Observe that the returned trace data has a corrupted 128-bit Trace ID where the 64-bit value is shifted to the left and padded with zeros on the right (e.g., `[original_id]0000000000000000`).


### Expected behavior

When reading a 64-bit Trace ID from Elasticsearch, it should be mapped to the lower 8 bytes (right-aligned) of the `pcommon.TraceID` so that the trace ID accurately reflects `0000000000000000[original_id]`.


### Relevant log output

```shell

```

### Screenshot

_No response_

### Additional context

I have audited the code and know how to fix the padding logic to ensure the bytes are correctly right-aligned when the decoded slice is less than 16 bytes. 

I would love to contribute the fix for this issue! **Could a mentor please assign this to me so I can submit a PR?**

### Jaeger backend version

main (v2 storage pipeline)

### SDK

N/A

### Pipeline

N/A

### Stogage backend

v2 Elasticsearch

### Operating system

 All

### Deployment model

N/A

### Deployment configs

```shell
N/A
```

### PR DESCRIPTION
**Pull request by Anujkumar9081**
Resolves #8266

## Description of the changes
-  Fixed convertTraceIDFromDB in internal/storage/v2/elasticsearch/tracestore/ids.go where 64-bit Trace IDs were 
    incorrectly left-aligned when converted to 128-bit pcommon.TraceID.
-  The original code used copy(traceId[:], traceBytes) which places 8 decoded bytes into positions [0:8] of the 16-byte 
    array, corrupting the Trace ID.
-  Changed to copy(traceId[16-len(traceBytes):], traceBytes) to right-align the bytes into positions [8:16], correctly 
    representing the 64-bit value in the lower bytes of the 128-bit array.
-  Applied the same right-alignment fix to fromDbSpanId for consistency.
- Added ids_test.go with comprehensive test coverage for both functions, including 128-bit IDs, 64-bit IDs, and invalid 
   hex input cases

## How was this change tested?
- Added new unit tests in ids_test.go covering:
     - 128-bit trace ID (32 hex chars) — full byte array populated correctly
     - 64-bit trace ID (16 hex chars) — bytes right-aligned to lower 8 positions
     - Invalid hex string — error returned correctly
     - Full 64-bit span ID (16 hex chars) — all bytes populated
     - Shorter span ID — bytes right-aligned correctly
     - Invalid span ID hex — error returned correctly
- Ran make fmt, make lint (0 issues), and go test ./internal/storage/v2/elasticsearch/tracestore/... (all pass)

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/main/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [x] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully: `make lint test`

## AI Usage in this PR (choose one)
See [AI Usage Policy](https://github.com/jaegertracing/jaeger/blob/main/CONTRIBUTING_GUIDELINES.md#ai-usage-policy).
- [ ] **None**: No AI tools were used in creating this PR
- [x] **Light**: AI provided minor assistance (formatting, simple suggestions)
- [ ] **Moderate**: AI helped with code generation or debugging specific parts
- [ ] **Heavy**: AI generated most or all of the code changes

### CODE REVIEW

File: internal/storage/v2/elasticsearch/tracestore/ids.go [hunk 1]
```diff
@@ -17,7 +17,9 @@ func convertTraceIDFromDB(dbTraceId dbmodel.TraceID) (pcommon.TraceID, error) {
 	if err != nil {
 		return pcommon.TraceID{}, err
 	}
-	copy(traceId[:], traceBytes)
+	// Right-align the bytes so that shorter (e.g. 64-bit) trace IDs
+	// are placed in the lower bytes of the 128-bit array.
+	copy(traceId[16-len(traceBytes):], traceBytes)
 	return traceId, nil
 }
```
[the remark this answers is not in the document]
Comment (yurishkuro) [reply internal/storage/v2/elasticsearch/tracestore/ids.go:32]: +1, could add a new len check

**Comment by yurishkuro** [comment]
please make sure all commits are signed

**Comment by Anujkumar9081** [comment]
@yurishkuro Thanks for reviewing! I've amended the commit to ensure it is properly signed and passes the DCO check. The workflows are currently awaiting approval to run.

**Comment by Anujkumar9081** [comment]
@yurishkuro Hi! Could you please approve the pending workflows so the CI checks can run? All commits are signed and DCO is passing. Thank you!

File: internal/storage/v2/elasticsearch/tracestore/ids.go [hunk 2]
```diff
@@ -17,7 +18,12 @@ func convertTraceIDFromDB(dbTraceId dbmodel.TraceID) (pcommon.TraceID, error) {
 	if err != nil {
 		return pcommon.TraceID{}, err
 	}
-	copy(traceId[:], traceBytes)
+	if len(traceBytes) > 16 {
```
Comment (yurishkuro) [inline internal/storage/v2/elasticsearch/tracestore/ids.go]: you can required exactly len=16 and then not bother with partial copy below.

File: internal/storage/v2/elasticsearch/tracestore/from_dbmodel_test.go [hunk 3]
```diff
@@ -465,7 +465,7 @@ func TestFromDBModelErrors(t *testing.T) {
 				SpanID:       dbmodel.SpanID("0123456789abcdef"),
 				ParentSpanID: dbmodel.SpanID("invalid-parent-id"),
 			}},
-			err: "encoding/hex: invalid byte: U+0069 'i'",
+			err: "span ID from DB is too long",
```
Comment (yurishkuro) [inline internal/storage/v2/elasticsearch/tracestore/from_dbmodel_test.go]: This changes the meaning of the test

File: internal/storage/v2/elasticsearch/tracestore/ids.go [hunk 4]
```diff
@@ -13,7 +15,13 @@ import (
 
 func convertTraceIDFromDB(dbTraceId dbmodel.TraceID) (pcommon.TraceID, error) {
 	var traceId [16]byte
-	traceBytes, err := hex.DecodeString(string(dbTraceId))
+	traceIdHex := string(dbTraceId)
+	if len(traceIdHex) > 32 {
+		return pcommon.TraceID{}, fmt.Errorf("trace ID from DB is too long: %d chars", len(traceIdHex))
+	}
+	// Left-pad with zeros to 32 hex chars to handle shorter (e.g. 64-bit) trace IDs.
```
Comment (yurishkuro) [inline internal/storage/v2/elasticsearch/tracestore/ids.go:22]: Why do we need to support 64bit ids explicitly? Was there a code on the write path that would truncate ids from full length?

Comment (Anujkumar9081) [reply internal/storage/v2/elasticsearch/tracestore/ids.go:22]: Good question. The original issue (#8266) reports that Jaeger v1 stored 64-bit trace IDs (from Zipkin or older instrumentation) as 16-hex-char strings in Elasticsearch. When the v2 reader reads these shorter IDs, the original code left-aligned the decoded bytes in the 16-byte array, corrupting the trace ID. The left-padding approach ensures these legacy 64-bit IDs stored in ES are correctly right-aligned in the 128-bit pcommon.TraceID, matching how OpenTelemetry represents them.

File: internal/storage/v2/elasticsearch/tracestore/ids.go (hunk 2 above)
Comment (Anujkumar9081) [reply internal/storage/v2/elasticsearch/tracestore/ids.go]: Yes, that's exactly what the current approach does - after left-padding the hex string to 32 chars, hex.DecodeString always returns exactly 16 bytes, so the simple copy(traceId[:], traceBytes) works correctly without any offset math.

File: internal/storage/v2/elasticsearch/tracestore/from_dbmodel_test.go (hunk 3 above)
Comment (Anujkumar9081) [reply internal/storage/v2/elasticsearch/tracestore/from_dbmodel_test.go]: You're right, my apologies. The original test was checking for invalid hex characters, but invalid-parent-id (18 chars) was now triggering the length check instead. I've shortened the input to invalid-par (11 chars, within the 16-char limit) so it properly hits the hex decode error path and preserves the original test intent. Fixed in the latest push.

File: internal/storage/v2/elasticsearch/tracestore/ids.go [hunk 5]
```diff
@@ -13,7 +15,13 @@ import (
...
+	traceIdHex = strings.Repeat("0", 32-len(traceIdHex)) + traceIdHex
```
Comment (yurishkuro) [inline internal/storage/v2/elasticsearch/tracestore/ids.go]:
```suggestion
	if len(traceIdHex) < 32 {
		traceIdHex = strings.Repeat("0", 32-len(traceIdHex)) + traceIdHex
	}
```

Comment (Anujkumar9081) [reply internal/storage/v2/elasticsearch/tracestore/ids.go]: Thanks for catching this! I've applied the length check here. I also added the same check to fromDbSpanId just below it to be consistent and avoid unnecessary operations. Just pushed the update! :rocket:

File: internal/storage/v2/elasticsearch/tracestore/ids_test.go [hunk 6]
```diff
@@ -0,0 +1,114 @@
...
+package tracestore
+
+import (
+	"testing"
+
+	"github.com/stretchr/testify/assert"
+	"github.com/stretchr/testify/require"
+	"go.opentelemetry.io/collector/pdata/pcommon"
+
+	"github.com/jaegertracing/jaeger/internal/storage/elasticsearch/dbmodel"
```
Comment (yurishkuro) [inline internal/storage/v2/elasticsearch/tracestore/ids_test.go]:
```suggestion
	"github.com/jaegertracing/jaeger/internal/storage/v2/elasticsearch/tracestore/core/dbmodel"
```
