### PR TITLE
[fix][query] Fix misconfiguration in TLS settings from using OTEL HTTP helper

### LINKED ISSUE #6230: [Bug]: query: TLS handshake error
### What happened?

Using v1.63.0 on Windows.
When loading `https://localhost:16686/` in the browser
I get the error on the console where I run `jaeger-all-in-one.exe`

>  http: TLS handshake error from [::1]:55388: tls: first record does not look like a TLS handshake

I run with args:

> --query.additional-headers="Access-Control-Allow-Origin: *" --collector.otlp.enabled=true --collector.otlp.http.cors.allowed-origins="*" --collector.otlp.http.cors.allowed-headers="*" --collector.otlp.http.host-port=4318 --collector.otlp.http.tls.key=%TLS%\key.pem --collector.otlp.http.tls.cert=%TLS%\cert.pem --collector.otlp.http.tls.enabled=true --query.http.tls.enabled=true --query.http.tls.key=%TLS%\key.pem --query.http.tls.cert=%TLS%\cert.pem

This works with v1.62.0.

Maybe this is related to PR #6023 
I don't see an update to the CLI doc.

### Steps to reproduce

1. Run jaeger-all-in-one.exe on windows with args similar to above
2. Open UI at default port in browser
3. See described error in jaeger console

### Expected behavior

It should work as before - the UI should load but it remains empty.

### Relevant log output

```shell
http: TLS handshake error from [::1]:55388: tls: first record does not look like a TLS handshake
```

### Screenshot

_No response_

### Additional context

_No response_

### Jaeger backend version

v1.63.0

### SDK

_No response_

### Pipeline

_No response_

### Stogage backend

none (all-in-one)

### Operating system

Windows

### Deployment model

_No response_

### Deployment configs

```shell

```

### PR DESCRIPTION
**Pull request by mahadzaryab1**
## Which problem is this PR solving?
- Fixes #6230 

## Description of the changes
- This PR fixes an oversight that was made when migrating to OTEL's helpers for creating the HTTP server. OTEL's helper was adding TLS to the listener whereas we left the code to add TLS to the server. This was leading to the connection being in a weird state causing the bug in #6230. This PR simplifies the flow by doing the following:
  - We do not need to add TLS to the server because its added when the listener is initialized using `.ToListener()`
  - We do not need to call `ServeTLS` and can simply call `Serve` and TLS will be used when the connection is configured to do so (which it will be if the TLSSetting is set on the server). 

## How was this change tested?
Start the server by doing the following
```
go run ./cmd/all-in-one \
    --query.http.tls.enabled=true \
    --query.http.tls.cert=./pkg/config/tlscfg/testdata/example-server-cert.pem \
    --query.http.tls.key=./pkg/config/tlscfg/testdata/example-server-key.pem
```
Send request with HTTP1.1
```
curl -k --http1.1 https://localhost:16686/ > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4454    0  4454    0     0   393k      0 --:--:-- --:--:-- --:--:--  869k
```

Send request with HTTP2 (default)
```
curl -k --http2 https://localhost:16686/ > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4454    0  4454    0     0   140k      0 --:--:-- --:--:-- --:--:--  173k
```

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [ ] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

File: cmd/query/app/server_test.go [hunk 1]
```diff
@@ -117,12 +117,16 @@ func TestCreateTLSHttpServerError(t *testing.T) {
...
 		&QueryOptions{
 			HTTP: confighttp.ServerConfig{Endpoint: ":8080", TLSSetting: &tlsCfg},
 			GRPC: configgrpc.ServerConfig{NetAddr: confignet.AddrConfig{Endpoint: ":8081", Transport: confignet.TransportTypeTCP}},
 		}, tenancy.NewManager(&tenancy.Options{}), telset)
-	require.Error(t, err)
+	require.NoError(t, err)
+	require.Error(t, s.Start(context.Background()))
+	t.Cleanup(func() {
+		require.NoError(t, s.Close())
+	})
```
Comment (mahadzaryab1) [inline cmd/query/app/server_test.go:129]: this error will now be thrown at start when we initialize the listener rather than when we create the server

**Review by yurishkuro — APPROVED** [review]

File: cmd/query/app/server.go [hunk 2]
```diff
@@ -228,15 +228,6 @@ func createHTTPServer(
 		staticHandlerCloser: staticHandlerCloser,
 	}
 
-	// TODO why doesn't OTEL helper do that already?
```
Comment (yurishkuro) [inline cmd/query/app/server.go:231]: hehe, my intuition was right at the time :-)

**Comment by yurishkuro** [comment]
Thanks for fixing it!
