### PR TITLE
Fixed intermittent test

### LINKED ISSUE #1703: Intermittent test - TestSpanReader_multiRead_followUp_query
The test `TestSpanReader_multiRead_followUp_query` is intermittently failing. I spotted this for the PR #1668, which isn't touching any Go code at all.

```
--- FAIL: TestSpanReader_multiRead_followUp_query (0.00s)
    reader_test.go:279: 
        	Error Trace:	reader_test.go:279
        	            				reader_test.go:105
        	            				reader_test.go:209
        	Error:      	Not equal: 
        	            	expected: &model.Span{TraceID:model.TraceID{Low:0x2, High:0x0}, SpanID:0x0, OperationName:"", References:[]model.SpanRef{}, Flags:0x0, StartTime:time.Time{wall:0x3b93dc90, ext:63700183028, loc:(*time.Location)(nil)}, Duration:0, Tags:[]model.KeyValue{}, Logs:[]model.Log{}, Process:(*model.Process)(0xc000141770), ProcessID:"", Warnings:[]string(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
        	            	actual  : &model.Span{TraceID:model.TraceID{Low:0x1, High:0x0}, SpanID:0x0, OperationName:"", References:[]model.SpanRef{}, Flags:0x0, StartTime:time.Time{wall:0x3b93dc90, ext:63700183028, loc:(*time.Location)(nil)}, Duration:0, Tags:[]model.KeyValue{}, Logs:[]model.Log{}, Process:(*model.Process)(0xc0001417c0), ProcessID:"", Warnings:[]string(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
        	            	
        	            	Diff:
        	Test:       	TestSpanReader_multiRead_followUp_query
    reader_test.go:280: 
        	Error Trace:	reader_test.go:280
        	            				reader_test.go:105
        	            				reader_test.go:209
        	Error:      	Not equal: 
        	            	expected: &model.Span{TraceID:model.TraceID{Low:0x1, High:0x0}, SpanID:0x0, OperationName:"", References:[]model.SpanRef{}, Flags:0x0, StartTime:time.Time{wall:0x3b93dc90, ext:63700183028, loc:(*time.Location)(nil)}, Duration:0, Tags:[]model.KeyValue{}, Logs:[]model.Log{}, Process:(*model.Process)(0xc000141360), ProcessID:"", Warnings:[]string(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
        	            	actual  : &model.Span{TraceID:model.TraceID{Low:0x2, High:0x0}, SpanID:0x0, OperationName:"", References:[]model.SpanRef{}, Flags:0x0, StartTime:time.Time{wall:0x3b93dc90, ext:63700183028, loc:(*time.Location)(nil)}, Duration:0, Tags:[]model.KeyValue{}, Logs:[]model.Log{}, Process:(*model.Process)(0xc000141810), ProcessID:"", Warnings:[]string(nil), XXX_NoUnkeyedLiteral:struct {}{}, XXX_unrecognized:[]uint8(nil), XXX_sizecache:0}
        	            	
        	            	Diff:
        	Test:       	TestSpanReader_multiRead_followUp_query
```

### PR DESCRIPTION
**Pull request by jpkrohling**
Signed-off-by: Juraci Paixão Kröhling <juraci@kroehling.de>

## Which problem is this PR solving?
- Fixes #1703 by changing the way assertions are done for items within arrays

### CODE REVIEW

File: plugin/storage/es/spanstore/reader_test.go [hunk 1]
```diff
@@ -145,30 +145,30 @@ func TestSpanReaderIndices(t *testing.T) {
 	date := time.Now()
 	dateFormat := date.UTC().Format("2006-01-02")
 	testCases := []struct {
-		index string
-		params  SpanReaderParams
```
Comment (jpkrohling) [inline plugin/storage/es/spanstore/reader_test.go]: The formatting changes were made automatically by my editor and should match the other files in the project. Let me know if I should revert them.

Comment (pavolloffay) [reply plugin/storage/es/spanstore/reader_test.go]: cannot be the formatting verified during the build. There are probably other files which does not match setting in your editor.

I would prefer to keep only changes related to the subject.

File: plugin/storage/es/spanstore/reader_test.go [hunk 2]
```diff
@@ -276,8 +276,11 @@ func TestSpanReader_multiRead_followUp_query(t *testing.T) {
 		require.NoError(t, err)
 		sModel2, err := toDomain.SpanToDomain(&spanID2)
 		require.NoError(t, err)
-		assert.EqualValues(t, traces[0].Spans[0], sModel1)
-		assert.EqualValues(t, traces[1].Spans[0], sModel2)
+
+		for _, s := range []*model.Span{sModel1, sModel2} {
```
Comment (pavolloffay) [inline plugin/storage/es/spanstore/reader_test.go]: This seems fine, the result can be different because the function creates traces array from a map: https://github.com/jaegertracing/jaeger/blob/a14ca3c04ca89873d21a94c2849f0337c212cb1d/plugin/storage/es/spanstore/reader.go#L378

File: plugin/storage/es/spanstore/reader_test.go (hunk 1 above)
Comment (jpkrohling) [reply plugin/storage/es/spanstore/reader_test.go]: @objectiser also expressed that via IRC, and I'd normally undo such changes, but these ones do make sense to me. For instance, it would be expected that `index string` would be aligned wiht `params SpanReaderParams` and that was *not* the case before this PR. As this is a small PR, and the "after" state is better than the "before", I decided to leave the formatting changes there.

If it's still desirable to revert those changes, I can certainly do that.

Comment (yurishkuro) [reply plugin/storage/es/spanstore/reader_test.go]: that looks like a standard go fmt behavior, is it not running on this file during the build?  I remember we used to have an issue where lints were not running on all Go files.

Comment (yurishkuro) [reply plugin/storage/es/spanstore/reader_test.go]: Turns out we indeed were excluding test files from linting. Fix here: #1709. Once we merge that, this PR won't need formatting diffs

**Comment by jpkrohling** [comment]
PR updated, formatting changes are now gone as part of #1709
