### PR TITLE
Fix rebuild-ui.sh script

### LINKED ISSUE #6097: rebuild-ui is broken
```
$ make rebuild-ui
::group::rebuild-ui logs
bash ./scripts/rebuild-ui.sh
+ cd jaeger-ui
+ git fetch --all --unshallow --tags
fatal: --unshallow on a complete repository does not make sense
make: *** [rebuild-ui] Error 128
```

cc @andreasgerstmayr

### PR DESCRIPTION
**Pull request by andreasgerstmayr**
## Which problem is this PR solving?
- Resolves #6097

## Description of the changes
- run `git fetch --unshallow` only on shallow repos

## How was this change tested?
- 

## Checklist
- [X] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [X] I have signed all commits
- [ ] I have added unit tests for the new functionality
- [ ] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

File: scripts/rebuild-ui.sh [hunk 1]
```diff
@@ -7,7 +7,11 @@ set -euxf -o pipefail
 
 cd jaeger-ui
 
-git fetch --all --unshallow --tags
+git fetch --all --tags
+is_shallow_repo=$(git rev-parse --is-shallow-repository)
+if [[ "$is_shallow_repo" == "true" ]]; then
+    git fetch --unshallow
+fi
```
Comment (yurishkuro) [inline scripts/rebuild-ui.sh:14]: I think you want this in the reverse order
```suggestion
if [[ "$(git rev-parse --is-shallow-repository)" == "true" ]]; then
    git fetch --unshallow
fi
git fetch --all --tags
```

**Review by yurishkuro — APPROVED** [review]

**Comment by yurishkuro** [comment]
Thanks!
