### PR TITLE
Fix flaky client metrics test

### LINKED ISSUE #2108: Fix flaky test TestClientMetricsReporter_Expire
It seems to be touched in https://github.com/jaegertracing/jaeger/pull/2010

```
--- FAIL: TestClientMetricsReporter_Expire (0.01s)
    --- FAIL: TestClientMetricsReporter_Expire/iter0:gauge=1,log=new_client (0.01s)
        client_metrics_test.go:268: 
            	Error Trace:	client_metrics_test.go:268
            	Error:      	Not equal: 
            	            	expected: int(1)
            	            	actual  : int64(0)
            	Test:       	TestClientMetricsReporter_Expire/iter0:gauge=1,log=new_client
FAIL	github.com/jaegertracing/jaeger/cmd/agent/app/reporter	0.064s
```

### PR DESCRIPTION
**Pull request by yurishkuro**
Resolves #2108

Supersedes #2168

### CODE REVIEW

File: cmd/agent/app/reporter/client_metrics_test.go [hunk 1]
```diff
@@ -238,42 +240,46 @@ func TestClientMetricsReporter_Expire(t *testing.T) {
...
-				for i := 0; i < 10; i++ {
-					_, gauges := tr.mb.Snapshot()
-					gaugeValue = gauges["client_stats.connected_clients"]
-					if gaugeValue == int64(test.expGauge) {
-						break
-					}
-					time.Sleep(500 * time.Microsecond)
+
+		t.Run("detect new client", func(t *testing.T) {
+			assert.EqualValues(t, 0, getGauge(), "start with gauge=0")
```
Comment (vprithvi) [inline cmd/agent/app/reporter/client_metrics_test.go:249]: Why is this needed? What else could set the gauge to a non zero value earlier?

File: cmd/agent/app/reporter/client_metrics_test.go [hunk 2]
```diff
@@ -222,9 +223,10 @@ func TestClientMetricsReporter_ClientUUID(t *testing.T) {
 }
 
 func TestClientMetricsReporter_Expire(t *testing.T) {
+	const expireTTL = 50 * time.Millisecond
 	params := ClientMetricsReporterParams{
-		ExpireFrequency: 100 * time.Microsecond,
-		ExpireTTL:       5 * time.Millisecond,
+		ExpireFrequency: 1 * time.Millisecond,
```
Comment (vprithvi) [inline cmd/agent/app/reporter/client_metrics_test.go:228]: can simply be `time.Millisecond`

File: cmd/agent/app/reporter/client_metrics_test.go [hunk 3]
```diff
@@ -238,42 +240,46 @@ func TestClientMetricsReporter_Expire(t *testing.T) {
...
+					tr.assertLog(t, "new client", clientUUID)
+					return
 				}
-				assert.EqualValues(t, test.expGauge, gaugeValue)
-				tr.assertLog(t, test.expLog, clientUUID)
+			}
+			require.EqualValues(t, 1, gauge)
+		})
+
+		t.Run("detect stale client", func(t *testing.T) {
```
Comment (vprithvi) [inline cmd/agent/app/reporter/client_metrics_test.go:268]: Is it difficult to start with gauges at a specific value instead of relying on `EmitBatch`?

File: cmd/agent/app/reporter/client_metrics_test.go (hunk 1 above)
Comment (yurishkuro) [reply cmd/agent/app/reporter/client_metrics_test.go:249]: it's a sanity check

File: cmd/agent/app/reporter/client_metrics_test.go (hunk 3 above)
Comment (yurishkuro) [reply cmd/agent/app/reporter/client_metrics_test.go:268]: I am not sure, it would probably require some backdoor. This way we're testing cleanly via the official APIs.
