### PR TITLE
Query service: fix logging errors on SIGINT

### LINKED ISSUE #1542: Query and all-in-one generates error message on SIGINT
Jaeger 1.12.0 query/all-in-one generates 2 error messages on shutdown (SIGINT):

> {"level":"error","ts":1557924794.5416982,"caller":"app/server.go:127","msg":"Could not start multiplexed server","error":"accept tcp [::]:16686: use of closed network connection","stacktrace":"github.com/jaegertracing/jaeger/cmd/query/app.(*Server).Start.func3\n\t/home/ploffay/projects/golang/src/github.com/jaegertracing/jaeger/cmd/query/app/server.go:127"}

> {"level":"error","ts":1557924794.5418048,"caller":"app/server.go:109","msg":"Could not start HTTP server","error":"http: Server closed","stacktrace":"github.com/jaegertracing/jaeger/cmd/query/app.(*Server).Start.func1\n\t/home/ploffay/projects/golang/src/github.com/jaegertracing/jaeger/cmd/query/app/server.go:109"}

Those messages should not be there as it is a normal termination of the process.

Jaeger 1.11.0 output
```
{"level":"info","ts":1557923870.4618723,"caller":"healthcheck/handler.go:99","msg":"Health Check server started","http-port":14269,"status":"unavailable"}
{"level":"info","ts":1557923870.4620156,"caller":"memory/factory.go:55","msg":"Memory storage configuration","configuration":{"MaxTraces":0}}
{"level":"info","ts":1557923870.4621208,"caller":"static/strategy_store.go:79","msg":"No sampling strategies provided, using defaults"}
WARNING: 2019/05/15 14:37:50 grpc: addrConn.createTransport failed to connect to {127.0.0.1:14250 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:14250: connect: connection refused". Reconnecting...
{"level":"info","ts":1557923870.4652264,"caller":"all-in-one/main.go:211","msg":"Starting agent"}
{"level":"info","ts":1557923870.465499,"caller":"app/agent.go:68","msg":"Starting jaeger-agent HTTP server","http-port":5778}
{"level":"info","ts":1557923870.465974,"caller":"all-in-one/main.go:253","msg":"Starting jaeger-collector TChannel server","port":14267}
{"level":"info","ts":1557923870.466026,"caller":"grpcserver/grpc_server.go:64","msg":"Starting jaeger-collector gRPC server","grpc-port":"14250"}
{"level":"info","ts":1557923870.4660544,"caller":"all-in-one/main.go:271","msg":"Starting jaeger-collector HTTP server","http-port":14268}
{"level":"info","ts":1557923870.4660826,"caller":"all-in-one/main.go:399","msg":"Archive storage not created","reason":"Archive storage not supported"}
{"level":"info","ts":1557923870.4677374,"caller":"all-in-one/main.go:360","msg":"Registering metrics handler with jaeger-query HTTP server","route":"/metrics"}
{"level":"info","ts":1557923870.4677625,"caller":"all-in-one/main.go:366","msg":"Starting jaeger-query HTTP server","port":16686}
{"level":"info","ts":1557923870.4677749,"caller":"healthcheck/handler.go:133","msg":"Health Check state change","status":"ready"}
^C{"level":"info","ts":1557923873.034265,"caller":"all-in-one/main.go:149","msg":"Shutting down"}
{"level":"info","ts":1557923873.0343597,"caller":"all-in-one/main.go:157","msg":"Shutdown complete"}
```

Jaeger 1.12.0 output
```
{"level":"info","ts":1557924790.7362473,"caller":"flags/service.go:113","msg":"Mounting metrics handler on admin server","route":"/metrics"}
{"level":"info","ts":1557924790.7364206,"caller":"flags/admin.go:108","msg":"Mounting health check on admin server","route":"/"}
{"level":"info","ts":1557924790.7364788,"caller":"flags/admin.go:114","msg":"Starting admin HTTP server","http-port":14269}
{"level":"info","ts":1557924790.736494,"caller":"flags/admin.go:100","msg":"Admin server started","http-port":14269,"health-status":"unavailable"}
{"level":"info","ts":1557924790.7381833,"caller":"memory/factory.go:55","msg":"Memory storage initialized","configuration":{"MaxTraces":0}}
{"level":"info","ts":1557924790.7383587,"caller":"static/strategy_store.go:79","msg":"No sampling strategies provided, using defaults"}
{"level":"info","ts":1557924790.7411678,"caller":"grpc/builder.go:75","msg":"Agent requested insecure grpc connection to collector(s)"}
WARNING: 2019/05/15 14:53:10 grpc: addrConn.createTransport failed to connect to {127.0.0.1:14250 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:14250: connect: connection refused". Reconnecting...
{"level":"info","ts":1557924790.7417045,"caller":"all-in-one/main.go:195","msg":"Starting agent"}
{"level":"info","ts":1557924790.7418346,"caller":"app/agent.go:68","msg":"Starting jaeger-agent HTTP server","http-port":5778}
{"level":"info","ts":1557924790.742618,"caller":"all-in-one/main.go:238","msg":"Starting jaeger-collector TChannel server","port":14267}
{"level":"info","ts":1557924790.7426636,"caller":"grpcserver/grpc_server.go:64","msg":"Starting jaeger-collector gRPC server","grpc-port":"14250"}
{"level":"info","ts":1557924790.742699,"caller":"all-in-one/main.go:256","msg":"Starting jaeger-collector HTTP server","http-port":14268}
{"level":"info","ts":1557924790.7427151,"caller":"querysvc/query_service.go:130","msg":"Archive storage not created","reason":"archive storage not supported"}
{"level":"info","ts":1557924790.742728,"caller":"all-in-one/main.go:338","msg":"Archive storage not initialized"}
{"level":"info","ts":1557924790.7431312,"caller":"healthcheck/handler.go:129","msg":"Health Check state change","status":"ready"}
{"level":"info","ts":1557924790.743133,"caller":"app/server.go:107","msg":"Starting HTTP server","port":16686}
{"level":"info","ts":1557924790.7431507,"caller":"app/server.go:125","msg":"Starting CMUX server","port":16686}
{"level":"info","ts":1557924790.743178,"caller":"app/server.go:116","msg":"Starting GRPC server","port":16686}
^C{"level":"info","ts":1557924794.5406473,"caller":"flags/service.go:143","msg":"Shutting down"}
{"level":"info","ts":1557924794.5407808,"caller":"healthcheck/handler.go:129","msg":"Health Check state change","status":"unavailable"}
{"level":"error","ts":1557924794.5416982,"caller":"app/server.go:127","msg":"Could not start multiplexed server","error":"accept tcp [::]:16686: use of closed network connection","stacktrace":"github.com/jaegertracing/jaeger/cmd/query/app.(*Server).Start.func3\n\t/home/ploffay/projects/golang/src/github.com/jaegertracing/jaeger/cmd/query/app/server.go:127"}
{"level":"info","ts":1557924794.54186,"caller":"flags/service.go:151","msg":"Shutdown complete"}
{"level":"error","ts":1557924794.5418048,"caller":"app/server.go:109","msg":"Could not start HTTP server","error":"http: Server closed","stacktrace":"github.com/jaegertracing/jaeger/cmd/query/app.(*Server).Start.func1\n\t/home/ploffay/projects/golang/src/github.com/jaegertracing/jaeger/cmd/query/app/server.go:109"}
```

### PR DESCRIPTION
**Pull request by jan25**
Signed-off-by: Abhilash Gnan <abhilashgnan@gmail.com>

## Which problem is this PR solving?
- Resolves #1542

## Short description of the changes
- Query service servers return errors on SIGINT (when we call `Close()` on them). This PR handles such errors correctly and stops from logging

Previously merged PR: #1598 - I think, fixed the similar issue, but solving for SIGTERM. So it stopped from logging errors when i tested rebuilt query image inside a [all-in-one](https://github.com/jaegertracing/jaeger-kubernetes/blob/master/all-in-one/jaeger-all-in-one-template.yml) pod

### CODE REVIEW

File: cmd/flags/admin.go [hunk 1]
```diff
@@ -113,7 +113,8 @@ func (s *AdminServer) serveWithListener(l net.Listener) {
 	s.server = &http.Server{Handler: recoveryHandler(s.mux)}
 	s.logger.Info("Starting admin HTTP server", zap.Int("http-port", s.adminPort))
 	go func() {
-		if err := s.server.Serve(l); err != nil {
+		err := s.server.Serve(l)
+		if err != nil && err != http.ErrServerClosed {
```
Comment (yurishkuro) [inline cmd/flags/admin.go]: should we make it consistent with the other and use `case nil, http.ErrServerClosed, cmux.ErrListenerClosed:`?

File: cmd/query/app/server.go [hunk 2]
```diff
@@ -105,7 +106,10 @@ func (s *Server) Start() error {
 
 	go func() {
 		s.svc.Logger.Info("Starting HTTP server", zap.Int("port", s.queryOptions.Port))
-		if err := s.httpServer.Serve(httpListener); err != nil {
+
+		switch err := s.httpServer.Serve(httpListener); err {
+		case nil, http.ErrServerClosed, cmux.ErrListenerClosed:
+		default:
```
Comment (yurishkuro) [inline cmd/query/app/server.go]: make it more readable
```go
		switch err := s.httpServer.Serve(httpListener); err {
		case nil, http.ErrServerClosed, cmux.ErrListenerClosed:
                     // normal exit, nothing to do
                default:
```

File: cmd/query/app/server.go [hunk 3]
```diff
@@ -123,7 +127,9 @@ func (s *Server) Start() error {
 	// Start cmux server concurrently.
 	go func() {
 		s.svc.Logger.Info("Starting CMUX server", zap.Int("port", s.queryOptions.Port))
-		if err := cmuxServer.Serve(); err != nil {
+
+		err := cmuxServer.Serve()
+		if err != nil && !strings.Contains(err.Error(), "use of closed network connection") {
```
Comment (yurishkuro) [inline cmd/query/app/server.go]: strcmp is unfortunate. I see that cmux has ErrListenerClosed, at least (https://github.com/soheilhy/cmux/blob/master/cmux.go#L62). Is there no cleaner way to check for server closed? If not, maybe open a ticket w/ cmux?

File: cmd/flags/admin.go (hunk 1 above)
Comment (jan25) [reply cmd/flags/admin.go]: nice tip

File: cmd/query/app/server.go (hunk 3 above)
Comment (jan25) [reply cmd/query/app/server.go]: Agree with you :) There is no nice way to check for this currently, also cmux doesn't have nice way to close server. I opened this PR with cmux just now https://github.com/soheilhy/cmux/pull/69, this is still WIP. Until then, should be not fix this part? Or i could add a TODO about this cmux PR

File: cmd/query/app/server.go (hunk 2 above)
Comment (jan25) [reply cmd/query/app/server.go]: good idea, and done!

File: cmd/query/app/server.go (hunk 3 above)
Comment (jan25) [reply cmd/query/app/server.go]: Once that cmux PR is merged, the idea is to just call `cmux.Close()` and no such error checking needed

**Comment by jan25** [comment]
As a side note: When i just clicked "Merge master" in this PR the merge commit is not signed automatically, perhaps something to fix in the github workflow?

**Comment by yurishkuro** [comment]
it's the `Revert "add comments for readability"` commit that's not signed. Master merge is usually ok.

File: cmd/query/app/server.go (hunk 3 above)
Comment (yurishkuro) [reply cmd/query/app/server.go]: +1

Comment (yurishkuro) [reply cmd/query/app/server.go]: well, you'd still need to check the error to detect normal exit, because server.Close() could be called from the interrupt.

**Comment by jan25** [comment]
Added test to check for errors in logs on `server.Close()`

I may have messed up git history when trying to sign one of my commits i pushed earlier. Now DCO complains about author issue on a commit which came from merging master

File: cmd/query/app/server.go [hunk 4]
```diff
@@ -114,6 +119,7 @@ func (s *Server) Start() error {
 	// Start GRPC server concurrently
 	go func() {
 		s.svc.Logger.Info("Starting GRPC server", zap.Int("port", s.queryOptions.Port))
+
 		if err := s.grpcServer.Serve(grpcListener); err != nil {
```
Comment (yurishkuro) [inline cmd/query/app/server.go]: this is the same pattern as with the other two servers, but it works fine?

**Comment by yurishkuro** [comment]
you can try squashing the commits to have a single signed commit, or alter the commit message in the old commit via interactive rebase.

File: cmd/query/app/server.go (hunk 4 above)
Comment (jan25) [reply cmd/query/app/server.go]: Yes, grpc doesn't complain. I guess it has to do with how `grpc.Serve()` is implemented. Unlike with `http.Serve()`, grpc doesn't throw errors after `grpc.Stop()`

**Comment by pavolloffay** [comment]
@jan25 did you try to increase coverage?

**Comment by jan25** [comment]
Thanks for the review!

The additional test case tried to improve the coverage. I think codecov is talking about the `else` blocks which are written with `default:` which might've resulted in [tiny dip](https://codecov.io/gh/jaegertracing/jaeger/pull/1601/diff?src=pr&el=tree#diff-Y21kL3F1ZXJ5L2FwcC9zZXJ2ZXIuZ28=) in coverage, not entirely sure how codecov works. Please suggest if its possible to improve further
