### PR TITLE
[fix][spm]: Change default metrics namespace to match new default in spanmetricsconnector

### LINKED ISSUE #5982: SPM is broken by OTEL's new version
The PR #5968 is trying to upgrade to v0.109 and the SPM e2e test is consistently failing. It could be related to these breaking changes :

spanmetricsconnector: 
* Improve consistency between metrics generated by spanmetricsconnector. Added traces.span.metrics as default namespace ([#33227](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/33227), [#32818](https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/32818))
* Default namespace for the generated metrics is traces.span.metrics now. | The deprecated metrics are: calls, duration and events. | The feature flag connector.spanmetrics.legacyLatencyMetricNames was added to revert the behavior.

Tasks:
  * [ ] understand what changes in OTEL and how it affects SPM in Jaeger
  * [ ] make corresponding code changes to compensate
  * [ ] provide backwards compatibility following Jaeger's policy https://github.com/jaegertracing/jaeger?tab=readme-ov-file#version-compatibility-guarantees

### PR DESCRIPTION
**Pull request by mahadzaryab1**
## Which problem is this PR solving?
- Resolves #5982

## Description of the changes
- Make `traces_span_metrics` the new namespace default.
- Fixed the failing SPM integration test by setting the default namespace when querying from prometheus to `traces_span_metrics`. This matches the new default namespace in the `spanmetricsconnector` which was changed in `v0.109.0` (see https://github.com/f7o/opentelemetry-collector-contrib/commit/371bc59d4d5a10961782cc800771f266ba4c88df)
- This change is backwards compatible because it modifies the default. As a result, if anyone isn't using a custom namespace they will not be broken by these changes. 

## How was this change tested?
- CI

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [x] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

File: plugin/metrics/prometheus/options.go [hunk 1]
```diff
@@ -33,7 +33,7 @@ const (
 	defaultTokenFilePath  = ""
 
 	defaultSupportSpanmetricsConnector = true
-	defaultMetricNamespace             = ""
+	defaultMetricNamespace             = "traces_span_metrics"
```
Comment (mahadzaryab1) [inline plugin/metrics/prometheus/options.go:36]: @yurishkuro setting this default here seems to take care of the v2 test but the v1 test is still getting an empty response. do you have any idea why that could be? both v1 and v2 read this config.

Comment (mahadzaryab1) [reply plugin/metrics/prometheus/options.go:36]: this was actually not related to the changes in this PR and was failing due to missing http receiver endpoint in the otel collector config

File: plugin/metrics/prometheus/options.go [hunk 2]
```diff
@@ -32,11 +32,11 @@ const (
 	defaultConnectTimeout = 30 * time.Second
 	defaultTokenFilePath  = ""
 
-	defaultSupportSpanmetricsConnector = true
```
Comment (mahadzaryab1) [inline plugin/metrics/prometheus/options.go:35]: drive by change: this variable is not used anymore

File: docker-compose/monitor/docker-compose.yml [hunk 3]
```diff
@@ -9,8 +9,6 @@ services:
     environment:
       - METRICS_STORAGE_TYPE=prometheus
       - PROMETHEUS_SERVER_URL=http://prometheus:9090
-      - PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR=${PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR:-true}
```
Comment (mahadzaryab1) [inline docker-compose/monitor/docker-compose.yml:12]: drive by change: this configuration is not used anymore

File: docker-compose/monitor/docker-compose.yml [hunk 4]
```diff
@@ -9,8 +9,6 @@ services:
...
-      - PROMETHEUS_QUERY_NAMESPACE=${PROMETHEUS_QUERY_NAMESPACE:-}
```
[the remark this answers is not in the document]
Comment (mahadzaryab1) [reply docker-compose/monitor/docker-compose.yml:13]: @yurishkuro good point! I added this line back in. I don't believe we need to provide the default here however. If its unset then the default will be used. This can be seen by the integration tests passing which don't set this environment variable.

**Review by yurishkuro — APPROVED** [review]
Thanks for digging into this one!  🥳
