### PR TITLE
[fix][grpc] Disable tracing in grpc storage writer clients

### LINKED ISSUE #5971: [jaeger-v2] Dangerous use of tracer in plugin/storage/grpc/factory.go
The factory is passed a tracer that it then passes to OTEL's ToClientConn() function, which automatically adds tracing instrumentation to gRPC connection. That means we may start generating new traces as we're trying to save spans to storage, thus causing an infinite loop of trace generation. The write path must always be devoid of tracing (or use very low sampling rate) to avoid this.

Related upstream issue https://github.com/open-telemetry/opentelemetry-collector/issues/10663

### PR DESCRIPTION
**Pull request by mahadzaryab1**
## Which problem is this PR solving?
- Fixes #5971 
- Towards #6113 and #5859

## Description of the changes
- This PR fixes an issue where the GRPC remote storage client was provided a tracer which was resulting in an infinite loop of trace generation. This infinite loop would happen when we would try to write a trace to storage which would generate a new trace that needed to be written and so on. This PR provides a fix for this by using a noop tracer for the writer clients so that we do not generate traces on the write paths but still do so when reading. 
- This is likely just a temporary fix and we'll want to monitor https://github.com/open-telemetry/opentelemetry-collector/issues/10663 for a better long-term fix.

## How was this change tested?
- Added the healthcheck endpoint which was previously failing in #6113.

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [x] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

## Co-Authors 
This PR is a continuation of https://github.com/jaegertracing/jaeger/pull/5979
Co-authored-by: cx <1249843194@qq.com>

### CODE REVIEW

**Comment by mahadzaryab1** [comment]
@yurishkuro where would be a good place to write a test for this?

File: plugin/storage/grpc/factory.go [hunk 1]
```diff
@@ -42,13 +43,14 @@ var ( // interface comformance checks
...
-	config         Config
-	services       *ClientPluginServices
-	remoteConn     *grpc.ClientConn
-	host           component.Host
+	metricsFactory      metrics.Factory
+	logger              *zap.Logger
+	tracerProvider      trace.TracerProvider
+	config              Config
+	services            *ClientPluginServices
+	remoteConn          *grpc.ClientConn
```
Comment (yurishkuro) [inline plugin/storage/grpc/factory.go:51]: I'd recommend more symmetrical names: tracedRemoteConn and untracedRemoteConn. Same pattern for other pairs like telset and opts.

File: plugin/storage/grpc/factory.go [hunk 2]
```diff
@@ -208,5 +215,19 @@ func (f *Factory) Close() error {
...
+		errs = append(errs, f.noTracingRemoteConn.Close())
+	}
 	return errors.Join(errs...)
 }
+
+func getTelset(logger *zap.Logger, tracerProvider trace.TracerProvider) component.TelemetrySettings {
+	return component.TelemetrySettings{
+		Logger:         logger,
+		TracerProvider: tracerProvider,
+		// TODO needs to be joined with the metricsFactory
```
Comment (yurishkuro) [inline plugin/storage/grpc/factory.go:228]: We should book a ticket for v2 board. I'm thinking the internal telset struct should expose both internal metrics factory and otel meter provider, for cases where the latter is needed.

**Review by yurishkuro — COMMENTED** [review]
If this closes any other tickets or prs please include in description. 

Also give credit to the original author. Did you reuse any of their commits? When you go GitHub automatically includes them in the PR summary.

**Comment by mahadzaryab1** [comment]
> If this closes any other tickets or prs please include in description.

Done 

> Also give credit to the original author. Did you reuse any of their commits? When you go GitHub automatically includes them in the PR summary.

I didn't reuse any of their commits since I didn't have permissions to modify the PR. I manually edited the PR description to add the original author as a co-author for this PR.

File: plugin/storage/grpc/factory.go (hunk 2 above)
Comment (mahadzaryab1) [reply plugin/storage/grpc/factory.go:228]: @yurishkuro would you be able to elaborate on why we want to expose the meter provider in `telemetry.Setting`. This factory currently just takes in the `metrics.Factory`. Would we want to refactor it to take the whole setting struct?

**Comment by yurishkuro** [comment]
> didn't reuse any of their commits since I didn't have permissions to modify the PR

For the future - you don't need to modify their pr, just do 'gh pr checkout ###' then create a new branch and push it to a new pr.

File: plugin/storage/grpc/factory.go [hunk 3]
```diff
@@ -205,8 +212,22 @@ func (f *Factory) CreateArchiveSpanWriter() (spanstore.Writer, error) {
...
+		LeveledMeterProvider: func(_ configtelemetry.Level) metric.MeterProvider {
+			return noopmetric.NewMeterProvider()
```
Comment (yurishkuro) [inline plugin/storage/grpc/factory.go:230]: As you can see below we're passing noop provider, that's not good. But we also cannot make up a new provider here, it should be passed down from OTEL framework, and it makes sense to pass it down in our telset struct.

Comment (mahadzaryab1) [reply plugin/storage/grpc/factory.go:230]: Sounds good! Added https://github.com/jaegertracing/jaeger/issues/6127

File: plugin/storage/grpc/factory.go [hunk 4]
```diff
@@ -108,40 +104,51 @@ func (f *Factory) Initialize(metricsFactory metrics.Factory, logger *zap.Logger)
...
-		opts = append(opts, grpc.WithStreamInterceptor(tenancy.NewClientStreamInterceptor(tenancyMgr)))
+		baseOpts = append(baseOpts, grpc.WithUnaryInterceptor(tenancy.NewClientUnaryInterceptor(tenancyMgr)))
+		baseOpts = append(baseOpts, grpc.WithStreamInterceptor(tenancy.NewClientStreamInterceptor(tenancyMgr)))
 	}
 
-	opts = append(opts, grpc.WithUnaryInterceptor(bearertoken.NewUnaryClientInterceptor()))
-	opts = append(opts, grpc.WithStreamInterceptor(bearertoken.NewStreamClientInterceptor()))
-
-	remoteConn, err := newClient(opts...)
+	baseOpts = append(baseOpts, grpc.WithUnaryInterceptor(bearertoken.NewUnaryClientInterceptor()))
```
[the remark this answers is not in the document]
Comment (mahadzaryab1) [reply plugin/storage/grpc/factory.go:133]: @yurishkuro looks like `grpc.NewClient` chains the interceptors into one (ref: https://github.com/grpc/grpc-go/blob/cb329375b14e0ddd4e454e18405a732f7c2ccd72/clientconn.go#L170-L171)
```
	chainUnaryClientInterceptors(cc)
	chainStreamClientInterceptors(cc)
```

[the remark this answers is not in the document]
Comment (yurishkuro) [reply plugin/storage/grpc/factory.go:133]: Not sure about that, but the way the functional options are processed is they just override the only interceptor slot: https://github.com/grpc/grpc-go/blob/cb329375b14e0ddd4e454e18405a732f7c2ccd72/dialoptions.go#L535

File: plugin/storage/grpc/factory.go [hunk 5]
```diff
@@ -108,40 +104,56 @@ func (f *Factory) Initialize(metricsFactory metrics.Factory, logger *zap.Logger)
...
+		baseOpts = append(baseOpts, grpc.WithUnaryInterceptor(tenancy.NewClientUnaryInterceptor(tenancyMgr)))
+		baseOpts = append(baseOpts, grpc.WithStreamInterceptor(tenancy.NewClientStreamInterceptor(tenancyMgr)))
 	}
 
-	opts = append(opts, grpc.WithUnaryInterceptor(bearertoken.NewUnaryClientInterceptor()))
-	opts = append(opts, grpc.WithStreamInterceptor(bearertoken.NewStreamClientInterceptor()))
+	baseOpts = append(baseOpts, grpc.WithUnaryInterceptor(bearertoken.NewUnaryClientInterceptor()))
+	baseOpts = append(baseOpts, grpc.WithStreamInterceptor(bearertoken.NewStreamClientInterceptor()))
+	opts := make([]grpc.DialOption, len(baseOpts))
+	copy(opts, baseOpts)
```
Comment (yurishkuro) [inline plugin/storage/grpc/factory.go:136]:
```suggestion
	opts := append([]grpc.DialOption{}, baseOpts...)
```

File: plugin/storage/grpc/shared/grpc_client.go [hunk 6]
```diff
@@ -46,15 +46,15 @@ type GRPCClient struct {
 	streamWriterClient  storage_v1.StreamingSpanWriterPluginClient
 }
 
-func NewGRPCClient(c *grpc.ClientConn) *GRPCClient {
+func NewGRPCClient(c *grpc.ClientConn, noTracingConn *grpc.ClientConn) *GRPCClient {
```
Comment (yurishkuro) [inline plugin/storage/grpc/shared/grpc_client.go:49]:
```suggestion
func NewGRPCClient(tracedConn *grpc.ClientConn, untracedConn *grpc.ClientConn) *GRPCClient {
```

File: plugin/storage/grpc/factory.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (mahadzaryab1) [reply plugin/storage/grpc/factory.go]: chained the unary and stream interceptors together

**Review by yurishkuro — APPROVED** [review]
