### PR TITLE
[query] Avoid errors when closing shared listener

### LINKED ISSUE #5519: Flaky unit test TestServerSinglePort
This test failed several times recently:
```
--- FAIL: TestServerSinglePort (10.01s)
    logger.go:146: 2024-06-03T15:06:55.394Z	INFO	Using UI configuration	{"path": ""}
    logger.go:146: 2024-06-03T15:06:55.394Z	INFO	Query server started	{"port": 16686, "addr": ":16686"}
    logger.go:146: 2024-06-03T15:06:55.395Z	INFO	Starting GRPC server	{"port": 16686, "addr": ":16686"}
    logger.go:146: 2024-06-03T15:06:55.395Z	INFO	Starting HTTP server	{"port": 16686, "addr": ":16686"}
    logger.go:146: 2024-06-03T15:06:55.395Z	INFO	Starting CMUX server	{"port": 16686, "addr": ":16686"}
    logger.go:146: 2024-06-03T15:07:05.399Z	INFO	GRPC server stopped	{"port": 16686, "addr": ":16686"}
    logger.go:146: 2024-06-03T15:07:05.399Z	INFO	HTTP server stopped	{"port": 16686, "addr": ":16686"}
    server_test.go:622: 
        	Error Trace:	/home/runner/work/jaeger/jaeger/cmd/query/app/server_test.go:622
        	            				/opt/hostedtoolcache/go/1.22.3/x64/src/testing/testing.go:[117](https://github.com/jaegertracing/jaeger/actions/runs/9352539113/job/25740954249#step:8:118)5
        	            				/opt/hostedtoolcache/go/1.22.3/x64/src/testing/testing.go:1353
        	            				/opt/hostedtoolcache/go/1.22.3/x64/src/testing/testing.go:1683
        	Error:      	Received unexpected error:
        	            	close tcp [::]:16686: use of closed network connection
        	Test:       	TestServerSinglePort
FAIL
coverage: 27.8% of statements
FAIL	github.com/jaegertracing/jaeger/cmd/query/app	[121](https://github.com/jaegertracing/jaeger/actions/runs/9352539113/job/25740954249#step:8:122).373s
```

Looks like we have some kind of race condition in closing the connection more than once. When we use cmux, the listener is not owned by the http/grpc servers, but they probably each try to close it.

### PR DESCRIPTION
**Pull request by vermaaatul07**
## Description
This PR aims to address the intermittent timeout issue in the `TestServerSinglePort` test by adding enhanced logging to the `Start` and `Close` methods of the server. These additional logs provide better visibility into the server's behavior during the test, which should help in diagnosing the root cause of the issue.

### Enhanced Logging:
- Added error logging in the `Start` method for listener initialization failures.
- Added info logging in the `Start` method to log the initialized HTTP and gRPC ports.
- Added info logging in the `Close` method to indicate an attempt to close the server and confirm when the server has stopped.

These changes provide better diagnostics and insights into server operations, which should help in identifying and resolving the flaky test issue if it occurs again.

## Related Issue
Closes #5519

## Checklist
- [x] I have read `CONTRIBUTING_GUIDELINES`
- [x] I have signed all commits
- [ ] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

File: cmd/query/app/server.go [hunk 1]
```diff
@@ -49,6 +49,9 @@ import (
 
 // Server runs HTTP, Mux and a grpc server
 type Server struct {
+	mu           sync.Mutex
+	started      bool
+	stopChan     chan struct{}
```
Comment (yurishkuro) [inline cmd/query/app/server.go:54]: Why do we need any of these? If you suspect that Close is being called twice from the test we can just add a log message. But there's no evidence it was called twice. And the channel is never read at all.

File: cmd/query/app/server.go [hunk 2]
```diff
@@ -346,6 +356,16 @@ func (s *Server) Start() error {
...
 func (s *Server) Close() error {
+	s.mu.Lock()
+	defer s.mu.Unlock()
+	if !s.started {
+		return nil
+	}
+	s.started = false
+
+	s.logger.Info("Stopping server")
+	close(s.stopChan)
```
Comment (yurishkuro) [inline cmd/query/app/server.go:367]: Nobody reads this channel

File: cmd/query/app/server_test.go [hunk 3]
```diff
@@ -602,12 +602,11 @@ func TestServerInUseHostPort(t *testing.T) {
...
 	flagsSvc := flags.NewService(ports.QueryAdminHTTP)
 	flagsSvc.Logger = zaptest.NewLogger(t)
-	hostPort := ports.GetAddressFromCLIOptions(ports.QueryHTTP, "")
 	querySvc := makeQuerySvc()
 	server, err := NewServer(flagsSvc.Logger, flagsSvc.HC(), querySvc.qs, nil,
 		&QueryOptions{
-			GRPCHostPort: hostPort,
-			HTTPHostPort: hostPort,
+			GRPCHostPort: ":0",
+			HTTPHostPort: ":0",
```
Comment (yurishkuro) [inline cmd/query/app/server_test.go:609]: This will make the servers run on different random ports, would it not? It would invalidate the test.

Comment (vermaaatul07) [reply cmd/query/app/server_test.go]: Thank you for pointing that out. You're right; changing the ports to "0" will cause the servers to run on different random ports, which could invalidate the test. I will revise the code to ensure that the servers run on the same port as intended.

File: cmd/query/app/server.go (hunk 2 above)
Comment (vermaaatul07) [reply cmd/query/app/server.go]: I appreciate the feedback. Perhaps logging directly after the close operation would be more effective.

File: cmd/query/app/server.go (hunk 1 above)
Comment (vermaaatul07) [reply cmd/query/app/server.go]: Thank you for the insights. The additional fields were intended to prevent redundant close operations, but I understand that there's no current evidence of the Close method being called twice. I'll simplify the code by removing the `stopChan` and focus on logging to diagnose the issue more clearly.

File: cmd/query/app/server.go [hunk 4]
```diff
@@ -274,10 +274,14 @@ func (s *Server) initListener() (cmux.CMux, error) {
 func (s *Server) Start() error {
 	cmuxServer, err := s.initListener()
 	if err != nil {
+		s.logger.Error("Failed to initialize listener", zap.Error(err))
 		return err
```
Comment (yurishkuro) [inline cmd/query/app/server.go:278]: there is no need to log, just wrap the error
```suggestion
		return fmt.Errorf("query server failed to initialize listener: %w", err)
```

File: cmd/query/app/server.go [hunk 5]
```diff
@@ -346,6 +350,7 @@ func (s *Server) Start() error {
 
 // Close stops http, GRPC servers and closes the port listener.
 func (s *Server) Close() error {
+	s.logger.Info("Attempting to close server")
```
Comment (yurishkuro) [inline cmd/query/app/server.go:353]: considering the original error, this log is useless, because the race condition was between closing grpc/gttp/cmux servers, so I would log when those are closed (if possible from their own Close methods if we implement then, but they come from 3rd party library then the best we can do is log just before calling each Close)

File: cmd/query/app/server_test.go [hunk 6]
```diff
@@ -625,7 +625,6 @@ func TestServerSinglePort(t *testing.T) {
 		require.NoError(t, client.conn.Close())
 	})
 
-	// using generous timeout since grpc.NewClient no longer does a handshake.
```
Comment (yurishkuro) [inline cmd/query/app/server_test.go:628]: why remove the commend?

File: cmd/query/app/server.go [hunk 7]
```diff
@@ -272,12 +272,18 @@ func (s *Server) initListener() (cmux.CMux, error) {
 
 // Start http, GRPC and cmux servers concurrently
 func (s *Server) Start() error {
+	if s.logger == nil {
+		return errors.New("logger not initialized")
+	}
```
Comment (yurishkuro) [inline cmd/query/app/server.go:277]:
```suggestion
```

File: cmd/query/app/server.go [hunk 8]
```diff
@@ -347,13 +353,31 @@ func (s *Server) Start() error {
 // Close stops http, GRPC servers and closes the port listener.
 func (s *Server) Close() error {
 	var errs []error
+
+	// Log and close TLS gRPC server
```
Comment (yurishkuro) [inline cmd/query/app/server.go:357]: comment is redundant (and invalid, we're not closing the server itself, but a TLS config watcher)

File: cmd/query/app/server.go [hunk 9]
```diff
@@ -347,13 +353,31 @@ func (s *Server) Start() error {
...
+	s.logger.Info("Closing TLS gRPC server")
```
Comment (yurishkuro) [inline cmd/query/app/server.go:358]:
```suggestion
```

File: cmd/query/app/server.go [hunk 10]
```diff
@@ -347,13 +353,31 @@ func (s *Server) Start() error {
...
 	errs = append(errs, s.queryOptions.TLSGRPC.Close())
+
+	// Log and close TLS HTTP server
+	s.logger.Info("Closing TLS HTTP server")
```
Comment (yurishkuro) [inline cmd/query/app/server.go:362]:
```suggestion
```

File: cmd/query/app/server.go [hunk 11]
```diff
@@ -347,13 +353,31 @@ func (s *Server) Start() error {
...
+	// Stop gRPC server
+	s.logger.Info("Stopping gRPC server")
 	s.grpcServer.Stop()
+
+	// Log and close HTTP server
+	s.logger.Info("Closing HTTP server")
 	errs = append(errs, s.httpServer.Close())
+
 	if !s.separatePorts {
+		// Log and close CMux server
```
Comment (yurishkuro) [inline cmd/query/app/server.go:374]:
```suggestion
```

File: cmd/query/app/server.go [hunk 12]
```diff
@@ -274,10 +274,13 @@ func (s *Server) initListener() (cmux.CMux, error) {
 func (s *Server) Start() error {
 	cmuxServer, err := s.initListener()
 	if err != nil {
-		return err
+		return fmt.Errorf("query server failed to initialize listener: %w", err)
 	}
 	s.cmuxServer = cmuxServer
 
+	// Logging for ports
+	s.logger.Info("Initialized listener", zap.String("HTTP", s.queryOptions.HTTPHostPort), zap.String("gRPC", s.queryOptions.GRPCHostPort))
```
Comment (yurishkuro) [inline cmd/query/app/server.go:282]: is there a value in this log? From the ticket description, the ports are already logged
```
    logger.go:146: 2024-06-03T15:06:55.395Z	INFO	Starting GRPC server	{"port": 16686, "addr": ":16686"}
    logger.go:146: 2024-06-03T15:06:55.395Z	INFO	Starting HTTP server	{"port": 16686, "addr": ":16686"}
    logger.go:146: 2024-06-03T15:06:55.395Z	INFO	Starting CMUX server	{"port": 16686, "addr": ":16686"}
    logger.go:146: 2024-06-03T15:07:05.399Z	INFO	GRPC server stopped	{"port": 16686, "addr": ":16686"}
```

File: cmd/query/app/server.go [hunk 13]
```diff
@@ -349,11 +352,22 @@ func (s *Server) Close() error {
 	var errs []error
 	errs = append(errs, s.queryOptions.TLSGRPC.Close())
 	errs = append(errs, s.queryOptions.TLSHTTP.Close())
+
+	// Stop gRPC server
```
Comment (yurishkuro) [inline cmd/query/app/server.go:356]: this comment adds 0 new information
```suggestion
```

File: cmd/query/app/server.go [hunk 14]
```diff
@@ -349,11 +352,22 @@ func (s *Server) Close() error {
...
+	s.logger.Info("Stopping gRPC server")
 	s.grpcServer.Stop()
+
+	// Log and close HTTP server
```
Comment (yurishkuro) [inline cmd/query/app/server.go:360]:
```suggestion
```

File: cmd/query/app/server.go [hunk 15]
```diff
@@ -349,11 +352,22 @@ func (s *Server) Close() error {
...
+	s.logger.Info("Closing HTTP server")
 	errs = append(errs, s.httpServer.Close())
```
Comment (yurishkuro) [inline cmd/query/app/server.go:362]: if feels to me that here is the actual issue. When we're running on a single port with cmux, we create a single Listener. But the way at least HTTP server works is when you pass it a listener it assumes it owns it and will close it when stopping the server. Since we have several servers they probably all try to close the listener, but in random order due to goroutine scheduling. I suspect if we add sleeps in this function after each call to Close (and maybe change the order of closing servers) then we might be able to reproduce the error in the failed test. 

If my assumption is correct, I still don't know how to actually fix the issue, since we don't control how servers deal with Listener. One thing we could do is to explicitly check for "conn already closed" error and not return it (but only when running on a single port).

File: cmd/query/app/server.go (hunk 12 above)
Comment (vermaaatul07) [reply cmd/query/app/server.go:282]: I will remove this redundant log statement to avoid unnecessary duplication.

File: cmd/query/app/server.go (hunk 13 above)
Comment (vermaaatul07) [reply cmd/query/app/server.go:356]: Sorry , mb i will remove it to keep the code clean

File: cmd/query/app/server.go [hunk 16]
```diff
@@ -344,16 +344,42 @@ func (s *Server) Start() error {
...
+
+	if err := s.queryOptions.TLSGRPC.Close(); err != nil && !isConnAlreadyClosedError(err) {
+		errs = append(errs, fmt.Errorf("failed to close TLS gRPC server: %w", err))
+	}
+	time.Sleep(200 * time.Millisecond)
+
+	if err := s.queryOptions.TLSHTTP.Close(); err != nil && !isConnAlreadyClosedError(err) {
+		errs = append(errs, fmt.Errorf("failed to close TLS HTTP server: %w", err))
+	}
+	time.Sleep(200 * time.Millisecond)
```
Comment (yurishkuro) [inline cmd/query/app/server.go:359]: none of this is necessary. I already explained that TLSxxx.Close has nothing to do with servers or with the error in question, it just stops the file watchers.

File: cmd/query/app/server.go [hunk 17]
```diff
@@ -274,7 +274,7 @@ func (s *Server) initListener() (cmux.CMux, error) {
 func (s *Server) Start() error {
```
Comment (yurishkuro) [inline cmd/query/app/server.go:274]: you should add this option to the logger in the test:
```
	flagsSvc.Logger = zaptest.NewLogger(t, zaptest.WrapOptions(zap.AddCaller()))
```
that way it prints the source line.

I changed the timeout to 2s and look what the logs say:
```
    logger.go:146: 2024-06-12T15:13:20.232-0400 INFO    app/static_handler.go:109       Using UI configuration  {"path": ""}
    logger.go:146: 2024-06-12T15:13:20.234-0400 INFO    app/server.go:256       Query server started    {"port": 16686, "addr": ":16686"}
    logger.go:146: 2024-06-12T15:13:20.234-0400 INFO    app/server.go:300       Starting HTTP server    {"port": 16686, "addr": ":16686"}
    logger.go:146: 2024-06-12T15:13:20.234-0400 INFO    app/server.go:332       Starting CMUX server    {"port": 16686, "addr": ":16686"}
    logger.go:146: 2024-06-12T15:13:20.234-0400 INFO    app/server.go:318       Starting GRPC server    {"port": 16686, "addr": ":16686"}
    logger.go:146: 2024-06-12T15:13:20.283-0400 INFO    app/server.go:358       Stopping gRPC server
    logger.go:146: 2024-06-12T15:13:20.284-0400 INFO    app/server.go:310       HTTP server stopped     {"port": 16686, "addr": ":16686"}
    logger.go:146: 2024-06-12T15:13:20.284-0400 INFO    app/server.go:323       GRPC server stopped     {"port": 16686, "addr": ":16686"}
    logger.go:146: 2024-06-12T15:13:22.285-0400 INFO    app/server.go:362       Closing HTTP server
    logger.go:146: 2024-06-12T15:13:24.286-0400 INFO    app/server.go:369       Closing CMux server
    logger.go:146: 2024-06-12T15:13:24.286-0400 INFO    app/server.go:375       Server stopped
```
note that after `Stopping gRPC server` we're seeing `HTTP server stopped`, even before `Closing HTTP server`.  When I add a log line for CMUX server goroutine, it also logs that CMUX server is stopped before we come to trying to stop HTTP. So it seems when we're running on a single port it's simply sufficient to close gRPC server, which closes the underlying listenter, and all other servers exit automatically (we do already catch `ErrServerClosed` errors and don't log them).

File: cmd/query/app/server.go (hunk 16 above)
Comment (vermaaatul07) [reply cmd/query/app/server.go:359]: Sorry for the confusion. I was just trying to be extra cautious in ensuring all resources were being closed properly. Based on your feedback, I've removed the unnecessary `TLSGRPC.Close()` and `TLSHTTP.Close()` operations.

**Comment by yurishkuro** [comment]
I pushed a fix.

**Review by yurishkuro — APPROVED** [review]

**Comment by yurishkuro** [comment]
not sure if it will fix the issue, but at least it provides additional logging should it happen again.

**Comment by vermaaatul07** [comment]
> not sure if it will fix the issue, but at least it provides additional logging should it happen again.

 I will keep this issue in mind and will revisit it once I gain more understanding of how to resolve it. Thank you so much for your help and guidance.
