### PR TITLE
[Fix] Fix prometheus label value is not valid utf 8 cause api timeout

### LINKED ISSUE #2944: Prometheus 'Label value is not valid UTF-8' cause API timeout
**Describe the bug**
Prometheus 'Label value is not valid UTF-8' cause API request timeout.

**To Reproduce**
1. docker run -d -e COLLECTOR_ZIPKIN_HOST_PORT=:9411   -p 5775:5775/udp   -p 6831:6831/udp   -p 6832:6832/udp   -p 5778:5778   -p 16686:16686   -p 14268:14268   -p 14250:14250   -p 9411:9411   jaegertracing/all-in-one:1.22
2. curl http://localhost:9411/%C0%AE%C0%AE
3. Then all the other requests to http://localhost:9411/ will be timeout.

log:
```
2021/04/18 06:51:16 http: panic serving 172.17.0.1:33336: label value "/\xc0\xae\xc0\xae" is not valid UTF-8
goroutine 195 [running]:
net/http.(*conn).serve.func1(0xc000489f40)
	net/http/server.go:1801 +0x147
panic(0x1392360, 0xc0002c3630)
	runtime/panic.go:975 +0x47a
github.com/prometheus/client_golang/prometheus.(*HistogramVec).WithLabelValues(0xc0004fc500, 0xc000575770, 0x3, 0x3, 0xc000575650, 0xc000575770)
	github.com/prometheus/client_golang@v1.5.1/prometheus/histogram.go:489 +0xda
github.com/uber/jaeger-lib/metrics/prometheus.(*Factory).Timer(0xc0000edc20, 0x15b70ed, 0x15, 0xc000575620, 0x15bbfcd, 0x19, 0x0, 0x0, 0x0, 0x1512b80, ...)
	github.com/uber/jaeger-lib@v2.4.0+incompatible/metrics/prometheus/factory.go:181 +0x2ce
github.com/uber/jaeger-lib/metrics/fork.(*Factory).Timer(0xc0003fe870, 0x15b70ed, 0x15, 0xc000575620, 0x15bbfcd, 0x19, 0x0, 0x0, 0x0, 0xc0006799f5, ...)
	github.com/uber/jaeger-lib@v2.4.0+incompatible/metrics/fork/fork.go:48 +0x65
github.com/jaegertracing/jaeger/pkg/httpmetrics.buildTimer(...)
	github.com/jaegertracing/jaeger/pkg/httpmetrics/metrics.go:111
github.com/jaegertracing/jaeger/pkg/httpmetrics.(*requestDurations).record(0xc00056c090, 0xc0000bbc80, 0x3, 0xc00057a858, 0x5, 0xc00057a940, 0x3, 0x10578)
	github.com/jaegertracing/jaeger/pkg/httpmetrics/metrics.go:101 +0x465
github.com/jaegertracing/jaeger/pkg/httpmetrics.Wrap.func1(0x1e1c2c0, 0xc000158380, 0xc00014ea00)
	github.com/jaegertracing/jaeger/pkg/httpmetrics/metrics.go:63 +0x1fe
net/http.HandlerFunc.ServeHTTP(0xc00050de60, 0x1e1c2c0, 0xc000158380, 0xc00014ea00)
	net/http/server.go:2042 +0x44
github.com/rs/cors.(*Cors).Handler.func1(0x1e1c2c0, 0xc000158380, 0xc00014ea00)
	github.com/rs/cors@v1.7.0/cors.go:219 +0x1b9
net/http.HandlerFunc.ServeHTTP(0xc00050de80, 0x1e1c2c0, 0xc000158380, 0xc00014ea00)
	net/http/server.go:2042 +0x44
net/http.serverHandler.ServeHTTP(0xc0000d0380, 0x1e1c2c0, 0xc000158380, 0xc00014ea00)
	net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc000489f40, 0x1e225c0, 0xc00025a400)
	net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	net/http/server.go:2969 +0x36c
```

**Expected behavior**
 Other requests not timeout.

**Screenshots**
null

**Version (please complete the following information):**
 - OS: MacOS & Linux
 - Jaeger version: 1.22
 - Deployment: Docker

**What troubleshooting steps did you try?**
The error is reported by Prometheus, so I add `-e METRICS_BACKEND=expvar` to disable Prometheus.

**Additional context**
null

### PR DESCRIPTION
**Pull request by iypetrov**
## Which problem is this PR solving?
- Example: Resolves #2944

## Description of the changes
- Use `hist.GetMetricWithLabelValues` instead of `hist.WithLabelValues` to avoid the panic 'Label value is not valid UTF-8' and receive instead of that empty counter/gauge/timer/histogram.

## How was this change tested?
- Four new tests were added to ensure the system remains stable when it receives an invalid label.

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [x] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `npm run lint` and `npm run test`

### CODE REVIEW

File: internal/metrics/prometheus/factory.go [hunk 1]
```diff
@@ -129,8 +141,19 @@ func (f *Factory) Counter(options metrics.Options) metrics.Counter {
 		Help: help,
 	}
 	cv := f.cache.getOrMakeCounterVec(opts, labelNames)
+	labelValues := f.tagsAsLabelValues(labelNames, tags)
+	metric, err := cv.GetMetricWithLabelValues(labelValues...)
+	if err != nil {
+		f.logger.Warn(
```
Comment (yurishkuro) [inline internal/metrics/prometheus/factory.go:147]: logger can be nil here, you're not validating it

Comment (iypetrov) [reply internal/metrics/prometheus/factory.go]: a new nil check is added for each usage of f.logger

File: internal/metrics/prometheus/factory.go [hunk 2]
```diff
@@ -129,8 +141,21 @@ func (f *Factory) Counter(options metrics.Options) metrics.Counter {
 		Help: help,
 	}
 	cv := f.cache.getOrMakeCounterVec(opts, labelNames)
+	labelValues := f.tagsAsLabelValues(labelNames, tags)
+	metric, err := cv.GetMetricWithLabelValues(labelValues...)
+	if err != nil {
+		if f.logger != nil {
```
Comment (yurishkuro) [inline internal/metrics/prometheus/factory.go:147]: this is a bad idea. The common practice is to require that a non-nil logger is provided when constructing the object (e.g. by logging something in the constructor like `debug(creating prometheus metrics store)`). There are not that many places in the code where factory is constructed (more so in test than in prod code).

File: internal/metrics/prometheus/factory.go [hunk 3]
```diff
@@ -148,8 +154,13 @@ func (f *Factory) Gauge(options metrics.Options) metrics.Gauge {
 		Help: help,
 	}
 	gv := f.cache.getOrMakeGaugeVec(opts, labelNames)
+	labelValues := f.tagsAsLabelValues(labelNames, tags)
+	metric, err := gv.GetMetricWithLabelValues(labelValues...)
```
Comment (yurishkuro) [inline internal/metrics/prometheus/factory.go:158]: IIUC WithLabelValues could panic on bad strings but GetMetricWithLabelValues would return an error. But doesn't prom library have some utility to actually sanitize the strings to something valid? If think it's better to record a slightly different label with special characters encoded than to silently ignore the data.

Comment (iypetrov) [reply internal/metrics/prometheus/factory.go:158]: I've done some research on this topic, and here are my findings:

- I couldn't find in the Prometheus library functionality for handling string sanitization. In general this responsibility is left to the user of the library.

> // While populating dto.Metric, it is the responsibility of the
> // implementation to ensure validity of the Metric protobuf (like valid
> // UTF-8 strings or syntactically valid metric and label names). It is
> // recommended to sort labels lexicographically. Callers of Write should
> // still make sure of sorting if they depend on it.

- There are 2 options for replacing the [WithLabelValues(lvs ...string)](https://pkg.go.dev/github.com/prometheus/client_golang@v1.22.0/prometheus#CounterVec.WithLabelValues):
    - [GetMetricWithLabelValues(lvs ...string)](https://pkg.go.dev/github.com/prometheus/client_golang@v1.22.0/prometheus#CounterVec.GetMetricWithLabelValues)
        - Pros:
            - It accepts the same arguments as WithLabelValues.
        - Cons:
            - Prone to mistakes caused by an incorrect order of arguments.
    - [GetMetricWith(labels Labels)](https://pkg.go.dev/github.com/prometheus/client_golang@v1.22.0/prometheus#CounterVec.GetMetricWith)
        - Pros:
            - A more robust approach that helps prevent potential side effects and unexpected behavior.
        - Cons:
            - Requires a bit more effort to implement, because it accepts slightly different argument. 
            - Introduces performance overhead if there are many labels. 
    
    >    Note that for more than one label value, this method is prone to mistakes caused by an incorrect order of 
    >     arguments. Consider GetMetricWith(Labels) as an alternative to avoid that type of mistake. For higher label 
    >     numbers, the latter has a much more readable (albeit more verbose) syntax, but it comes with a performance  
    >     overhead (for creating and processing the Labels map).  

    IMO it is worth the effort to use **GetMetricWith**, because it is important to avoid potential unexpected side effects at all cost.

- For the UTF-8 sanitization topic, I founded 2 approaches that might solve the problem:
    - [strings.ToValidUTF8](https://pkg.go.dev/strings#ToValidUTF8): We can use it to directly replace every character that is invalid with empty space.
        ```go
        import "strings"

        sanitized := strings.ToValidUTF8(input, "")
        ```
    - [runes.ReplaceIllFormed](https://pkg.go.dev/golang.org/x/text@v0.25.0/runes#ReplaceIllFormed): We can use it for more advanced replacement of invalid characters, so that users are aware there were issues with them(we already use `golang.org/x/text` library, so we don't introduce extra dependency).
        ```go
        import (
            "golang.org/x/text/transform"
            "golang.org/x/text/runes"
            "unicode/utf8"
            "strings"
            "io/ioutil"
       )

      func sanitizeUTF8(input string) (string, error) {
            t := transform.Chain(runes.ReplaceIllFormed(), transform.Nop)
            result, _, err := transform.String(t, input)
            return result, err
        }
        ```
    IMO it is better approach to use **ReplaceIllFormed**, because:
    - We avoid silently removing characters that users might expect to see.
    - If all characters in the given label are invalid UTF-8, simply replacing them with empty strings could lead to errors. In such cases, a more advanced replacement mechanism is helpful to preserve the structure and inform users about the issue.

Comment (yurishkuro) [reply internal/metrics/prometheus/factory.go:158]: stepping through prom library I found that the only validation it seems to be doing is
```
	for _, val := range vals {
		if !utf8.ValidString(val) {
			return fmt.Errorf("label value %q is not valid UTF-8", val)
		}
	}
```
So we should indeed implement sanitizeUTF8 function. I would argue it should be the trace sanitizer because the only strings we use for metrics are service names and span names, and those better be valid UTF8 strings since we display then in the UI.

To make the sanitizer not hide/swallow the invalid runes we can replace them with hex equivalent, such that the string from your test "foo\x85bar" would render something like "foo_x85_bar".

We could also apply the same sanitizer in the prom factory, just in case, but it would be no-op if the span was already sanitized.

File: internal/utils/utf8.go [hunk 4]
```diff
@@ -0,0 +1,12 @@
+package utils
+
+import (
+	"golang.org/x/text/runes"
+	"golang.org/x/text/transform"
+)
+
+func SanitizeUTF8(input string) (string, error) {
```
Comment (yurishkuro) [inline internal/utils/utf8.go:8]: could you move it into internal/jptrace/sanitizer package instead? I am establishing it as the central location for model sanitizers in #7158

**Review by yurishkuro — APPROVED** [review]
