### PR TITLE
Fix sarama consumer deadlock

### LINKED ISSUE #1314: Flaky test: TestSaramaConsumerWrapper_start_Messages
https://travis-ci.org/jaegertracing/jaeger/jobs/487803410
```
=== RUN   TestSaramaConsumerWrapper_start_Messages
2019-02-02T09:46:32.154Z	DEBUG	consumer/deadlock_detector.go:151	Starting global deadlock detector
2019-02-02T09:46:32.155Z	INFO	consumer/consumer.go:77	Starting main loop
2019-02-02T09:46:32.155Z	INFO	consumer/consumer.go:162	Starting error handler	{"partition": 316}
2019-02-02T09:46:32.155Z	INFO	consumer/consumer.go:111	Starting message handler	{"partition": 316}
2019-02-02T09:46:32.156Z	DEBUG	consumer/consumer.go:134	Got msg	{"msg": {"Key":null,"Value":null,"Topic":"morekuzambu","Partition":316,"Offset":1,"Timestamp":"0001-01-01T00:00:00Z","BlockTimestamp":"0001-01-01T00:00:00Z","Headers":null}}
2019-02-02T09:46:32.156Z	INFO	consumer/processor_factory.go:62	Creating new processors	{"partition": 316}
2019-02-02T09:46:32.157Z	DEBUG	processor/parallel_processor.go:50	Spawning goroutines to process messages	{"num_routines": 1}
2019-02-02T09:46:32.158Z	INFO	consumer/consumer.go:155	Closing partition consumer	{"partition": 316}
2019-02-02T09:46:32.158Z	INFO	consumer/consumer.go:131	Message channel closed. 	{"partition": 316}
2019-02-02T09:46:32.158Z	DEBUG	processor/parallel_processor.go:75	Initiated shutdown of processor goroutines
2019-02-02T09:46:32.158Z	INFO	processor/parallel_processor.go:78	Completed shutdown of processor goroutines
2019-02-02T09:46:32.158Z	INFO	consumer/consumer.go:173	Finished handling errors	{"partition": 316}
2019-02-02T09:46:32.158Z	INFO	consumer/consumer.go:158	Closed partition consumer	{"partition": 316}
2019-02-02T09:46:32.158Z	DEBUG	consumer/deadlock_detector.go:195	Closing deadlock detector	{"partition": 316}
2019-02-02T09:46:32.158Z	INFO	consumer/consumer.go:155	Closing partition consumer	{"partition": 316}
2019-02-02T09:46:32.158Z	INFO	consumer/deadlock_detector.go:115	Closing ticker routine	{"partition": 316}
2019-02-02T09:46:32.159Z	INFO	consumer/consumer.go:158	Closed partition consumer	{"partition": 316}
2019-02-02T09:46:32.159Z	DEBUG	consumer/deadlock_detector.go:179	Closing all partitions deadlock detector
2019-02-02T09:46:32.159Z	INFO	consumer/consumer.go:106	Closing parent consumer
--- FAIL: TestSaramaConsumerWrapper_start_Messages (0.01s)
    <autogenerated>:1: PASS:	Process(*consumer.saramaMessageWrapper)
	Error Trace:	metricstest.go:49
			metricstest.go:37
			consumer_test.go:167
	Error:      	Not equal: 
	            	expected: int(0)
	            	actual  : int64(1)
	Test:       	TestSaramaConsumerWrapper_start_Messages
	Messages:   	expected metric name: sarama-consumer.partitions-held, tags: map[]
2019-02-02T09:46:32.161Z	DEBUG	consumer/deadlock_detector.go:159	Closing global ticker routine
```

### PR DESCRIPTION
**Pull request by albertteoh**
Signed-off-by: albertteoh <albert.teoh@logz.io>

## Which problem is this PR solving?
- Closes #1314

## Short description of the changes
Prevent deadlock between the `handleErrors()` and `Close()` functions trying to acquire the `partitionLock` and access the partition WaitGroup by:
- Removing per-partition WaitGroups
- Removing the need for acquiring the `partitionLock` within `Close()`

Additional improvements:
- More correct ordering of `close` calls: Ensure underlying sarama consumer is closed first to prevent repartitioning, causing potentially new partition consumers to be created that attempt to write to already closed channels.
- Instead, `Close()` will rely on `Consumer`-scoped WaitGroups to determine graceful closure of message and error handlers. These WaitGroups will be managed through goroutines monitoring `messagesDone` and `errorsDone` channels, which will be produced to by the respective handler functions.
- Remove the redundant loop to close partition consumers which is already performed by closing the aforementioned underlying sarama consumer.
- Additional diagnostic logging, mostly at debug, to help pickup race-related errors.
- Sarama tests use the `New` Consumer constructor to DRY up duplicated construction logic.

### Testing
- Local unit tests have not failed any Sarama tests.
- Confirm this failure no longer occurs on Travis branch builds (in fork) on Sarama tests.
- Local integration tests with Kafka, Cassandra, collector, agent, query and mock trace generator running:
  - Start ingester binary `./cmd/ingester/ingester-darwin-amd64 --log-level debug`:
    - Confirm successful startup.
    - Confirm span data consumed and showing correctly in Jaeger UI.
    - Confirm metrics look fine: `rate(jaeger_kafka_spans_written_total[5m])` and `rate(jaeger_ingester_sarama_consumer_messages_total[5m])` more or less line up.
  - Manually send SIGINT with Ctrl+C to trigger shutdown:
    - Confirm shutdown completes without hanging.
    - Confirm no Kafka consumer _related_ error messages or panics present.
    - Test under two conditions: when there is 0 lag, and when the consumer is lagging behind; terminating while busy consuming messages to catch potential race conditions.
  - Force a race condition between Consumer start and shutdown to test potential race conditions:
    - Command: `./cmd/ingester/ingester-darwin-amd64 --log-level debug & pid1="$\!"; sleep 0.1; kill $pid1`
    - Confirm shutdown attempted before consumer starts.
    - Confirm graceful shutdown completes successfully without error.
    - Output:
```
{"level":"debug","ts":1603594054.544082,"caller":"consumer/deadlock_detector.go:149","msg":"Global deadlock detector disabled"}
{"level":"info","ts":1603594054.5441122,"caller":"healthcheck/handler.go:128","msg":"Health Check state change","status":"ready"}
{"level":"info","ts":1603594054.544123,"caller":"flags/service.go:154","msg":"Shutting down"}
{"level":"info","ts":1603594054.544128,"caller":"healthcheck/handler.go:128","msg":"Health Check state change","status":"unavailable"}
{"level":"info","ts":1603594054.544121,"caller":"consumer/consumer.go:85","msg":"Starting main loop"}
{"level":"debug","ts":1603594054.544126,"caller":"consumer/consumer.go:107","msg":"Waiting for done signals"}
{"level":"info","ts":1603594054.5441332,"caller":"consumer/consumer.go:118","msg":"Closing parent consumer"}
{"level":"debug","ts":1603594054.544141,"caller":"consumer/consumer.go:107","msg":"Waiting for done signals"}
{"level":"info","ts":1603594054.55716,"caller":"consumer/consumer.go:196","msg":"Starting error handler","partition":0}
{"level":"info","ts":1603594054.557175,"caller":"consumer/consumer.go:138","msg":"Starting message handler","partition":0}
{"level":"debug","ts":1603594054.561001,"caller":"consumer/consumer.go:121","msg":"Closing deadlock detector"}
{"level":"info","ts":1603594054.7042592,"caller":"consumer/consumer.go:206","msg":"Finished handling errors","partition":0}
{"level":"debug","ts":1603594054.704276,"caller":"consumer/consumer.go:124","msg":"Waiting for messages and errors to be handled"}
{"level":"debug","ts":1603594054.704284,"caller":"consumer/consumer.go:109","msg":"Received done signal","msg":"HandleErrors done"}
{"level":"debug","ts":1603594054.704291,"caller":"consumer/deadlock_detector.go:100","msg":"Partition deadlock detector disabled"}
{"level":"info","ts":1603594054.704301,"caller":"consumer/consumer.go:163","msg":"Message channel closed. ","partition":0}
{"level":"info","ts":1603594054.704475,"caller":"consumer/consumer.go:187","msg":"Closing partition consumer","partition":0}
{"level":"info","ts":1603594054.704489,"caller":"consumer/consumer.go:190","msg":"Closed partition consumer","partition":0}
{"level":"debug","ts":1603594054.704499,"caller":"consumer/consumer.go:109","msg":"Received done signal","msg":"HandleMessages done"}
{"level":"debug","ts":1603594054.704504,"caller":"consumer/consumer.go:128","msg":"Closing message and error done channels"}
{"level":"info","ts":1603594055.207753,"caller":"flags/service.go:162","msg":"Shutdown complete"}
```

### CODE REVIEW

**Review by yurishkuro — COMMENTED** [review]
I am concerned that this makes the logic _even more_ complex by introducing additional signaling. My suggestion was to instead simplify it by reducing # of goroutines and handing more events in a single `select{}`, i.e. messages, errors, deadlock events. The errors handling is especially trivial (just a counter bump). Then perhaps with this refactoring the WaitGroup won't be necessary at all.

**Comment by albertteoh** [comment]
> I am concerned that this makes the logic _even more_ complex by introducing additional signaling. My suggestion was to instead simplify it by reducing # of goroutines and handing more events in a single `select{}`, i.e. messages, errors, deadlock events. The errors handling is especially trivial (just a counter bump). Then perhaps with this refactoring the WaitGroup won't be necessary at all.

Yeah, good call, agree it's more complex than necessary.

I think we can do away completely with additional goroutines and channels/signalling that this PR introduced, though I would have thought a waitgroup (at consumer scope) is still necessary as we still want to block `Close()` until messages and errors have been flushed/handled.

If we use a single `select`, IIUC, would it not require introducing new channels to listen on messages, error events?

File: cmd/ingester/app/consumer/consumer.go [hunk 1]
```diff
@@ -78,17 +79,11 @@ func (c *Consumer) Start() {
 		c.logger.Info("Starting main loop")
 		for pc := range c.internalConsumer.Partitions() {
 			c.partitionMapLock.Lock()
-			if p, ok := c.partitionIDToState[pc.Partition()]; ok {
```
Comment (yurishkuro) [inline cmd/ingester/app/consumer/consumer.go:81]: Are you sure this is safe to remove? From the comment is seems like a case where a partition gets re-assigned to the same service instance, so there's a potentially another partition consumer for this partition ID already running (or more likely shutting down).

@vprithvi do you have any more color to add to this condition?

File: cmd/ingester/app/consumer/consumer.go [hunk 2]
```diff
@@ -165,12 +162,10 @@ func (c *Consumer) closePartition(partitionConsumer sc.PartitionConsumer) {
...
 func (c *Consumer) handleErrors(partition int32, errChan <-chan *sarama.ConsumerError) {
 	c.logger.Info("Starting error handler", zap.Int32("partition", partition))
-	c.partitionMapLock.Lock()
-	wg := &c.partitionIDToState[partition].wg
-	c.partitionMapLock.Unlock()
-	defer wg.Done()
+	defer c.doneWg.Done()
 
 	errMetrics := c.newErrMetrics(partition)
 	for err := range errChan {
```
Comment (yurishkuro) [inline cmd/ingester/app/consumer/consumer.go:171]: can we move this into a select inside handleMessages?

File: cmd/ingester/app/consumer/consumer.go (hunk 1 above)
Comment (vprithvi) [reply cmd/ingester/app/consumer/consumer.go:81]: We noticed the case that you described a couple of times, but weren't able to reproduce it in tests. 
Since then, many things have changed with both Kafka and Sarama. I think we can remove this now in the interest of simplifying and revisit if see problems.

Comment (yurishkuro) [reply cmd/ingester/app/consumer/consumer.go:81]: How did it manifest when it happened?  Committed offsets going backwards?

File: cmd/ingester/app/consumer/consumer.go [hunk 3]
```diff
@@ -97,31 +92,33 @@ func (c *Consumer) Start() {
...
+// handleMessages handles incoming Kafka messages on a channel
 func (c *Consumer) handleMessages(pc sc.PartitionConsumer) {
 	c.logger.Info("Starting message handler", zap.Int32("partition", pc.Partition()))
 	c.partitionMapLock.Lock()
 	c.partitionsHeld++
 	c.partitionsHeldGauge.Update(c.partitionsHeld)
-	wg := &c.partitionIDToState[pc.Partition()].wg
 	c.partitionMapLock.Unlock()
 	defer func() {
 		c.closePartition(pc)
```
Comment (vprithvi) [inline cmd/ingester/app/consumer/consumer.go:116]: Is this `closePartition` still necessary provided `internalConsumer.Close()` closes all partitions?

File: cmd/ingester/app/consumer/consumer.go (hunk 2 above)
Comment (vprithvi) [reply cmd/ingester/app/consumer/consumer.go:171]: My preference is for this to be in a separate goroutine for isolation. For e.g., having this separate would log the error in a timely manner even if message processing was hung for some reason, like a long timeout on a failing write.

Comment (yurishkuro) [reply cmd/ingester/app/consumer/consumer.go:171]: good point.

File: cmd/ingester/app/consumer/consumer.go (hunk 3 above)
Comment (albertteoh) [reply cmd/ingester/app/consumer/consumer.go:116]: Yup, I think [you're right](https://github.com/bsm/sarama-cluster/blob/v2.1.13/consumer.go#L304), @vprithvi. 👍

However, `closePartition(`) also [increments a metrics counter](https://github.com/jaegertracing/jaeger/blob/404ce68ad033ffaccda063014a60978349f015c8/cmd/ingester/app/consumer/consumer.go#L164), which is used in tests to detect whether if the partition is closed or not; neither the `Consumer` nor `PartitionConsumer` interface appear to offer an "OnClosed" callback or channel to signal successful closure of a partition.

We could instead replace `c.closePartition(pc)` with `c.partitionMetrics(pc.Partition()).closeCounter.Inc(1)` to bump up the metric and remove the `closePartition()` function, if that sounds reasonable to you?

File: cmd/ingester/app/consumer/consumer.go (hunk 1 above)
Comment (albertteoh) [reply cmd/ingester/app/consumer/consumer.go:81]: IIUC, this happens when new messages arrive on the partition (because the `Messages()` channel isn't closed yet) after the partition consumer was closed (via the `c.closePartition(p.partitionConsumer)` call), causing a new partition consumer to be created.

This PR proposes to solve this by calling `c.internalConsumer.Close()` first within `Close()` which closes the `Messages()` channel, preventing new messages from arriving, and then closes the `Partitions()` channel, preventing new PartitionConsumers from being created.

**Review by yurishkuro — DISMISSED** [review]

**Review by yurishkuro — APPROVED** [review]

**Comment by yurishkuro** [comment]
Thanks!

**Comment by albertteoh** [comment]
Thanks for the review, @yurishkuro & @vprithvi!
