### PR TITLE
Configurable deadlock detector interval for ingester. (resubmit)

### LINKED ISSUE #1125: Ingester panics when no messages is processed in 1 minute
## Requirement - what kind of business use case are you trying to solve?

Forward traces from kafka storage to elasticsearch storage with jaeger-ingester deployed to kubernetes-cluster. There are periods when traced system is not used and no traces are being recorded.

## Problem - what in Jaeger blocks you from solving the requirement?

When ingester does not process any message for `Time.Minute` process dies with:

```
{"level":"panic","ts":1539766162.6593273,"caller":"consumer/deadlock_detector.go:69","msg":"No messages processed in the last check interval"
```

That stops docker container. Kubernetes brings it back, but with exponential backoff. Each restart makes pauses longer.
If not using kubernetes or some systemd manager, that keeps starting ingester it would just die and stay that way.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

* Trust kafka client (sarama) build in fail detection mechanism. Possibly in combination with exposing kafka consumer options (like read message timeouts) to be configurable.
* Restart consumer within running process (build new consumer and bootstrap app without exiting).
* Expose configuration for deadlock_detector tick duration - does not solve a problem, but helps managing impact on business.

## Any open questions to address

Which of proposed solutions is best?

### PR DESCRIPTION
**Pull request by marqc**
Resubmit because of github failures today, and previously submitter PR seems broken

## Which problem is this PR solving?
- Resolves #1125

## Short description of the changes
- Additional configurable flag for ingester deadlock detector interval
- Value of 0 disables deadlock_detector

### CODE REVIEW

File: cmd/ingester/app/consumer/deadlock_detector.go [hunk 1]
```diff
@@ -138,21 +142,25 @@ func (s *deadlockDetector) start() {
...
-		for {
-			select {
-			case <-detector.done:
-				s.logger.Debug("Closing global ticker routine")
-				return
-			case <-ticker.C:
-				if atomic.LoadUint64(detector.msgConsumed) == 0 {
-					s.panicFunc(-1)
-					return // For tests
+		if s.interval == 0 {
```
Comment (yurishkuro) [inline cmd/ingester/app/consumer/deadlock_detector.go]: move to head of start() & exit immediately instead?

File: cmd/ingester/app/consumer/deadlock_detector_test.go [hunk 2]
```diff
@@ -112,3 +112,34 @@ func TestGlobalPanic(t *testing.T) {
...
+	d := deadlockDetector{
+		metricsFactory: metrics.NewLocalFactory(0),
+		logger:         l,
+		interval:       0,
+		panicFunc: func(partition int32) {
+			t.Errorf("Should not panic when deadlock detector is disabled")
+		},
+	}
+
+	d.start()
```
Comment (yurishkuro) [inline cmd/ingester/app/consumer/deadlock_detector_test.go]: should include a call to close(), to ensure it works as expected when goroutines are not running

File: cmd/ingester/app/flags.go [hunk 3]
```diff
@@ -85,6 +91,10 @@ func AddFlags(flagSet *flag.FlagSet) {
 		ConfigPrefix+SuffixEncoding,
 		DefaultEncoding,
 		fmt.Sprintf(`The encoding of spans ("%s" or "%s") consumed from kafka`, EncodingProto, EncodingJSON))
+	flagSet.String(
+		ConfigPrefix+SuffixDeadlockInterval,
+		DefaultDeadlockInterval.String(),
+		"Interval to check for deadlocks. If no messages gets processed in given time, ingester app will exit. Value of 0 disable deadlock check.")
```
Comment (yurishkuro) [inline cmd/ingester/app/flags.go]: s/disable/disables/

File: cmd/ingester/app/consumer/deadlock_detector_test.go (hunk 2 above)
Comment (marqc) [reply cmd/ingester/app/consumer/deadlock_detector_test.go]: added calls to close() and fixed blocked channels w/o goroutines with setting "closed" flag on detectors

File: cmd/ingester/app/consumer/deadlock_detector.go (hunk 1 above)
Comment (marqc) [reply cmd/ingester/app/consumer/deadlock_detector.go]: Cannot really do that, because without initialization of "allPartitionsDeadlockDetector" API gets broken - and NullPointerExceptions will start to appear.

I little change this code not to check for interval inside goroutine.

**Comment by marqc** [comment]
@yurishkuro I got rid of closed flag, and introduced disabled flag with short circuits as You suggested. Also changed logic to not create unnecessary channels.

File: cmd/ingester/app/consumer/deadlock_detector.go [hunk 4]
```diff
@@ -82,18 +84,23 @@ func newDeadlockDetector(metricsFactory metrics.Factory, logger *zap.Logger, int
...
+		logger:      s.logger,
+		disabled:    0 == s.interval,
 
 		incrementAllPartitionMsgCount: func() {
 			s.allPartitionsDeadlockDetector.incrementMsgCount()
 		},
 	}
 
-	go s.monitorForPartition(w, partition)
+	if s.interval == 0 {
```
Comment (yurishkuro) [inline cmd/ingester/app/consumer/deadlock_detector.go]: nit: w.disabled

File: cmd/ingester/app/consumer/deadlock_detector.go [hunk 5]
```diff
@@ -82,18 +84,23 @@ func newDeadlockDetector(metricsFactory metrics.Factory, logger *zap.Logger, int
...
+		s.logger.Debug("Partition deadlock detector disabled")
+	} else {
+		w.closePartition = make(chan struct{}, 1)
+		w.done = make(chan struct{})
```
Comment (yurishkuro) [inline cmd/ingester/app/consumer/deadlock_detector.go]: nit: I don't think it's necessary to pull these out of the main construction. It saves a couple of memory allocations, but makes the code harder to maintain.

File: cmd/ingester/app/consumer/deadlock_detector.go [hunk 6]
```diff
@@ -133,52 +140,72 @@ func (s *deadlockDetector) start() {
 	var msgConsumed uint64
 	detector := &allPartitionsDeadlockDetector{
 		msgConsumed: &msgConsumed,
-		done:        make(chan struct{}),
 		logger:      s.logger,
+		disabled:    0 == s.interval,
 	}
 
-	go func() {
+	if s.interval == 0 {
```
Comment (yurishkuro) [inline cmd/ingester/app/consumer/deadlock_detector.go]: detector.disabled

File: cmd/ingester/app/consumer/deadlock_detector.go [hunk 7]
```diff
@@ -133,52 +140,72 @@ func (s *deadlockDetector) start() {
...
-		for {
-			select {
-			case <-detector.done:
-				s.logger.Debug("Closing global ticker routine")
-				return
-			case <-ticker.C:
-				if atomic.LoadUint64(detector.msgConsumed) == 0 {
-					s.panicFunc(-1)
-					return // For tests
+		detector.done = make(chan struct{})
```
Comment (yurishkuro) [inline cmd/ingester/app/consumer/deadlock_detector.go]: nit: don't pull this out, keep where it was

File: cmd/ingester/app/consumer/deadlock_detector.go [hunk 8]
```diff
@@ -133,52 +140,72 @@ func (s *deadlockDetector) start() {
...
 func (s *deadlockDetector) close() {
+	if s.allPartitionsDeadlockDetector.disabled {
+		return
+	}
 	s.logger.Debug("Closing all partitions deadlock detector")
 	s.allPartitionsDeadlockDetector.done <- struct{}{}
 }
 
 func (s *allPartitionsDeadlockDetector) incrementMsgCount() {
+	if s.disabled {
```
Comment (yurishkuro) [inline cmd/ingester/app/consumer/deadlock_detector.go]: not necessary.

File: cmd/ingester/app/consumer/deadlock_detector.go [hunk 9]
```diff
@@ -133,52 +140,72 @@ func (s *deadlockDetector) start() {
...
+		return
+	}
 	atomic.AddUint64(s.msgConsumed, 1)
 }
 
 func (w *partitionDeadlockDetector) closePartitionChannel() chan struct{} {
+	if w.disabled {
```
Comment (yurishkuro) [inline cmd/ingester/app/consumer/deadlock_detector.go]: not necessary

File: cmd/ingester/app/consumer/deadlock_detector.go [hunk 10]
```diff
@@ -133,52 +140,72 @@ func (s *deadlockDetector) start() {
...
 func (w *partitionDeadlockDetector) close() {
+	if w.disabled {
+		return
+	}
 	w.logger.Debug("Closing deadlock detector", zap.Int32("partition", w.partition))
 	w.done <- struct{}{}
 }
 
 func (w *partitionDeadlockDetector) incrementMsgCount() {
+	if w.disabled {
```
Comment (yurishkuro) [inline cmd/ingester/app/consumer/deadlock_detector.go]: not necessary

File: cmd/ingester/app/flags_test.go [hunk 11]
```diff
@@ -51,4 +54,15 @@ func TestFlagDefaults(t *testing.T) {
 	assert.Equal(t, DefaultGroupID, o.GroupID)
 	assert.Equal(t, DefaultParallelism, o.Parallelism)
 	assert.Equal(t, DefaultEncoding, o.Encoding)
+	assert.Equal(t, DefaultDeadlockInterval, o.DeadlockInterval)
+}
+
+func TestUnparsableDeadlockIntervalFlag(t *testing.T) {
```
Comment (yurishkuro) [inline cmd/ingester/app/flags_test.go]: Shouldn't it cause an error in flags parsing instead? This is what happens when I pass `hello` as a timeout
```
$ go run ./cmd/query/main.go --cassandra.timeout=hello
Error: invalid argument "hello" for "--cassandra.timeout" flag: time: invalid duration hello
Usage:
  jaeger-query [flags]
...
```

File: cmd/ingester/app/consumer/deadlock_detector_test.go [hunk 12]
```diff
@@ -112,3 +112,54 @@ func TestGlobalPanic(t *testing.T) {
...
+	f := newDeadlockDetector(mf, l, 0)
+	f.start()
+	defer f.close()
+
+	w := f.startMonitoringForPartition(1)
+
+	w.incrementMsgCount()
+	w.incrementAllPartitionMsgCount()
+	assert.Zero(t, len(w.closePartitionChannel()))
+	w.close()
```
Comment (yurishkuro) [inline cmd/ingester/app/consumer/deadlock_detector_test.go]: I am not clear what this is testing. Why calling increments should have any effect on the closePartitionChannel?
