### PR TITLE
[v2][query] Apply "Max Clock Skew Adjust" setting

### LINKED ISSUE #6565: [Bug]: Max clock skew setting not applied in v2
### What happened?

I'm having a distributed tracing setup in which some devices have a clock difference of several seconds and wanted to adjust the maximum clock skew adjustment duration.

After some digging into the config structures, I found that the yaml setting should be as follows and confirmed it's parsed and accepted by the server, as it errors on any unknown config field:

```yaml
extensions:
  jaeger_query:
    max_clock_skew_adjust: 5s
```

This is the equivalent of the `--query.max-clock-skew-adjustment=5s` of Jaeger v1.

However, it seems this setting is not being applied in v2 at all, as regardless of what duration is set, it always applies the default of 1 second.

### Steps to reproduce

1. Have a Jaeger instance and two OTLP clients set up with different clock timing.
  1.1. The clients should have a clock difference of at least a few seconds.
  1.2. The clients must be setup for distributed tracing so their traces are combined in Jaeger.
3. Configure Jaeger to accept larger durations that 1 second.
4. View a trace in the UI that is a distributed trace of both clients.
5. Verify that the spans of the clients are far apart and not normalized, despite the configured max clock skew adjustment. A warning will be shown in the spans, saying that the clock skew exceeds the limit.

### Expected behavior

The Jaeger server should apply the max clock skew adjustment setting accordingly.

### Relevant log output

```shell

```

### Screenshot

_No response_

### Additional context

_No response_

### Jaeger backend version

v2.2.0

### SDK

Rust setup with `tracing`, `tracing-subscriber`, `tracing-opentelemetry` and various crates from the [opentelemetry-rust](https://github.com/open-telemetry/opentelemetry-rust) project.

All with the latest version as of writing, but this appears to be no client-side error anyway.

### Pipeline

OTEL SDK -> [OTLP] -> Jaeger v2

Same pipeline for 2 clients, but the clients are on different installments:
- Server system receiving requests.
- Android app sending requests.

In a local setup the server is run in Docker, and the app is run in an Android emulator.

### Stogage backend

Badger

### Operating system

Linux

### Deployment model

Docker Compose

### Deployment configs

```shell

```

### PR DESCRIPTION
**Pull request by dnaka91**
Apply the `max_clock_skew_adjust` setting to the query service during initialization.

The maximum clock skew adjustment setting for the query component is properly read during initialization, but not applied in the v2 server in the end. This causes it to always default to 1 second, regardless of the configuration value.

## Which problem is this PR solving?

- Resolves #6565 

## Description of the changes

- Initialize and set the `Adjuster` on both the v1 and v2 query options.
- The config defaults to `0` so applying this unconditionally would now disable the clock skew adjustment instead of defaulting to `1s`? However, the same _seems to be done_ in the older services from v1.
  - Having a default of `1s` instead of `0` (which disables adjustments completely) might have been an accident?

## How was this change tested?

- Not testing so far.

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [x] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `npm run lint` and `npm run test`

### CODE REVIEW

File: cmd/jaeger/internal/extension/jaegerquery/server.go [hunk 1]
```diff
@@ -100,6 +102,10 @@ func (s *server) Start(ctx context.Context, host component.Host) error {
 	if err := s.addArchiveStorage(&opts, &v2opts, host); err != nil {
 		return err
 	}
+
+	opts.Adjuster = adjuster.Sequence(querysvc.StandardAdjusters(s.config.MaxClockSkewAdjust)...)
+	v2opts.Adjuster = v2adjuster.Sequence(v2adjuster.StandardAdjusters(s.config.MaxClockSkewAdjust)...)
```
Comment (yurishkuro) [inline cmd/jaeger/internal/extension/jaegerquery/server.go:107]: @mahadzaryab1 did we miss adjusters altogether in query extension?

File: cmd/jaeger/config.yaml [hunk 2]
```diff
@@ -32,6 +32,7 @@ extensions:
       traces_archive: another_store
     ui:
       config_file: ./cmd/jaeger/config-ui.json
+    max_clock_skew_adjust: 5s
```
Comment (yurishkuro) [inline cmd/jaeger/config.yaml:35]: we don't want this in the default config

Comment (dnaka91) [reply cmd/jaeger/config.yaml:35]: Sure no problem, I'll remove it again.

Was just wondering where to put this to make people aware. Because the v2 docs are a WIP with only sample configs.

Even had to clone the repo and search through the code for a good 20 minutes or so to even realize it exists 😅.

So any other example config where I should put it or does it warrant a new config?

File: cmd/jaeger/internal/extension/jaegerquery/server.go (hunk 1 above)
Comment (mahadzaryab1) [reply cmd/jaeger/internal/extension/jaegerquery/server.go:107]: @yurishkuro We didn;t miss the adjusters - they're applied by default in the query service (https://github.com/jaegertracing/jaeger/blob/main/cmd/query/app/querysvc/v2/querysvc/service.go#L82-L85). However, it looks like we weren't propagating the MaxClockSkewAdjust value all the way down to the query service.

File: cmd/jaeger/config.yaml (hunk 2 above)
Comment (yurishkuro) [reply cmd/jaeger/config.yaml:35]: you can add it commented out, the the same value as the current default.

File: cmd/jaeger/internal/extension/jaegerquery/server.go (hunk 1 above)
Comment (yurishkuro) [reply cmd/jaeger/internal/extension/jaegerquery/server.go:107]: then it needs a bit of a bigger change to propagate the value via QuerySvcOptions -- @dnaka91 fyi

**Comment by dnaka91** [comment]
@yurishkuro I adjusted the PR to instead pass down the value through the service options and make the adjuster internal. I hope I understood your comment correctly by that change idea.

There didn't seem to be any reason to keep the adjuster public and imho this way it's clearer as there is only one place that sets the adjuster field.

File: cmd/query/app/flags.go [hunk 3]
```diff
@@ -94,7 +96,7 @@ func AddFlags(flagSet *flag.FlagSet) {
 	flagSet.Bool(queryLogStaticAssetsAccess, false, "Log when static assets are accessed (for debugging)")
 	flagSet.String(queryUIConfig, "", "The path to the UI configuration file in JSON format")
 	flagSet.Bool(queryTokenPropagation, false, "Allow propagation of bearer token to be used by storage plugins")
-	flagSet.Duration(queryMaxClockSkewAdjust, 0, "The maximum delta by which span timestamps may be adjusted in the UI due to clock skew; set to 0s to disable clock skew adjustments")
+	flagSet.Duration(queryMaxClockSkewAdjust, defaultMaxClockSkewAdjust, "The maximum delta by which span timestamps may be adjusted in the UI due to clock skew; set to 0s to disable clock skew adjustments")
```
Comment (yurishkuro) [inline cmd/query/app/flags.go:99]: please don't change the default

File: cmd/query/app/flags.go [hunk 4]
```diff
@@ -140,18 +142,20 @@ func (qOpts *QueryOptions) InitFromViper(v *viper.Viper, logger *zap.Logger) (*Q
...
 func (qOpts *QueryOptions) BuildQueryServiceOptions(storageFactory storage.BaseFactory, logger *zap.Logger) *querysvc.QueryServiceOptions {
-	opts := &querysvc.QueryServiceOptions{}
+	opts := &querysvc.QueryServiceOptions{
+		MaxClockSkewAdjust: qOpts.MaxClockSkewAdjust,
+	}
 	if !opts.InitArchiveStorage(storageFactory, logger) {
 		logger.Info("Archive storage not initialized")
 	}
 
-	opts.Adjuster = adjuster.Sequence(querysvc.StandardAdjusters(qOpts.MaxClockSkewAdjust)...)
```
Comment (yurishkuro) [inline cmd/query/app/flags.go:148]: why do we need to change this? I think the big might be in `qOpts.MaxClockSkewAdjust` not being assigned. No other changes are required.

Comment (dnaka91) [reply cmd/query/app/flags.go:148]: Sorry I might have misunderstood your [comment](
https://github.com/jaegertracing/jaeger/pull/6566#discussion_r1924588674) from yesterday then.

From that comment I gathered that the old way of setting the adjuster early is not the way to go anymore? So I moved the `MaxClockSkewAdjust` value into the `QueryServiceOptions` to propagate it. But with propagating it down to where its instantiated there is no need to assign the adjuster from outside anymore.

I can of course restore the previous version where we explicitly assign the adjuster from outside its module so it won't use the default value (as does the other part of the code).

**Comment by yurishkuro** [comment]
We have a bit of a mess right now:
  * `cmd/query/app/flags.go` uses CLI flag to set `qOpts.MaxClockSkewAdjust` and then uses that to initialize Adjuster in v1/v2 QueryServiceOptions
  * at the same time, v1/v2 QueryService constructors check if Adjuster is null and initialize it with `defaultMaxClockSkewAdjust`
  * meanwhile `cmd/jaeger/internal/extension/jaegerquery/server.go` creates v1/v2 QueryServiceOptions without Adjuster

As a result, in v1 the user-settings are respected, but in v2 we always end up with `defaultMaxClockSkewAdjust`, even though the config has a setting.

I would like to minimize duplication. My suggestion is:
  * remove Adjuster from the options altogether, 
  * make it a private field in the QS, 
  * initialize it in the constructor, 
  * extend Options structs to contain `MaxClockSkewAdjust` field
  * initialize this field in `cmd/query/app/flags.go` and `cmd/jaeger/internal/extension/jaegerquery/server.go`

cc @mahadzaryab1

File: cmd/query/app/flags.go (hunk 3 above)
Comment (yurishkuro) [inline cmd/query/app/flags.go:99]: default was 0, let's not change it

File: cmd/query/app/flags.go [hunk 5]
```diff
@@ -47,6 +45,10 @@ const (
 	queryEnableTracing         = "query.enable-tracing"
 )
 
+const (
+	defaultMaxClockSkewAdjust = time.Second
```
Comment (yurishkuro) [inline cmd/query/app/flags.go:49]:
```suggestion
	defaultMaxClockSkewAdjust = 0*time.Second
```

File: cmd/query/app/querysvc/query_service.go [hunk 6]
```diff
@@ -44,7 +45,9 @@ type StorageCapabilities struct {
 type QueryService struct {
 	spanReader       spanstore.Reader
 	dependencyReader depstore.Reader
-	options          QueryServiceOptions
+	// Adjuster is used to adjust traces before they are returned to the client.
+	adjuster adjuster.Adjuster
+	options  QueryServiceOptions
```
Comment (yurishkuro) [inline cmd/query/app/querysvc/query_service.go:50]:
```suggestion
	options          QueryServiceOptions
	adjuster         adjuster.Adjuster
```

File: cmd/query/app/querysvc/query_service.go [hunk 7]
```diff
@@ -70,12 +73,10 @@ func NewQueryService(traceReader tracestore.Reader, dependencyReader depstore.Re
 	qsvc := &QueryService{
 		spanReader:       spanReader,
 		dependencyReader: dependencyReader,
+		adjuster:         adjuster.Sequence(StandardAdjusters(defaultMaxClockSkewAdjust)...),
```
Comment (yurishkuro) [inline cmd/query/app/querysvc/query_service.go:76]: read value from options

File: cmd/query/app/querysvc/v2/querysvc/service.go [hunk 8]
```diff
@@ -48,7 +43,9 @@ type StorageCapabilities struct {
 type QueryService struct {
 	traceReader      tracestore.Reader
 	dependencyReader depstore.Reader
-	options          QueryServiceOptions
+	// Adjuster is used to adjust traces before they are returned to the client.
+	adjuster adjuster.Adjuster
+	options  QueryServiceOptions
```
Comment (yurishkuro) [inline cmd/query/app/querysvc/v2/querysvc/service.go:48]:
```suggestion
	options          QueryServiceOptions
	adjuster         adjuster.Adjuster
```

File: cmd/query/app/querysvc/query_service.go (hunk 7 above)
Comment (yurishkuro) [reply cmd/query/app/querysvc/query_service.go:76]:
```suggestion
		adjuster:         adjuster.Sequence(StandardAdjusters(options.MaxClockSkewAdjust)...),
```

File: cmd/jaeger/config.yaml [hunk 9]
```diff
@@ -32,6 +32,9 @@ extensions:
       traces_archive: another_store
     ui:
       config_file: ./cmd/jaeger/config-ui.json
+    # The maximum duration that is considered for clock skew adjustments.
+    # Defaults to 0 seconds, which means it's disabled.
+    #max_clock_skew_adjust: 0s
```
Comment (yurishkuro) [inline cmd/jaeger/config.yaml:37]:
```suggestion
    max_clock_skew_adjust: 0s
```

**Review by yurishkuro — APPROVED** [review]

**Comment by yurishkuro** [comment]
SIGSEGV in unit tests, please make sure `make test` is successful.

**Comment by dnaka91** [comment]
Sorry for that, didn't test the latest few changes anymore before heading to bed. Tests should be passing again now :bowing_man:

**Comment by dnaka91** [comment]
Ah I see some merge conflicts have come up, let me fix those (hopefully) real quick.

**Comment by yurishkuro** [comment]
Thanks!
