### PR TITLE
Fix span deduplication via correct ordering of adjusters 

### LINKED ISSUE #6001: [Bug]: ElasticSearch storage not deduplicating multiply-archived spans
### What happened?

As an SRE deploying Jaeger at a medium-sized engineering organization (the Wikimedia Foundation), I want to enable trace archival support, for the usual benefits discussed in #57: 
> Users often ask for this feature. The trace retention period is usually short, and often people would put a link to the trace into some issue tracker to improve service performance, but by the time someone starts working on the ticket the trace has already expired.

However, spans are written to our Elasticsearch(/OpenSearch) archival storage regardless of whether or not they already exist.  When archived traces are read from archival storage and displayed, this leads to spans that are duplicated exponentially by however many times 'archive' was clicked.
image

We're running Jaeger on Kubernetes using a slight modification of the official Helm chart (if curious see [chart](https://gerrit.wikimedia.org/r/plugins/gitiles/operations/deployment-charts/+/refs/heads/master/charts/jaeger/) and [values](https://gerrit.wikimedia.org/r/plugins/gitiles/operations/deployment-charts/+/refs/heads/master/helmfile.d/aux-k8s-services/jaeger/values.yaml))

### Steps to reproduce

1. Configure jaeger + OpenSearch similar to ours, with archive tracing
2. Send some tracing data
3. Archive the trace
4. Archive the trace again
5. Restart jaeger-query with `--es.max-span-age` younger than the trace is
6. Refresh the UI page for the trace

### Expected behavior

Pressing the 'archive' button on a trace that already exists in archive storage would not mutate anything in archive storage.

### Relevant log output

_No response_

### Screenshot

image
When expanded, the SpanIDs for these traces show as:
* 8d3589e43d599843
* 8d3589e43d599843_1
* 8d3589e43d599843_2
* 8d3589e43d599843_3
All child spans are similarly duplicated.

If you examine the OpenSearch index directly, you find that the spans are duplicate documents with everything identical except the index-internal `_id` field:
image

### Additional context

_No response_

### Jaeger backend version

v1.56.0

### SDK

Envoy sending OpenTelemetry

### Pipeline

Envoy -> otelcol -> jaeger-collector

### Stogage backend

OpenSearch 2.7.0

### Operating system

Linux

### Deployment model

Kubernetes

### Deployment configs

```shell
Args:                                                                                                                                                                   
      --es-archive.enabled=true                                                                                                                                             
      --es-archive.index-date-separator=.                                                                                                                                   
      --es-archive.num-replicas=2                                                                                                                                           
      --es-archive.num-shards=1                                                                                                                                             
      --es-archive.tags-as-fields.all=true                                                                                                                                  
      --es-archive.tls.enabled=true                                                                                                                                         
      --es.index-date-separator=.                                                                                                                                           
      --es.max-span-age=756h0m0s                                                                                                                                            
      --es.num-replicas=2                                                                                                                                                   
      --es.num-shards=1                                                                                                                                                     
      --es.tags-as-fields.all=true                                                                                                                                          
      --es.tls.enabled=true
[...]
    Environment:                                                                                                                                                            
      SPAN_STORAGE_TYPE:       elasticsearch                                                                                                                                
      ES_SERVER_URLS:          https://logs-api.svc.eqiad.wmnet:443                                                                                                         
      ES_USERNAME:             jaeger-prod                                                                                                                                  
      ES_PASSWORD:             <set to the key 'password' in secret 'main-jaeger-elasticsearch'>  Optional: false                                                           
      ES_ARCHIVE_SERVER_URLS:  https://logs-api.svc.eqiad.wmnet:443                                                                                                         
      ES_ARCHIVE_USERNAME:     jaeger-prod                                                                                                                                  
      ES_ARCHIVE_PASSWORD:     <set to the key 'password' in secret 'main-jaeger-elasticsearch'>  Optional: false                                                           
      QUERY_BASE_PATH:         /
```

### PR DESCRIPTION
**Pull request by cdanis**
## Which problem is this PR solving?
- Resolves #6001 (again).  If ClockSkew adjuster is run before DedupeBySpanHash, it will add warnings to spans with duplicate span IDs, which affect the hash code, which means that you "dedupe" to two copies of each span, not one.

## Description of the changes
- Change the order of Adjusters so that DedupeBySpanHash runs before ClockSkew

## How was this change tested?
- In production, lightly
- Also unit tested

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [x] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `yarn lint` and `yarn test`

### CODE REVIEW

**Comment by cdanis** [comment]
I am not sure how to add unittests for this and would welcome advice.

**Comment by yurishkuro** [comment]
> Resolves 6001 (again)

can you elaborate why "again"? Are we missing a unit test that should catch the issue of ordering?

**Comment by cdanis** [comment]
On Wed, Oct 23, 2024 at 6:47 PM Yuri Shkuro ***@***.***>
wrote:

> can you elaborate why "again"? Are we missing a unit test that should
> catch the issue of ordering?
>

Yes, we are. I would appreciate advice on the best existing test to add
that to.

>

**Comment by yurishkuro** [comment]
Can be a new test, we have several in the directory

**Comment by cdanis** [comment]
ok @yurishkuro ptal

File: cmd/query/app/http_handler_test.go [hunk 1]
```diff
@@ -162,6 +162,33 @@ func TestGetTraceSuccess(t *testing.T) {
...
+	}
+
+	ts := initializeTestServer(t)
+	ts.spanReader.On("GetTrace", mock.AnythingOfType("*context.valueCtx"), mock.AnythingOfType("model.TraceID")).
+		Return(dupedMockTrace, nil).Once()
+
+	var response structuredResponse
+	err := getJSON(ts.server.URL+`/api/traces/123456`, &response)
+	require.NoError(t, err)
+	assert.Empty(t, response.Errors)
```
Comment (yurishkuro) [inline cmd/query/app/http_handler_test.go:187]: Is this the part that's mean to ensure the order? Are you sure they would be in `response.Errors`, and not in `Span.Warnings`?
```suggestion
	assert.Empty(t, response.Errors, "clock skew adjuster logs warnings if spans are not deduped first")
```
Overall though I think it's a weak test, checking for something that's not there (like proving a negative). It would be stronger if it was simultaneously contrasted with the opposite behavior, i.e.
  1. run with only clock skew adjuster, observe the error
  2. run with all adjusters, observe lack of error

Comment (yurishkuro) [reply cmd/query/app/http_handler_test.go:189]: this check was indeed incorrect, if succeeded with the original adjuster order. I added another check below for span warnings, which was actually showing the errors.

**Review by yurishkuro — APPROVED** [review]

File: cmd/query/app/http_handler_test.go (hunk 1 above)
Comment (cdanis) [reply cmd/query/app/http_handler_test.go:189]: thank you very much for the fix, I had started digging on this but wasn't going to have time to look until at least today :)
