### PR TITLE
[fix] Allow es-index-cleaner to delete indices based on current time

### LINKED ISSUE #6236: [Bug]: Index cleaner only works once a day, even if it runs every hour.
### What happened?

I use helm chart with the images (cronjobs) jaeger-es-index-cleaner:1.57.0 and jaeger-es-rollover:1.57.0.
The rollover creates a new span every hour (for example). But the index cleaner only removes indexes older than 00:00 hours (once a day). And I would like indexes older than 24 hours to be deleted from the moment the index cleaner is launched. That is, 08:00, 09:00 and so on.
Here is the index cleaner log
```
{
  "level": "info",
  "ts": 1732172114.3503263,
  "caller": "es-index-cleaner/main.go:89",
  "msg": "Indices before this date will be deleted",
  "date": "2024-11-17T00:00:00Z"
}
```

### Steps to reproduce

Create cronjob jaeger-es-rollover whith `'{"max_age": "1h"}'` and run it every hour.
Run jaeger-es-index-cleaner every hour.

### Expected behavior

Indexes are deleted every hour, not once a day

### Relevant log output

```shell

```

### Screenshot

_No response_

### Additional context

_No response_

### Jaeger backend version

1.57.0

### SDK

_No response_

### Pipeline

_No response_

### Stogage backend

_No response_

### Operating system

_No response_

### Deployment model

_No response_

### Deployment configs

```shell

```

### PR DESCRIPTION
**Pull request by Asatyam**
## Which problem is this PR solving?
- Resolves #6236 
## Description of the changes
- Changes the es-index-cleaner to remove indices older than 24 hours from the time it runs, so deletions happen hourly instead of just at midnight.
## How was this change tested?
- CI

## Checklist
- [x] I have read https://github.com/jaegertracing/jaeger/blob/master/CONTRIBUTING_GUIDELINES.md
- [x] I have signed all commits
- [x] I have added unit tests for the new functionality
- [x] I have run lint and test steps successfully
  - for `jaeger`: `make lint test`
  - for `jaeger-ui`: `npm run lint` and `npm run test`

### CODE REVIEW

**Review by yurishkuro — COMMENTED** [review]
The change looks ok but it's a breaking change that should be handled according to our policy that is documented in CONTRIBUTING.

**Comment by Asatyam** [comment]
@yurishkuro PTAL

**Comment by yurishkuro** [comment]
Please include evidence of testing

File: cmd/es-index-cleaner/app/cutoff_time.go [hunk 1]
```diff
@@ -0,0 +1,17 @@
...
+
+package app
+
+import (
+	"time"
+)
+
+func CalculateDeletionCutoff(currTime time.Time, numOfDays int, relativeIndexEnabled bool) time.Time {
+	year, month, day := currTime.Date()
+	cutoffTime := time.Date(year, month, day, 0, 0, 0, 0, time.UTC).AddDate(0, 0, 1)
```
Comment (yurishkuro) [inline cmd/es-index-cleaner/app/cutoff_time.go:12]:
```suggestion
	// tomorrow midnight
	cutoffTime := time.Date(year, month, day, 0, 0, 0, 0, time.UTC).AddDate(0, 0, 1)
```

**Review by yurishkuro — APPROVED** [review]
